from pathlib import Path
import json,hashlib,datetime,subprocess
R=Path(__file__).resolve().parents[4]
A=Path('verification/evidence/2026-09-15-host-evidence-reuse-source-review-attempt-01')
B=A/'b-hardware-install';P=Path('verification/evidence/2026-09-15-host-unvalidated-source-families-attempt-01')
def sha(b):return hashlib.sha256(b).hexdigest()
def dump(p,v): (R/p).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
S={};D=[]
def src(k,p,kind='RETAINED_SOURCE',revision=None,url=None,**kw):
 p=Path(p);S[k]={'path':str(p),'sha256':sha((R/p).read_bytes()),'source_kind':kind,**kw}
 if revision:S[k]['revision']=revision
 if url:S[k]['url']=url
 return k
def ref(k,p):
 f=R/S[k]['path']
 if p.startswith('/lines/'):
  a,b=map(int,p.split('/')[-1].split('-'));v='\n'.join(f.read_text().splitlines()[a-1:b])
 else:
  v=json.loads(f.read_text())
  for a in p.strip('/').split('/'):v=v[int(a)] if isinstance(v,list) else v[a.replace('~1','/').replace('~0','~')]
 assert isinstance(v,str),(k,p,type(v));return {'source':k,'text_pointer':p,'source_excerpt':v}
def lines(k,a,b=None):return ref(k,f'/lines/{a}-{b or a}')
def find(k,needle,before=0,after=0):
 a=(R/S[k]['path']).read_text().splitlines();i=next(i for i,l in enumerate(a) if needle in l);return lines(k,max(1,i+1-before),min(len(a),i+1+after))
old=json.loads((R/P/'s1/sources.json').read_text())['sources']
for k in ['machine_diag','machines','systemreq','remote','runtime_diag']:
 S[k]=old[k];assert sha((R/S[k]['path']).read_bytes())==S[k]['sha256']
for f in ['hosting-overview','verification-stages','vms']:
 src(f,B/f'sources/published-{f}.mdx','PUBLISHED_VENDOR_DOCUMENTATION','175a318c27750ea64da94f043dda39ec5cb26259',f'https://docs.vast.ai/host/{f}',provenance='Exact upstream Git object, predating this batch; direct live page read on 2026-09-15 corroborated selected text. Published semantics, not backend execution.')
src('setup',A/'a-policy-account/setup-browser-response.json','PUBLISHED_VENDOR_DOCUMENTATION',url='https://cloud.vast.ai/host/setup')
src('owner',A/'owner-source-1518.json','PRIMARY_ENGINEERING_SOURCE')
src('keyowner',A/'owner-installer-key-1518.json','PRIMARY_ENGINEERING_SOURCE')
src('ticket',A/'requirement-con-1516.json','ORIGINAL_REQUIREMENT')
src('ownerports',P/'s2-s3/owner-58492.md','PRIMARY_ENGINEERING_SOURCE')
src('ownerports2',P/'s2-s3/owner-58017.md','PRIMARY_ENGINEERING_SOURCE')
src('publicprev',P/'s2-s3/public-sources.json','PUBLISHED_VENDOR_DOCUMENTATION')
src('toolprev','verification/evidence/2026-09-14-host-unvalidated-evidence-attempt-02/source-diagnostics/primary-tool-sources.json','PUBLISHED_VENDOR_DOCUMENTATION')
src('safe','verification/evidence/2026-09-02-host-safe-readonly-attempt-01/result.md','DIRECT_FUNCTIONAL_PARTIAL','2026-09-02 authorized HOST_VV_TARGET')
src('safeplan','verification/evidence/2026-09-02-host-safe-readonly-attempt-01/plan.md','RETAINED_EXECUTION_PLAN')
src('follow','verification/evidence/2026-09-02-host-self-test-log-follow-attempt-01/result.md','DIRECT_FUNCTIONAL_PARTIAL','2026-09-02 authorized HOST_VV_TARGET')
src('kernelfollow','verification/evidence/2026-09-02-host-kernel-log-follow-attempt-01/result.md','DIRECT_FUNCTIONAL_PARTIAL','2026-09-02 authorized HOST_VV_TARGET')
src('vmhelper','verification/evidence/2026-09-08-host-client-unblocking-attempt-01/vm-helper-source-retest-02.json','INSPECTED_INSTALLED_SOURCE','installed helper SHA bb7c5922931aacbdff85528fcfb52733639db00361ae00b232f3cbfad0d251de')
src('vmabort','verification/evidence/2026-08-31-host-privileged-attempt-01/result.md','RETAINED_COUNTEREXAMPLE','2026-08-31 disqualified VM environment; diagnostic counterexample only')
src('apikeyrun','verification/evidence/2026-09-02-cli-set-api-key-permissions-attempt-01/result.md','RETAINED_RUNTIME_DEFECT','Vast CLI 1.5.6, macOS arm64, Python3.14.6')
# Immutable auth source, no credentials or execution.
data=subprocess.check_output(['git','show','1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc:vastai/cli/commands/auth.py'],cwd='/private/tmp/host-docs-d10-3o6tftdu/current-cli')
(R/B/'sources/auth.py').write_bytes(data);src('auth',B/'sources/auth.py','CANONICAL_IMPLEMENTATION_SOURCE','1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc')
# Compact public installer excerpts; preserve original file hash and original lines.
f=Path('/Users/hanneszietsman/VastAi/CON-1584/docs-pr153-host-cli-api-sdk/.orchestra/h100x4-install-history/source-inspection-01-restricted/public-install');a=f.read_text().splitlines()
ex={'origin_url':'https://console.vast.ai/install','source_sha256':sha(f.read_bytes()),'source_capture':'Existing public installer source retained 2026-09-08; mutable URL, not a new download or installed revision assertion.','excerpts':{}}
for k,l,h in [('quota',924,977),('fstab',1038,1054),('check',1102,1115),('logs',1397,1408)]:ex['excerpts'][k]={'original_lines':[l,h],'text':'\n'.join(a[l-1:h])}
dump(B/'sources/installer-excerpts.json',ex);src('installer',B/'sources/installer-excerpts.json','INSPECTED_PUBLIC_INSTALLER_SOURCE')
# Primary manuals read on 2026-09-15. Definitions below are reviewer paraphrases, not runtime evidence.
M={}
def manual(k,url,version,locator,definition,quote=None):
 M[k]={'url':url,'version':version,'locator':locator,'reviewed_definition':definition,'limit':'Source/argument definition only; no execution, host configuration, universal outcome or compatibility qualification.'}
 if quote:M[k]['quote']=quote
manual('amd','https://docs.kernel.org/6.8/admin-guide/kernel-parameters.html','Linux6.8','amd_iommu lines473-489; intel_iommu2249-2253','Linux6.8 lists AMD IOMMU options including off, force_enable, force_isolation and page-table options; on is not a supported option. intel_iommu=on explicitly enables the Intel driver. Do not substitute force_enable: it overrides known-buggy-platform handling.')
manual('amdparser','https://raw.githubusercontent.com/torvalds/linux/v6.8/drivers/iommu/amd/init.c','Linux tagv6.8','parse_amd_iommu_options3256-3285; amd_iommu_detect3208-3225; __setup3427','The AMD parameter parser has no on branch; unknown strings are skipped without setting an enable flag. Detection initializes discovered supported AMD IOMMU hardware subject to firmware/global disable and other prerequisites. This does not prove any particular motherboard is configured.')
manual('ubuntu_iommu','https://ubuntu.com/server/docs/how-to/graphics/gpu-virtualization-with-qemu-kvm/','Ubuntu Server current manual read2026-09-15','Preparing IOMMU287-350','Enable firmware virtualization/IOMMU, inspect dmesg and IOMMU groups, and isolate the device for passthrough. Recent Ubuntu kernels normally initialize supported IOMMUs automatically; hardware-specific tuning may still be necessary. Nouveau can need blacklisting to release a device.')
manual('dpkg','https://manpages.ubuntu.com/manpages/noble/man1/dpkg.1.html','Ubuntu24.04 dpkg','--force-confold/--force-confdef343-346','With confdef and confold together, dpkg takes the default conffile action when one exists; confold is the fallback when there is no default. This combination does not guarantee preservation of every existing conffile.','in which case the default action is preferred.')
manual('debconf','https://manpages.ubuntu.com/manpages/noble/man7/debconf.7.html','Ubuntu24.04 debconf','FRONTENDS/noninteractive; unattended package installation','DEBIAN_FRONTEND=noninteractive makes debconf use default answers without interactive questions. This addresses debconf questions, not every arbitrary prompt a package script could issue.')
manual('fstab','https://manpages.ubuntu.com/manpages/noble/man5/fstab.5.html','Ubuntu24.04 util-linux','fs_spec66-71','fstab supports filesystem UUID= identifiers and recommends persistent identifiers because device-name order can change. PARTUUID identifies partitions separately. The adjacent UUID= mount example needs the filesystem UUID.')
manual('raid','https://docs.kernel.org/admin-guide/md.html','Current Linux md manual read2026-09-15','chunk_size124-127; component_size156-159; consistency_policy248-256; degraded arrays65-71','RAID0 stripes data across component devices and has no redundant copy/parity; losing a component can lose the array. Redundant arrays can continue in a degraded state, but further faults can exceed their redundancy. Monitoring component/array health is useful; redundancy itself does not require a person first noticing a fault.')
manual('dockerquota','https://docs.docker.com/reference/cli/dockerd/','Docker Engine reference read2026-09-15','overlay2.size283-285','The overlay2 per-container size limit requires an XFS backing filesystem mounted with pquota. Inspect the actual backing mount and quota state; this prerequisite explains the storage-opt/XFS/pquota error without identifying which mount/configuration step failed.')
manual('tmux','https://manpages.ubuntu.com/manpages/noble/man1/tmux.1.html','tmux3.4-1ubuntu0.1','DESCRIPTION72-79','tmux sessions can detach and remain running across SSH disconnection, then reattach. The instruction to keep the install session open or use tmux protects session continuity; it does not guarantee installer completion.')
manual('nc','https://man.openbsd.org/nc.1','OpenBSD current nc manual read2026-09-15','-u90-91; -v94-95; -w98-99; -z106-107','nc defaults to TCP; -v prints verbose information, -z checks listening ports without application data, -u selects UDP, and -w2 bounds connection/idle waiting to two seconds. These options are the OpenBSD-family nc syntax used on macOS and Ubuntu netcat-openbsd; availability/version is a local prerequisite. UDP send success is not receipt proof.')
manual('tcpdump','https://manpages.ubuntu.com/manpages/noble/man8/tcpdump.8.html','Ubuntu24.04 tcpdump','OPTIONS -n/-i; filter expression; UDP packet output393','tcpdump -n avoids name conversion; -i any captures on available interfaces on Linux; udp port 40000 selects UDP packets with source or destination port40000. Privileged capture on the host can observe an externally sent datagram but does not prove a responding application.')
manual('powershell_tcp','https://learn.microsoft.com/en-us/powershell/module/nettcpip/test-netconnection?view=windowsserver2025-ps','Microsoft NetTCPIP module, Windows Server2025 reference','RemotePort53-59; Port361-363','Test-NetConnection accepts a computer/IP and -Port to test that remote TCP port. Running from an external Windows machine tests that path. curl.exe with an explicit http:// URL tests the listener HTTP response; both tools must be installed.')
manual('dotnet_udp','https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.send?view=net-9.0','Microsoft .NET9 API reference','Send(Byte[],Int32,String,Int32)64-117; example135-155','UdpClient.Send accepts bytes, byte count, destination host and port. The adjacent PowerShell constructs a UdpClient, ASCII payload, sends it to PUBLIC_IP:40000 and closes it. A returned byte count means sent, not remote receipt.')
manual('portchecker','https://portchecker.co/','Public site read2026-09-15','What is Port Checker18-20; target input57-58','The service advertises an external port check with target address/port fields. The inspected page does not explicitly define its transport as TCP; use the source-defined TCP commands above if that distinction matters.')
manual('tail','https://manpages.ubuntu.com/manpages/noble/man1/tail.1.html','coreutils9.4-3ubuntu6.3','-f61-63; descriptor behavior90','tail -f first shows the file tail, then follows appended data through its file descriptor. It does not manufacture log events, and default -f does not follow a rotated replacement filename.','output appended data as the file grows;')
manual('grep','https://manpages.ubuntu.com/manpages/noble/man1/grep.1.html','Ubuntu24.04 GNU grep','-E/-i; Other Options169-170','grep -E uses extended alternatives, -i ignores case, and --line-buffered flushes each output line. The selected expressions filter kernel messages; no matches do not establish absence of every GPU or PCIe fault.','Use line buffering on output.')
manual('journal','https://manpages.ubuntu.com/manpages/noble/man1/journalctl.1.html','Ubuntu24.04 systemd255','-k; --follow385-387','journalctl -k selects kernel messages from the current boot; -f prints the recent tail and subsequent appended entries. The pipe passes those records to the line-buffered grep filter.','continuously print new entries as they are appended to the journal.')
dump(B/'sources/primary-manual-review.json',{'record_type':'PRIMARY_MANUAL_SOURCE_REVIEW','retrieved_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sources':M});src('manuals',B/'sources/primary-manual-review.json','PUBLISHED_VENDOR_DOCUMENTATION')
def m(k):return ref('manuals',f'/sources/{k}/reviewed_definition')
def pub(k):return ref('publicprev',f'/sources/{k}/reviewed_definition')
def tool(n):return ref('toolprev',f'/sources/{n}/reviewed_definition')
C=json.loads((R/B/'claims.json').read_text())['claims'];by={x['id']:x for x in C}
DEFAULT_LIMIT='Scoped documented instruction/definition at the retained source version; no new host execution, hardware qualification or platform acceptance.'
def add(n,refs,why,replacement=None,status='PASS',methods=None,classification=None,limit=None,next_action=None,topic=None):
 x=C[n-1];assert x['id'] not in {d['id'] for d in D}
 dec='correction' if replacement is not None else 'supported' if status in ('PASS','NOT_APPLICABLE') else 'residual'
 d={'id':x['id'],'literal_sha256':x['literal_sha256'],'location':x['claim']['spans'][0],'decision':dec,'proposed_status':status,'source_refs':refs,'support_rationale':why,'limitation':limit or DEFAULT_LIMIT,'next_action':next_action}
 if replacement is not None:d['proposed_replacement']=replacement;d['defect']=why
 if methods is not None:d['proposed_methods']=methods;d['method_rationale']='The full occurrence is assessed as '+('an observed bounded command carrier plus its exact source definitions, not its parent workflow.' if 'RUNTIME_BEHAVIORAL_TEST' in methods else 'a source-defined statement or scoped diagnostic instruction; executing the operation is not asserted by this literal.')
 if classification:d['proposed_classification']=classification
 if topic:d['topic_key']=topic
 D.append(d)
PUB=['PUBLISHED_VENDOR_DOCUMENTATION','REPOSITORY_STATIC_CHECK'];CAN=['CANONICAL_IMPLEMENTATION_SOURCE'];RUN=['CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_BEHAVIORAL_TEST'];DIAG=['PUBLISHED_VENDOR_DOCUMENTATION','REPOSITORY_STATIC_CHECK']
SET=ref('setup','/excerpts/1/text');OS=ref('setup','/excerpts/5/text');PORT=ref('setup','/excerpts/4/text');ACCOUNT=ref('setup','/excerpts/6/text')
# Hardware/installation source review; each entry refers to the entire frozen literal.
add(1,[SET,OS],'The current published setup explicitly includes ARM64 as well as x86_64, so the x86-only quick check is incomplete. Architecture-specific suitability remains a separate recorded question.','- Native Ubuntu Server; check the architecture guidance below before selecting x86_64/AMD64 or ARM64 hardware.',methods=PUB)
add(2,[SET],'The live published setup explicitly requires all GPUs to be the same model.',methods=PUB)
add(3,[SET,find('ticket','AMD')],'Current Setup names NVIDIA; the older requirement excludes AMD while this page lists AMD families. Neither establishes current AMD marketplace/verification support.',status='UNVALIDATED',methods=PUB,next_action='Obtain the current supported AMD/ROCm host families and their listing/verification limits from the setup/product owner, then reconcile the quick check and AMD table together.',topic='HOST-AMD-SUPPORT-CONSISTENCY')
add(4,[SET],'The published CPU row combines ARM64 with AVX; AVX is an x86 feature and the architecture-specific requirement needs clarification.',status='UNVALIDATED',methods=PUB,next_action='Confirm which CPU feature checks apply separately to x86_64 and ARM64 hosts and reconcile the AVX and architecture rows.',topic='HOST-ARM-SUPPORT-CONSISTENCY')
add(5,[SET],'Avoiding mixed models follows the explicit same-model rule; the conditional exception requires future explicit Vast documentation, not an assumed present exception.',methods=PUB)
add(6,[lines('hosting-overview',12,13)],'This is an escalation suggestion, not a promise that Vast will add a model. Published host community support provides the appropriate contact path.',methods=PUB)
add(7,[ref('owner','/comment/paragraphs/7'),OS],'Named Engineering answer and current public Setup agree on preferred24.04 and22.04 availability.',methods=['PRIMARY_ENGINEERING_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION'])
add(8,[SET,lines('hosting-overview',37)],'Published PCIe throughput and sustained resource requirements justify checking lane/bandwidth, power and firmware layouts as preparation advice.',methods=PUB)
add(9,[OS,lines('hosting-overview',12)],'Published host setup calls for native Ubuntu Server; Windows/WSL remains a separate client CLI environment, not the prescribed host OS.',methods=PUB)
add(10,[SET,find('verification-stages','ARM64')],'The x86-only assumption contradicts published ARM64 guidance. The replacement states the actual publication conflict and directs model-specific confirmation without declaring GB10 support.','| ARM or GB10-class systems | The published setup lists ARM64 but also specifies AVX. Confirm architecture-specific requirements and GB10 support with Vast before choosing this path. |',methods=PUB,topic='HOST-ARM-SUPPORT-CONSISTENCY')
add(11,[lines('machine_diag',236,249),pub('market_ui')],'The >7GiB preflight requirement is source-defined; weak demand for an unspecified old GPU is not established by that check.','| Low-VRAM or very old GPUs | The CLI preflight requires more than 7 GiB VRAM per GPU. Check [GPU Market Metrics](/host/market-metrics) for the model before buying. |',methods=CAN+['PUBLISHED_VENDOR_DOCUMENTATION'])
add(12,[pub('market_ui'),SET],'This is a purchase-preparation checklist grounded in the metrics interface and published hardware categories; it promises no earnings or qualification.',methods=PUB)
add(13,[ACCOUNT,lines('hosting-overview',19,25)],'Published setup and original overview require a separate Host account and agreement; the local links guide troubleshooting and credential preparation.',methods=PUB)
add(14,[lines('vms',89,99),lines('hosting-overview',29,31),m('ubuntu_iommu')],'Optional VM hardware/firmware prerequisites and EPYC caution are explicit published instructions.',methods=PUB)
add(15,[SET,lines('hosting-overview',37)],'Preparation advice seeks the documented PCIe bandwidth under adequate power; no claim of a particular riser failure or measured throughput.',methods=PUB)
add(16,[lines('hosting-overview',37)],'Original public guidance explicitly anticipates near-max GPU load for the rental and requires power/heat planning.',methods=PUB)
add(17,[lines('hosting-overview',29,31)],'Published Vast instructions explicitly disable auto-updates to prevent driver updates interrupting jobs; scheduling is coherent operational advice.',methods=PUB)
add(18,[OS,ref('owner','/comment/paragraphs/10'),ref('installer','/excerpts/quota/text'),m('dockerquota')],'Current setup separates Docker renter storage onto XFS/SSD; owner and installer enforce project quotas.',methods=['PRIMARY_ENGINEERING_SOURCE','CANONICAL_IMPLEMENTATION_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION'])
add(19,[OS],'The setup storage layout separates root and Docker; confirming the intended target is a prerequisite, not a claim any disk was checked.',methods=PUB)
add(20,[ref('installer','/excerpts/quota/text')],'The public installer accepts either pquota or prjquota in its mount-option test.',methods=CAN)
add(21,[find('safe','CLM-a95c02cbab56772e'),lines('safeplan',34,43),tool(4),tool(5)],'The retained September2 carrier is the exact filesystem/mount/root-capacity command group. Required reads succeeded; optional /data0 absence is explicitly tolerated.',methods=RUN,classification='REVIEWED_BOUNDED_DIAGNOSTIC_COLLECTION',limit='September2 HOST_VV_TARGET point-in-time collection only. Historical exact tool versions/raw bytes are not newly reconstructed; no device-disposability or storage-mutation proof.')
add(22,[m('fstab')],'Backup before editing a persistent mount table is directly relevant preparation. This is advice, not proof that cp ran or the backup is recoverable.',methods=DIAG)
add(23,[ref('owner','/comment/paragraphs/10'),ref('installer','/excerpts/quota/text'),m('dockerquota')],'Owner confirms XFS quota purpose and installer/Docker specify the required backing-mount quota mechanism.',methods=['PRIMARY_ENGINEERING_SOURCE','CANONICAL_IMPLEMENTATION_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION'])
add(24,[m('fstab')],'UUID= in the adjacent fstab entry identifies the filesystem, not the disk or PARTUUID.','Use the filesystem UUID, not a device name like `/dev/nvme0n1p1`:',methods=DIAG)
add(25,[m('raid')],'RAID0 striping combines components without redundancy; may-improve throughput is conditional, not a benchmark claim. Single-device simplicity is editorial guidance.',methods=DIAG)
add(26,[m('raid')],'Redundancy can protect data before the operator notices a fault; “only help if you know” is too absolute. Monitoring remains useful.','Monitor redundant RAID arrays so you notice a failed device and can restore redundancy. Configure health checks and failure notifications for the RAID layer, NVMe/SMART health, and any storage controller or software you use. An unnoticed degraded array can suffer downtime or data loss if further failures exceed its remaining redundancy.',methods=DIAG)
add(27,[m('dockerquota'),ref('installer','/excerpts/quota/text')],'The error signals failure to satisfy the overlay/XFS/project-quota prerequisite; it does not uniquely establish a filesystem type or missing quota flag.','`--storage-opt is supported only for overlay over xfs with pquota` means Docker could not use the required XFS project-quota backing storage. Check the actual Docker mount, filesystem type, and quota options:',methods=DIAG)
add(28,[OS,ref('installer','/excerpts/quota/text')],'These are prerequisite corrections for the chosen Docker mount, not an assertion of a completed repair.',methods=CAN+['PUBLISHED_VENDOR_DOCUMENTATION'])
add(29,[PORT,lines('ownerports',16,17)],'Public inbound ports are a published verification/network requirement; Engineering defines their outside-router meaning.',methods=['PRIMARY_ENGINEERING_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION'])
add(30,[m('nc'),pub('curl'),PORT],'The lead-in assigns the following curl HTTP and nc TCP checks to an external macOS/Linux client. Options/target syntax were inspected in context; no network execution asserted.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(31,[m('powershell_tcp'),pub('curl'),PORT],'The lead-in binds the following Test-NetConnection and curl.exe block to an external Windows client; both are source-defined checks, not an observed result.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(32,[m('portchecker'),m('nc'),m('powershell_tcp')],'The service page does not explicitly identify TCP. Use the already-defined external TCP tests instead of asserting unverified transport semantics for a third-party service.','Use the TCP checks above from an external machine to test inbound TCP reachability.',methods=DIAG)
add(33,[m('tcpdump'),PORT],'The adjacent Linux tcpdump expression observes UDP port40000 packets on the host. External receipt must be observed; capture itself is not application or bidirectional proof.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(34,[m('nc'),PORT],'The following printf pipe feeds a datagram payload to nc -u -w2 from outside the LAN; nc option-family availability is a local prerequisite.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(35,[m('dotnet_udp'),PORT],'The complete following PowerShell block constructs payload bytes, sends them to the remote host/port, and closes the client; no receipt claimed.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
# Incremental coherent batch retained before remaining decisions.
def seal(state):
 dump(B/'sources.json',{'recorded_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sources':S})
 dump(B/'decisions.json',{'record_type':'B_FULL_LITERAL_SOURCE_AND_REUSE_REVIEW','state':state,'baseline_model_sha256':'6be19bf6104252cd133caf3473ca10701cb987c927bf9de66d0876880f039b71','source_index':'sources.json','source_index_sha256':sha((R/B/'sources.json').read_bytes()),'reviewed_count':len(D),'total_frozen_count':91,'decisions':D})
seal('IN_PROGRESS_35_OF_91')
src('linuxamd',B/'sources/linux-v6.8-amd-init.c','CANONICAL_IMPLEMENTATION_SOURCE','Linuxv6.8','https://raw.githubusercontent.com/torvalds/linux/v6.8/drivers/iommu/amd/init.c')
AMD=[m('amd'),lines('linuxamd',3467,3498),m('ubuntu_iommu')]
# Installer, VM and retained command-carrier decisions.
add(36,[lines('hosting-overview',25),ACCOUNT],'The original published overview expressly designates the Host setup guide as official setup documentation; this page scopes its supplemental role.',methods=PUB)
add(37,[ACCOUNT,lines('hosting-overview',19,21)],'The setup account conversion establishes the Host-enabled account prerequisite, not a present authenticated session.',methods=PUB)
add(38,[lines('hosting-overview',25),ref('keyowner','/comment/excerpt')],'Using the current setup command follows official setup and the owner refresh remedy. No token lifetime is inferred.',methods=PUB+['PRIMARY_ENGINEERING_SOURCE'])
add(39,[m('tmux')],'A persistent terminal session supports an SSH installation that may outlast the interactive connection. No successful installation is inferred.',methods=DIAG)
add(40,[lines('hosting-overview',25),ref('installer','/excerpts/quota/text'),OS],'This is conditional workflow advice: use the official installer interface, and complete concrete host prerequisites before a raw-installer fallback. It does not claim the fallback was executed or is universally equivalent to the TUI.',methods=PUB+CAN)
add(41,[ref('installer','/excerpts/quota/text'),m('dockerquota')],'The actual public installer checks the Docker backing filesystem and either accepted project-quota mount option.',methods=CAN)
add(42,[ref('keyowner','/comment/excerpt')],'The owner explicitly rejects the expiry/403 explanation; retained authority establishes refresh as remedy, not single-use or expiration semantics.','2. **Setup command or key rejected.** Refresh the setup page and copy its current installer command before retrying. Do not infer the key lifetime or account-agreement state from an HTTP 403 alone.',methods=['PRIMARY_ENGINEERING_SOURCE'])
add(43,[lines('hosting-overview',25),ref('keyowner','/comment/excerpt')],'The inspected authority supports obtaining the current installer but does not identify a retired endpoint in this specific failure.','4. **Stale installer.** If you are reusing a downloaded installer, return to the setup page and download its current version before retrying. Retain the failing URL and HTTP response from the log if the fresh installer still fails.',methods=PUB+['PRIMARY_ENGINEERING_SOURCE'])
add(44,[ref('installer','/excerpts/logs/text'),lines('hosting-overview',12,13)],'This is source/log-based triage advice separating local component failures from HTTP rejection; linked diagnostics retain their own execution status.',methods=DIAG)
add(45,[ref('installer','/excerpts/logs/text'),find('safe','CLM-c7a8ac27359a2b4b'),lines('follow',9,13)],'The public installer defines its log basename and retained reads establish the Vast service and kaalia self-test log locations. This instruction does not assert healthy service state.',methods=CAN+['RUNTIME_OR_UI_OBSERVATION'])
add(46,[find('safe','CLM-c7a8ac27359a2b4b'),lines('safeplan',52,58),tool(0),tool(3),tool(5)],'September2 retained the exact four-component installed-Host carrier with all components0, four services active, XFS project accounting/enforcementON and matched configured range.',methods=['CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION'],limit='Only the observed September2 Host snapshot; all four printed service states matter because systemctl zero alone means at least one active. No install journey, reboot persistence, WAN or quota enforcement-under-load proof.')
add(47,[lines('follow',3,13),m('tail')],'The exact path/sudo/follow command opened and emitted initial output, then was interrupted with no remaining child. The retained run had no active self-test.',methods=['PUBLISHED_VENDOR_DOCUMENTATION','RUNTIME_OR_UI_OBSERVATION'],limit='September2 bounded follow/interrupt mechanics only, not fresh self-test progress, completed diagnostics, rotated-log handling or parent-procedure qualification.')
add(48,[m('debconf'),m('dpkg')],'Noninteractive debconf and dpkg conffile options cover specific prompt classes, not all provider package-script prompts.','For SSH-only installs, the following `apt-get` commands use noninteractive debconf answers and predefined dpkg conffile choices. Review the upgrade output; package scripts can still fail or require attention:',methods=DIAG)
add(49,[m('dpkg')],'With both options, confdef takes precedence when a default exists; the old wording wrongly promises keeping every local configuration file.','For changed configuration files, `--force-confdef` takes the default dpkg action; `--force-confold` keeps the existing file when no default is available. Review important local configuration files after the upgrade.',methods=DIAG)
add(50,[find('safe','CLM-10bcbc68d0d8f1a2'),lines('safeplan',45,50)],'The exact driver-recommendation command executed with exit0 and one recommendation. Its deprecation and missing-audio-command stderr remains recorded.',methods=['RUNTIME_OR_UI_OBSERVATION'],limit='September2 query only; no driver install, recommended-version compatibility, clean stderr or current hardware inference.')
add(51,[find('safe','CLM-128d433cdb393ca9'),lines('safeplan',34,43),tool(5)],'The exact four-command carrier ran with required reads0; the optional data mount absence returned1 under authored ||true.',methods=['PUBLISHED_VENDOR_DOCUMENTATION','RUNTIME_OR_UI_OBSERVATION'],limit='September2 collection only; no disk identity/disposability or formatting/mounting success.')
add(52,AMD,'The published Vast example uses an unsupported AMD option: the pinned kernel parser has no on branch. Use firmware enablement and verify actual grouping rather than claiming this token enables IOMMU.','| AMD IOMMU | Enable virtualization and IOMMU in firmware, then verify IOMMU groups before [VM setup](/host/vms). Linux 6.8 does not define `amd_iommu=on` as an enabling option. |',methods=CAN+['PUBLISHED_VENDOR_DOCUMENTATION'])
add(53,[m('amd')],'The Intel option is explicitly supported; it is not the CPU substitution for an equally valid AMD on parameter.','| `intel_iommu=on` | Enables the Intel IOMMU driver on supported Intel platforms; firmware virtualization/IOMMU must also be configured. |',methods=DIAG)
add(54,[lines('vms',99,109)],'The original published VM setup explicitly selects NVIDIA modeset disablement as part of its configuration; no guarantee of universal VM compatibility follows.',methods=PUB)
add(55,[PORT],'The current public setup supplies the exact echo-n dash-range command and explicitly forbids a trailing newline.',methods=PUB)
add(56,[find('safe','CLM-6391e55bdef1e3cc'),lines('safeplan',60,67),tool(4),tool(5),tool(0)],'The retained final-state carrier supports each read; df/findmnt alone do not establish that the backing device is NVMe. Correct only that comment; all executed command bytes stay unchanged.',replacement=C[55]['claim']['text'].replace('# Check NVMe is mounted to /var/lib/docker','# Check Docker storage capacity, mount, and project quotas'),methods=['CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION'],limit='September2 read-only component observations only; not a fresh run, reboot chronology, exact disk technology, storage mutation, WAN or full headless installation proof.')
add(57,[lines('hosting-overview',25),lines('vms',17,23)],'VM support is an optional feature layered on normal host setup; this cross-reference preserves that published workflow.',methods=PUB)
add(58,[lines('vms',17,23),lines('vms',29,48)],'Original product documentation declares VM-template search visibility and workloads. This is a documented capability, not evidence a particular host is enabled.',methods=PUB)
add(59,[lines('vms',38,40)],'The original VM feature/use-case list explicitly includes these Systemd/Docker workflows.',methods=PUB)
add(60,[lines('vms',42,44)],'The original VM feature list explicitly names non-Linux guest OS and Windows use cases; it does not change the host OS requirement.',methods=PUB)
add(61,[lines('vms',46,48)],'The original VM feature list explicitly names ptrace and NVIDIA Nsight profiling.',methods=PUB)
add(62,[lines('vms',55,56)],'Original product guidance explains VM disk overhead relative to containers.',methods=PUB)
add(63,[lines('vms',56)],'Original product docs explicitly suggest higher disk/bandwidth pricing; the conditional advice is not a measured earnings claim.',methods=PUB)
add(64,[ref('vmhelper','/excerpts/1/text')],'This lead-in introduces the exact helper-output table; its meaning is resolved in that table and surrounding configuration-only caveat.',methods=CAN)
add(65,[ref('vmhelper','/excerpts/1/text'),lines('vms',75)],'The helper returns on for its enabled configuration marker; the following paragraph already limits this to configuration state, not idle or healthy VM workload.',methods=CAN)
add(66,[ref('vmhelper','/excerpts/1/text')],'pending occurs whenever the tried marker is absent, unreadable or not exactly y; that does not establish an attempt history or promise future scheduling.','| `pending` | The helper did not read a completed-attempt marker (`y`). The marker may be absent, unreadable, or contain a different value; this result alone does not establish when an enablement attempt will run. |',methods=CAN)
add(67,[lines('vms',89,99),m('ubuntu_iommu')],'Published VM and Ubuntu passthrough instructions require chipset/CPU IOMMU and firmware virtualization prerequisites.',methods=PUB)
add(68,[lines('vms',89,99),m('ubuntu_iommu')],'Firmware prerequisite instruction is explicitly supported; menu names vary by platform and are not claimed universal.',methods=PUB)
add(69,[lines('vms',99,111),*AMD],'The generic sentence must not imply every AMD platform needs a new enabling kernel token. Preserve existing parameters while applying the documented Intel/NVIDIA case.','Edit `/etc/default/grub` without removing existing boot options. For the Intel example below, add `intel_iommu=on` and the Vast VM setting `nvidia_drm.modeset=0`:',methods=PUB+CAN)
add(70,AMD,'The AMD substitution is contradicted by the pinned kernel parser. Replace it with the actual firmware/default-driver behavior and a concrete grouping check.','On AMD platforms, enable virtualization and IOMMU in firmware and verify IOMMU groups before retrying VM enablement. Supported AMD IOMMUs normally initialize without `amd_iommu=on`; Linux 6.8 does not implement that value. Follow the [Ubuntu IOMMU checks](https://ubuntu.com/server/docs/how-to/graphics/gpu-virtualization-with-qemu-kvm/) if groups are missing.',methods=PUB+CAN)
add(71,[lines('vms',106,109),m('ubuntu_iommu')],'In context this introduces the original product-documented Nouveau blacklist options for hosts needing them; it is conditional advice, not a universal fix.',methods=PUB)
add(72,[lines('vms',119,123),ref('vmhelper','/excerpts/2/text')],'The published command and installed parser define forced retry; surrounding maintenance/no-active-work gate is retained. No actual retry success asserted.',methods=PUB+CAN)
add(73,[lines('vmabort',51,74),ref('vmhelper','/excerpts/2/text')],'The retained disqualified-environment counterexample proves that this abort message coexisted with exit0; installed dispatch catches/prints errors without dependable nonzero status. The narrow safety claim does not qualify the VM operation.',methods=CAN+['RUNTIME_OR_UI_OBSERVATION'],limit='Counterexample use only: original VM environment was disqualified and all VM command acceptance statuses remain unchanged. This supports checking output/state, not an enablement PASS.')
add(74,[ref('vmhelper','/excerpts/1/text'),find('safe','CLM-c7a8ac27359a2b4b'),tool(0)],'The next block checks configuration output, GPU enumeration and basic services; this is an appropriate follow-up instruction and not a complete VM workload qualification.',methods=DIAG)
add(75,[ref('vmhelper','/excerpts/1/text')],'After a tried marker, all paths except readable nvidia_vm config return off, including read exceptions. The table lists possible interpretations and surrounding scope excludes health/idle.',methods=CAN)
add(76,[lines('machines',699,716),lines('machines',994,1015)],'The CLI checks selected-offer preflight data and starts diagnostic work; those checks are not equivalent to full platform verification readiness.','Self-test checks a listed machine against the CLI’s preflight requirements and attempts a temporary diagnostic rental. It does not by itself establish platform verification or readiness for every renter workload.',methods=CAN)
add(77,[lines('auth',199,220),lines('apikeyrun',13,30)],'The exact command writes the key successfully but the retained isolated run found unsafe mode0644; the pinned implementation still opens without explicit permission hardening. A successful write is not suitable passing credential-handling evidence.',status='FAIL',methods=['CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION'],next_action='Provide a secure key-storage path or verify a corrected CLI release; retain the existing isolated0644 failure and test a restrictive new-file/existing-file workflow before promoting this credential instruction.',topic='HOST-CLI-KEY-FILE-PERMISSIONS',limit='Actual failure was CLI1.5.6/macOSarm64/Python3.14.6/umask022 with a synthetic key; pinned1c6 source retains the same unsafe open pattern, but no new cross-platform execution occurred.')
add(78,[lines('machine_diag',153,165),lines('systemreq',29,45),ref('owner','/comment/paragraphs/2'),SET],'The “same gates/page wins” claim erases a real owner-versus-pinned-tester discrepancy and implies an unproven backend contract.','These are diagnostic preflight checks implemented by the CLI. Compare the [Self-Test Reference](/host/self-test-reference) with the published [verification requirements](/host/verification-stages#additional-requirements-for-verification); a difference needs source/version clarification and does not change the check your installed tester executes.',methods=CAN+['PRIMARY_ENGINEERING_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION'])
add(79,[lines('machines',1310,1333),lines('systemreq',14,45)],'HTTPS polling runs in the CLI, while resource checks run in the image; the list lead-in currently misplaces all checks inside the image.','The CLI and temporary self-test image perform checks that include:',methods=CAN)
add(80,[lines('machines',1310,1333)],'With the corrected lead-in, this is the CLI HTTPS progress probe, not an assertion that the image can reach itself or the endpoint succeeded.',methods=CAN)
add(81,[lines('systemreq',29,41)],'The implementation compares total system RAM, not currently available/free RAM.','- Total system RAM meeting the image’s minimum requirement.',methods=CAN)
add(82,[lines('systemreq',29,45)],'psutil.cpu_count(logical=False) distinguishes physical from logical threads for the image check; this does not resolve how offer.cpu_cores is populated.',methods=CAN)
add(83,[lines('follow',3,13),m('tail')],'The exact repeated log-follower command shares the retained September2 bounded execution; no active self-test ran then.',methods=['PUBLISHED_VENDOR_DOCUMENTATION','RUNTIME_OR_UI_OBSERVATION'],limit='Path/read/follow/interruption/cleanup only; no live progress or parent-procedure promotion.')
add(84,[lines('kernelfollow',3,29),m('journal'),m('grep')],'Exact kernel follower/pattern/line-buffer option matches retained execution and primary option definitions. A healthy/no-match run supports collection mechanics without inducing faults.',methods=['PUBLISHED_VENDOR_DOCUMENTATION','RUNTIME_OR_UI_OBSERVATION'],limit='September2 bounded follow/interrupt mechanics only; no matching fault/event, sustained under-load evidence or repair. Unrelated workload activity was retained as an environment limit.')
# Support ownership is a published obligation, not proof a host satisfies it.
# Retain the already-bound agreement authority rather than copying it.
x=C[84]['claim'];agreementrefs=x.get('evidence_refs',[])+x.get('source_refs',[])
for e in agreementrefs:
 p=e.get('path') or e.get('artifact_ref') or ''
 if p and (R/p).is_file() and 'agreement' in p:
  src('agreement',p,'AUTHORITATIVE_DOCUMENTATION_CITATION');break
add(85,[lines('hosting-overview',10,15),lines('hosting-overview',37),PORT,lines('ownerports',16,17)],'Original public overview assigns setup/troubleshooting and resource operation to the host; public Setup and Engineering require public inbound ports and exclude CGNAT/shared-IP configurations. This is support-scope/network guidance, not an observed host compliance result.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','PRIMARY_ENGINEERING_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION'],classification='SUPPORT_SCOPE_WITH_TECHNICAL_CONTEXT')
add(86,[pub('ping')],'The exact numeric-target ping sends four ICMP requests; numeric addressing bypasses DNS. The limitations correctly prevent overgeneralizing that signal.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(87,[pub('ping')],'Packet counts/loss are an illustrative interpretation of this ICMP probe; filtering/path failure cannot establish all-service failure. Network-owner escalation is advice, not a measured outage.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(88,[pub('nslookup')],'The tool definition supports the query/answer/error interpretation; examples are not fixed current DNS values or global-fault diagnoses.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(89,[pub('curl'),pub('ifconfig')],'The adjacent curl -4 ifconfig.me command selects IPv4 and default HTTP; the service reports this request egress and proves neither inbound routing nor HTTPS.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(90,[pub('curl'),pub('ifconfig')],'The statement treats an address/error as a request-specific observation and correctly leaves cause/topology to investigation. Proxy/VPN routing can change the service-observed egress.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
add(91,[pub('ping'),pub('nslookup'),pub('curl')],'This is a conservative decision rule for inconclusive different-scope network checks, not an execution claim or proof of general availability.',methods=DIAG,classification='REVIEWED_DIAGNOSTIC_RECIPE')
# Normalize all decisions to explicit integration inputs with exact source selection.
for d in D:
 if not d.get('proposed_classification'):d['proposed_classification']=by[d['id']]['claim']['classification']
 if d['proposed_classification']=='REVIEWED_BOUNDED_DIAGNOSTIC_COLLECTION':d['proposed_classification']='REVIEWED_DIAGNOSTIC_RECIPE'
 if not d.get('next_action'):d['next_action']='Apply the accepted literal correction and recheck the source/context binding; retain the stated evidence limits.' if d['decision']=='correction' else 'Retain the exact source/observation binding; recheck if the literal, dependency or intended outcome changes.'
 if 'proposed_methods' in d:
  d['proposed_methods']=['RUNTIME_OR_UI_OBSERVATION' if x=='RUNTIME_BEHAVIORAL_TEST' else x for x in d['proposed_methods']]
 else:d['proposed_methods']=by[d['id']]['claim']['required_evidence_types']
 if 'RUNTIME_OR_UI_OBSERVATION' in d['proposed_methods']:d['method_rationale']='Retained bounded execution/counterexample is combined with exact source definitions; this does not promote the parent workflow or claim a new target run.'
 if d.get('topic_key'):d['residual_topic']={'key':d['topic_key'],'title':{'HOST-ARM-SUPPORT-CONSISTENCY':'Confirm ARM support and architecture-specific requirements','HOST-AMD-SUPPORT-CONSISTENCY':'Confirm supported AMD host families','HOST-CLI-KEY-FILE-PERMISSIONS':'Correct CLI API-key file permissions'}[d['topic_key']]}
assert len(D)==91 and {d['id'] for d in D}==set(by)
seal('COMPLETE_PENDING_INDEPENDENT_ROOT_REVIEW')
# Three adjacent proposals, separate from the frozen91.
model=json.loads((R/'verification/current-host-docs-review.json').read_text())
def claims(v):
 if isinstance(v,dict):
  if 'id' in v and 'text' in v and 'spans' in v:yield v
  for x in v.values():yield from claims(x)
 elif isinstance(v,list):
  for x in v:yield from claims(x)
allc={x['id']:x for x in claims(model)}
EXP=[]
def expand(i,replace,refs,why):
 c=allc[i];EXP.append({'id':i,'literal_sha256':sha(c['text'].encode()),'before_status':c['status'],'before_literal':c['text'],'decision':'correction','proposed_status':'PASS','proposed_methods':CAN,'proposed_classification':'REVIEWED_TECHNICAL_DECLARATION','proposed_replacement':replace,'source_refs':refs,'support_rationale':why,'method_rationale':'Exact diagnostic implementation/source correction, not a platform policy decision or new runtime qualification.','limitation':'Preserve the dated owner1-core guidance/current Setup2-core discrepancy as unresolved platform-policy context; do not reinterpret offer.cpu_cores as a proven physical-core counter.' if 'CUR-' in i else 'No boot or VM passthrough execution; existing operation/procedure statuses remain unchanged.','next_action':'Apply this separately accepted adjacent correction together with its generator/context counterpart; verify exact source and procedure consequences.'})
for i in ['CUR-f992e392221fe492','CUR-1de91e8c48307d8b']:
 print('CPU BEFORE',i,allc[i]['text'])
# Preserve table schema and all non-CPU cells; exact complete replacements are set from the frozen literal below.
new='| `cpu.cores`<br />CPU cores | Required: `offer.cpu_cores` &gt;= 2 × `num_gpus` | The CLI checks the reported offer core count against twice the listed GPU count. This check does not establish how `offer.cpu_cores` was measured. | Check the reported core count and GPU count; add CPU capacity or reduce the listed GPU count if this preflight gate is unmet. |'
expand('CUR-f992e392221fe492',new,[lines('machine_diag',153,165),lines('machine_diag',266,278)],'Reference currently describes a1-physical-core check, but pinned CLI compares offer.cpu_cores against2*num_gpus. Correct the implemented check without asserting counter semantics.')
c=allc['CUR-1de91e8c48307d8b']['text'];new=c.replace('at least 1 visible physical CPU core per visible GPU. Hyperthreads/logical CPUs do not count as physical cores.','at least 2 physical CPU cores per visible GPU, counted with `psutil.cpu_count(logical=False)`. Hyperthreads/logical CPUs do not count as physical cores.')
new=new.replace('there is at least 2 physical CPU cores','there are at least 2 physical CPU cores').replace('Each GPU has at least 98% free VRAM;', 'For each visible GPU, PyTorch allocated plus reserved memory must be at most 2% of its reported VRAM;')
assert new!=c
expand('CUR-1de91e8c48307d8b',new,[lines('systemreq',6,45)],'Pinned image checks PyTorch allocated-plus-reserved memory, not independently measured global free GPU memory; it applies the capped total-RAM formula and physical cpu_count(logical=False) >=2*visibleGPUcount. Owner policy does not alter these source bytes.')
expand('MCL-7c8616c7ed600748','```text\n# Preserve other existing GRUB_CMDLINE_LINUX options.\n# AMD: enable IOMMU in firmware and verify IOMMU groups.\nGRUB_CMDLINE_LINUX="nvidia_drm.modeset=0"\n```',AMD,'The adjacent AMD example must not retain an unsupported amd_iommu=on after its explanation is corrected. Keep the documented NVIDIA VM setting and explicitly preserve existing boot options.')
dump(B/'sources/cpu-policy-discrepancy.json',{'record_type':'SOURCE_POLICY_DISCREPANCY_CONTEXT','dated_owner':ref('owner','/comment/paragraphs/2'),'current_setup':SET,'context':'Dated Engineering answer requires one physical core per GPU; current public Setup specifies two physical cores. Both pinned diagnostic implementations compare against two, with CLI offer counter semantics not established. Correcting diagnostic rows does not decide the platform-policy discrepancy. Existing eight owner questions and prior CPU FAIL history remain unchanged.'})
src('cpudiscrepancy',B/'sources/cpu-policy-discrepancy.json','SOURCE_DISCREPANCY_CONTEXT')
for e in EXP:
 if e['id'].startswith('CUR-'):e['source_refs'] += [ref('owner','/comment/paragraphs/2'),SET];e['residual_context_artifact']=str(B/'sources/cpu-policy-discrepancy.json')
seal('COMPLETE_PENDING_INDEPENDENT_ROOT_REVIEW')
dump(B/'adjacent-proposals.json',{'state':'PROPOSED_ADDITIVE_SCOPE_ROOT_ACCEPTANCE_REQUIRED','proposals':EXP})
print('SEALED91',len(D))
