import json,pathlib,hashlib,datetime,collections
A=pathlib.Path(__file__).resolve().parent;R=A.parents[3];P=A.parent
H=lambda b:hashlib.sha256(b).hexdigest()
read=lambda p:json.loads(p.read_text())
I=read(A/'claims.json');C={x['id']:x for x in I['claims']};S={};D={}
def src(key,path,url=None,kind='AUTHORITATIVE_DOCUMENTATION_CITATION',revision=None):
 p=R/path;S[key]={'path':path,'sha256':H(p.read_bytes()),'url':url,'revision':revision,'source_kind':kind};return key
def ref(key,ptr):
 p=R/S[key]['path'];v=None
 if ptr.startswith('/lines/'):
  a,b=map(int,ptr.split('/')[-1].split('-'));v='\n'.join(p.read_text().splitlines()[a-1:b])
 else:
  v=read(p)
  for k in ptr.strip('/').split('/'):v=v[int(k)]if isinstance(v,list)else v[k.replace('~1','/').replace('~0','~')]
 assert isinstance(v,str),(key,ptr,type(v));return {'source':key,'text_pointer':ptr,'source_excerpt':v}
for name in ['published-current','published-targeted']:
 for k,v in read(A/(name+'.json'))['sources'].items():
  if 'error'not in v:src(k,str((A/(name+'.json')).relative_to(R)),v['source_url'])
def pub(k,i=0):return ref(k,f'/sources/{k}/excerpts/{i}/text')
for k,f,url,kind,rev in [
 ('agreement','agreement-clauses.json','https://cloud.vast.ai/host/agreement','AUTHORITATIVE_DOCUMENTATION_CITATION',None),('cli','cli-excerpts.json','https://github.com/vast-ai/vast-cli/tree/1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc','CANONICAL_IMPLEMENTATION_SOURCE','1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc'),('setup','setup-browser-response.json','https://cloud.vast.ai/host/setup','AUTHORITATIVE_DOCUMENTATION_CITATION',None),('images','included-image-observations.json',None,'RUNTIME_OR_UI_OBSERVATION','Included screenshot capture date/version unknown'),('math','arithmetic-and-context.json',None,'REPOSITORY_STATIC_CHECK',None),('navigation','navigation-review.json',None,'REPOSITORY_STATIC_CHECK','61fbb472fadd1c9242a34fae14b67ddf0eb3f376'),('notification-api','notification-api-source.json','https://github.com/vast-ai/docs/blob/175a318/api-reference/openapi/yaml/notifications.yaml','CANONICAL_IMPLEMENTATION_SOURCE',None)]:src(k,str((A/f).relative_to(R)),url,kind,rev)
S['notification-api']['url']=read(A/'notification-api-source.json')['source_url'];S['notification-api']['revision']=read(A/'notification-api-source.json')['revision']
src('owner-1518',str((P/'owner-source-1518.json').relative_to(R)),'https://vastai.atlassian.net/browse/CON-1518?focusedCommentId=55846','ACCOUNTABLE_OWNER_CONFIRMATION')
src('owner-questions',str((A/'existing-owner-question-excerpts.json').relative_to(R)),None,'REPOSITORY_STATIC_CHECK','61fbb472fadd1c9242a34fae14b67ddf0eb3f376')
src('old-tail-result','verification/evidence/2026-09-02-host-safe-readonly-attempt-03/result.md',None,'RUNTIME_OR_UI_OBSERVATION','2026-09-02 historical Host observation')
src('tail-review','verification/evidence/2026-09-14-host-unvalidated-evidence-attempt-02/diagnostic-review.json',None,'RUNTIME_OR_UI_OBSERVATION','Retained independent raw/hash audit; no fresh execution')
src('old-cli-offer-fields','verification/evidence/2026-09-15-host-unvalidated-source-families-attempt-01/s4-s5/canonical-cli-excerpts.json','https://github.com/vast-ai/vast-cli/tree/1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc','CANONICAL_IMPLEMENTATION_SOURCE','1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc')
src('team-gap','verification/evidence/2026-09-15-host-evidence-reuse-source-review-attempt-01/sources-before/host/host-teams.mdx',None,'REPOSITORY_STATIC_CHECK','61fbb472fadd1c9242a34fae14b67ddf0eb3f376')
src('notification-original',str((A/'notification-original-provenance.json').relative_to(R)),'https://github.com/vast-ai/docs/blob/5f234480afc0bdea630f681939d11a23240cbaf5/host/notifications.mdx','AUTHORITATIVE_DOCUMENTATION_CITATION','5f234480afc0bdea630f681939d11a23240cbaf5')
def agr(k):return ref('agreement',f'/clauses/{k}/text')
def cli(i):
 k=f'cli-{i}';item=read(A/'cli-excerpts.json')['excerpts'][i]
 if k not in S:S[k]={**S['cli'],'url':item['url'],'repository_path':item['source_file'],'revision':item['revision']}
 return ref(k,f'/excerpts/{i}/text')
def img(i):return ref('images',f'/observations/{i}/observation')
def nav(f):
 d=read(A/'navigation-review.json')['targets'];i=next(i for i,x in enumerate(d)if x['path']==f);return ref('navigation',f'/targets/{i}/headings_and_anchors/0/text')
DOC=['AUTHORITATIVE_DOCUMENTATION_CITATION'];STATIC=['REPOSITORY_STATIC_CHECK'];CODE=['CANONICAL_IMPLEMENTATION_SOURCE'];ADVICE=['REPOSITORY_STATIC_CHECK','AUTHORITATIVE_DOCUMENTATION_CITATION'];BOTH=['CANONICAL_IMPLEMENTATION_SOURCE','AUTHORITATIVE_DOCUMENTATION_CITATION'];UI=['REPOSITORY_STATIC_CHECK','RUNTIME_OR_UI_OBSERVATION']
Q={x['id']:i for i,x in enumerate(read(R/'verification/current-host-owner-questions.json')['questions'])}
def q(k):
 d=read(R/'verification/current-host-owner-questions.json')['questions'][Q[k]]
 field='question'if 'question'in d else 'title';return ref('owner-questions',f'/questions/{Q[k]}/{field}')
def add(id,refs,why,methods=None,cls=None,replacement=None,residual=None,topic=None,question=None,lim=None,status='PASS'):
 assert id in C and id not in D,id;x=C[id];c=x['claim'];old=c['text'];assert H(old.encode())==x['literal_sha256']
 if residual:status='UNVALIDATED'
 methods=methods if methods is not None else c['required_evidence_types'];cls=cls or c['classification']
 d={'id':id,'literal_sha256':x['literal_sha256'],'location':c['spans'][0]if c['spans']else{'source_file':x['page']},'decision':'residual'if residual else('correction'if replacement is not None else'supported'),'proposed_status':status,'proposed_methods':methods,'proposed_classification':cls,'source_refs':refs,'support_rationale':why,'method_rationale':f"Full occurrence reviewed in {x['page']} context. Prior classification/methods: {c['classification']} / {', '.join(c['required_evidence_types'])}. " + (f"Use {cls} / {', '.join(methods)} for this exact " + ('proposed wording'if replacement else'passage') + '. ' if (cls!=c['classification']or methods!=c['required_evidence_types'])else'Existing evidence methods retained. ') + ('The sources define a published rule or interface; this does not assert a newly observed backend outcome.'if 'RUNTIME_OR_UI_OBSERVATION'not in methods else'Any UI/runtime support is limited to the explicitly identified retained observation; no new account or Host operation occurred.'),'limitation':lim or'No live Host, rental, payout or account action. Source review does not establish backend enforcement, general runtime success or human acceptance.','next_action':residual or('Apply the complete proposed replacement, preserve original wording/evidence in history, and recheck its exact source span.'if replacement else'Integrate this scoped source/evidence review without changing the literal or prior evidence.'),'existing_evidence_policy':'Retain all original evidence_refs, source_refs, history and any procedure result; no inherited procedure PASS.'}
 if replacement is not None:d.update(proposed_replacement=replacement,discrepancy=why,proposed_replacement_sha256=H(replacement.encode()))
 if topic:d['residual_topic']={'key':topic[0],'title':topic[1]}
 if question:d['existing_question_refs']=question
 D[id]=d
# Hosting duties: distinguish operational checklist from legal clause and implementation.
add('MCL-0da1b36690a3511a',[agr('uptime'),cli(0)],'The uptime clause supports the expressly qualified 24/7 duty; CLI listing guidance separately warns against interfering with rented machines. Together they support the complete operational checklist, not an exclusivity rule inferred solely from the agreement.',BOTH,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',question=['HQ-LOCAL-WORKLOADS'],lim='No idle/local workload exception or safe-offline threshold is resolved; HQ-LOCAL-WORKLOADS remains open.')
add('MCL-9bdafe9c81f6fb27',[agr('performance'),pub('hosting',1)],'The current published setup list expressly names Ubuntu, NVIDIA drivers, partitions/networking and Vast software; the fresh Agreement separately assigns hardware running/troubleshooting/maintenance. The technical half therefore has its own basis.',DOC,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-96a7de8300ee0824',[pub('hosting-details',0),agr('uptime'),cli(0)],'The public General concepts section asks hosts to plan continuous availability and near-max GPU use; the sentence is capacity-planning advice, not a workload forecast or uptime guarantee.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
for id in ['MCL-595d905880a176c1','MCL-cef28dd9319d10ea']:
 add(id,[pub('hosting-details',1),cli(4)],'Independent current published product guidance describes acceptance creating a rental contract with price, hardware specifications and end date. The linked CLI separately establishes the current-term/extension distinction. Both halves are source-reviewed as documented product semantics; no backend transaction is claimed.',BOTH,'REVIEWED_TECHNICAL_DECLARATION',question=['HQ-RENTAL-DATES','HQ-RENTAL-AVAILABILITY'],lim='Product-source semantics only. No deployed contract-creation, actual enforcement, immutable-date guarantee or safe-stop boundary is inferred; stronger adjacent published claims are not adopted and owner questions remain open.')
for id,why,refs in [
 ('MCL-8d3286528a924e12','CLI unlist removes offers; list help explicitly says existing jobs remain until owners end them. Price guidance supports the shared introductory distinction.',[cli(1),cli(0),cli(4)]),
 ('MCL-a4b087a3103c5bdb','Listing payload supplies updated offer prices; published offer guidance limits changes to future contracts, while CLI price guidance separately protects the current term and describes accepted later rates.',[cli(1),pub('hosting-details',4),cli(0),cli(4)]),
 ('MCL-421cebcd8ba352fa','The client exposes list/unlist and price fields, and its price-increase help expressly locates the cutover after current end_date. This is operational guidance using that declared interface.',[cli(1),cli(0),cli(4)]),
 ('MCL-8e9b3ede47cea846','The listing declarations separately define offer expiration and rolling duration; price-increase text distinguishes acceptance from cutover after the current term. No scheduled safe downtime is inferred.',[cli(0),cli(4)]),
 ('MCL-6451ffaa548e65a9','Published offer guidance says changed offers affect future contracts; the exact CLI guidance quoted in the second sentence supports its current-term and extension description.',[pub('hosting-details',4),cli(4)]),
 ('MCL-f1acb1113f75a3fe','The instruction to protect the current term follows the linked CLI cutover rule; it does not claim the reviewer changed or observed a price.',[cli(4)]),
 ('MCL-8f00a3466a2c728d','This is a prerequisite to understand the linked price-increase declaration, not an observed repricing workflow.',[cli(4)]),
 ('MCL-9aed4b65c749baae','Published offer-change guidance and the actual list-price payload support the new-offer half; CLI price-increase help supports the current-term and accepted extension half.',[pub('hosting-details',4),cli(1),cli(0),cli(4)])]:
 add(id,refs,why,BOTH,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',question=['HQ-RENTAL-DATES','HQ-RENTAL-AVAILABILITY'],lim='Scoped review of declared lifecycle guidance. No price-change API call, accepted extension, guaranteed auto-extension, universal safe-stop boundary or backend owner acceptance is established.')
add('MCL-ed68c47bda19e986',[agr('maintenance'),pub('volumes',1),ref('owner-1518','/comment/paragraphs/4'),nav('host/maintenance-windows.mdx'),nav('host/removing-recreating-machines.mdx')],'The fresh clause has the exact not-actively-using condition; the owner confirms stopped containers retain data and published volumes are separate storage. The conservative instruction to review all commitments and the two destinations are therefore supported.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',question=['HQ-RENTAL-AVAILABILITY','HQ-STORAGE-REMOVAL'])
# Prospective-host checklist.
add('MCL-09213387634b0ef5',[nav('host/supported-hardware.mdx')],'A good-fit checklist points to the actual Supported Hardware page. This literal does not enumerate or independently validate every hardware rule.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION')
add('MCL-4a8780e523ed0bec',[ref('setup','/excerpts/1/text')],'Fresh public Host Setup requires all GPUs to be the same model and more than 7 GB VRAM. The current qualitative checklist says same-type and enough VRAM; no numeric threshold is promoted.',DOC)
add('MCL-ee2c589aaa042885',[agr('technology'),pub('hosting-details',0),ref('setup','/excerpts/4/text')],'Stable power/cooling/storage/networking are capacity-planning inputs grounded in the provider-technology duty, public load/availability guidance and direct-network requirements.',ADVICE)
add('MCL-c19ad81f9d73b925',[ref('owner-1518','/comment/paragraphs/7'),ref('setup','/excerpts/5/text')],'Both owner guidance and current public setup prescribe Ubuntu, with no Windows/WSL host path. The row characterizes the documented supported path; it does not claim Windows CLI clients are unsupported.',DOC)
add('MCL-7a7ef86c0f7df05f',[ref('setup','/excerpts/4/text'),pub('hosting-prep',0)],'The existing row conflates the documented host TCP/UDP requirement with the protocols exercised by self-test. The public setup supports a continuous forwarded TCP and UDP range and public IPv4, without proving every self-test checks UDP.',DOC,replacement='| CGNAT, double NAT without public forwarding, blocked inbound ports, incompatible IPv6-only, or no public inbound path | The documented hosting network path requires public inbound connectivity and a continuous forwarded TCP and UDP port range. |',lim='No external port test, current router state or self-test protocol coverage was observed.')
add('MCL-ef7ae4abbb68b5f9',[pub('hosting',0)],'Current published account setup explicitly requires separate client and host accounts; this checklist asks for that supported account arrangement.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-ad105469d929fc63',[ref('setup','/excerpts/4/text')],'Fresh Host Setup explicitly asks for a continuous range for both TCP and UDP. The qualitative checklist does not adopt its conflicting numeric minimum.',DOC)
add('MCL-a4a99786611bde77',[pub('calculator',0),pub('pricing',3)],'Current calculator presents adjustable price and utilization; published pricing identifies marketplace demand and reliability. This asks the reader to account for variable inputs, not to expect a forecast.',ADVICE)
# Earnings components and illustrative math.
add('MCL-6cacfb94946d7298',[pub('calculator',0),pub('hosting-details',2)],'Fresh official calculator says the asking price is the basis for GPU earnings and customer-facing prices may reflect marketplace operations/support; listing documentation identifies host resource prices. This supports a possible host/client price difference without asserting a percentage fee.',DOC,lim='No specific fee amount, payout threshold, tax treatment or actual account calculation is established.')
add('MCL-41610a3ed826dd67',[ref('math','/gross_components')],'This is an introductory label for the immediately following component model. It has no independently testable fee or payout rule.',STATIC,'EDITORIAL_SCOPE_OR_LEAD_IN',status='NOT_APPLICABLE')
add('MCL-661048be8c8f4bb1',[pub('hosting-details',2),pub('hosting-details',3),ref('math','/gross_components')],'The modeled sum separates GPU compute, instance storage, bandwidth and separately priced volume offers. All are declared offer components; the surrounding page explicitly describes gross revenue before costs.',ADVICE,'REVIEWED_EXAMPLE_CALCULATION',lim='Arithmetic category model only; volume storage must not also be counted under instance storage. No net income, realized charges or guaranteed earning rate.')
add('MCL-5cef731065376169',[cli(0),pub('pricing',3),pub('calculator',0)],'The CLI declares per-GPU hourly prices for active instances, published pricing describes running-time compute billing, and the calculator binds GPU earnings to the asking price.',BOTH,'REVIEWED_TECHNICAL_DECLARATION')
add('MCL-41452a3e8a8e0f85',[pub('pricing',2),pub('pricing',3)],'Published instance pricing explicitly says storage billing continues while the instance exists, including stopped instances. The row is deliberately qualified by instance state.',DOC)
add('MCL-abe4f2c465aec7a6',[cli(0),pub('pricing',2)],'The CLI independently defines upload and download host price fields in dollars per GB; public pricing charges both directions by bytes. The full row describes those inputs, not a tested payout.',BOTH,'REVIEWED_TECHNICAL_DECLARATION')
add('MCL-6e3194b3f23bdd06',[pub('hosting-details',3),cli(0)],'Published volume offers can be priced separately and the CLI exposes vol_size/vol_price, including disabling them with size 0. This supports the conditional separate-volume component.',BOTH,'REVIEWED_TECHNICAL_DECLARATION')
add('MCL-059840711ca62764',[ref('math','/input_definition'),ref('math','/scenarios/1/interpretation')],'The existing definition can count utilization twice: GPUs already expected to be rented are multiplied by the separate occupancy input again. Define the capacity before utilization; the existing 4-GPU/55% example is dimensionally consistent with this correction.',STATIC,'REVIEWED_EXAMPLE_CALCULATION',replacement='| `rentable GPUs` | GPU capacity offered for rental during the modeled period, before applying utilization. |',lim='Fixed-capacity 30-day illustration; varying capacity needs separate periods or a time-weighted capacity. No earnings forecast or pricing policy.')
for id,i in [('MCL-8a295536feb086ec',0),('MCL-b4f3bff91bc1535b',1),('MCL-617eb3937852e105',2)]:
 add(id,[ref('math',f'/scenarios/{i}/interpretation'),ref('math','/input_definition')],'In the Compute-Only Monthly Model and 30-Day Range context, GPU capacity × dollars/GPU-hour × 720 hours × occupancy produces dollars. The price percentile changes the illustrative scenario input, not the algebra; the capacity definition is corrected separately.',STATIC,'REVIEWED_EXAMPLE_CALCULATION',lim='Scenario labels are illustrative planning cases, not statistical confidence bounds or guarantees. The median case is not a proven expectation of realized earnings.')
add('MCL-0e510a25842fd5d6',[ref('old-cli-offer-fields','/excerpts/0/text')],'This comparison checklist asks readers to compare verification state and host type; the offer schema exposes verified/datacenter fields. It promises no ranking or price effect.', ['REPOSITORY_STATIC_CHECK','CANONICAL_IMPLEMENTATION_SOURCE'],'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-526f6a348de7aaf2',[cli(0),pub('hosting-details',2)],'The comparison inputs correspond to actual minimum-GPU, bid, discount and expiration fields. The checklist does not prescribe a specific bid outcome or contract extension.',BOTH,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-18f04c2ae7ee95b4',[pub('calculator',0)],'The exact HTTPS destination returns the current official GPU Hosting Earnings Calculator page; this literal is just a navigation link.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION')
# Tax remains an accountable-owner gap, not a source-equality promotion.
add('CUR-99fb8d131e321e03',[pub('tax',0),q('HQ-VAST-TAX-HANDLING')],'Fresh published tax guide repeats the assertion, but this is the same policy-publication lineage being challenged. It does not provide independently approved scope, exceptions or Finance confirmation of actual Vast withholding practice.',residual='Ask Vast Finance/Tax to confirm current withholding practice and its jurisdiction/account exceptions in an approved source, or approve the pending tax-guide scope/removal decision.',topic=('tax-withholding','Tax withholding authority'),question=['HQ-VAST-TAX-HANDLING'])
add('MCL-0dc4f7d9c8e39ab3',[pub('teams',0),pub('teams-roles',3)],'Teams are documented as separate accounts with shared machines and roles. Recommending a team for shared hosting access avoids a shared personal login; it is account-design advice, not a claim of machine migration.',ADVICE,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
# Security recommendations are supported by feature inputs, not an account-security audit.
for id,why in [
 ('MCL-21977b596151a8c1','The host-owner bullet singles out accounts controlling valuable machines.'),('MCL-906c68dcab1918fd','The lead sentence recommends a second factor for accounts with privileged control.'),('MCL-94b16e51538e1193','The visibility bullet singles out sensitive earnings, invoices and payout history.'),('MCL-ae9eade8a82a6c8f','The team-owner/operator bullet singles out documented roles controlling machines.'),('MCL-ddf349fca94c6633','The API-key bullet singles out accounts capable of issuing or rotating secrets.')]:
 add(id,[pub('2fa',1),pub('permissions',3),pub('teams-roles',3),pub('keys',0)],why+' Public 2FA, permissions, roles and key documentation establish the factual capabilities in the shared lead-in. Enabling 2FA is proportionate security advice.',ADVICE,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS',lim='No new 2FA setup, sign-in, role enforcement, payout action or recovery workflow was tested.')
add('MCL-b5b8e74f4582df9b',[pub('api-keys',1),cli(2),cli(0)],'The existing sentence conflates CLI and SDK coverage for self-test. The pinned SDK self_test_machine raises NotImplementedError("self_test_machine requires CLI"); programmatic authentication remains supported by API-key docs.',BOTH,'REVIEWED_TECHNICAL_DECLARATION',replacement='Hosts use API keys for authenticated CLI and SDK automation. Use the CLI for machine self-test; the SDK’s `self_test_machine` method is not implemented. For listing, unlisting, pricing, maintenance, and diagnostic automation, check the supported command or SDK method in [CLI, API & SDK](/host/cli-api-sdk).')
add('MCL-4c92acd7bb5445f1',[pub('keys-rotation',2)],'Published API-key guidance expressly recommends reset for compromised keys. The instruction is secret-handling advice and does not claim a rotation was performed.',ADVICE)
add('MCL-ae43a91870f2d84d',[pub('api-keys',0),pub('permissions',0)],'Scoped keys and permission groups are documented; recommending only required privileges is consistent with those actual controls.',ADVICE)
add('MCL-f0af453a8c16714b',[pub('keys-rotation',1)],'Published key deletion/revocation controls support the recommendation to remove unused secrets. No blanket immediate-revocation runtime result is inferred.',ADVICE)
add('MCL-8d20618bf2a414e8',[pub('keys',0),nav('guides/reference/keys.mdx'),nav('cli/authentication.mdx')],'The Keys destination describes creation, reset and deletion, and the CLI authentication destination exists. This sentence routes users to these instructions rather than asserting completion.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION')
add('MCL-251ef7d712999857',[pub('teams',0),pub('teams-roles',3)],'Team accounts share machines/resources and roles; the recommendation applies those documented features to multi-operator or business access.',ADVICE)
# Pricing command and setup advice.
add('MCL-c7b9cabb79474701',[cli(0),pub('pricing',3)],'The CLI GPU price flag is dollars per GPU-hour; published pricing distinguishes GPU compute from additional storage and bandwidth. DPH is an hourly-price unit, not a guarantee of all-in cost.',BOTH,lim='The word usually does not establish that every dph field excludes storage; field-specific documentation remains authoritative.')
add('MCL-54acbeb016f26cd7',[cli(0),pub('hosting-details',2)],'CLI min_chunk defaults to 1 and published min_gpu controls slicing. Choosing that default unless larger slices are intentional is configuration advice, not a utilization guarantee.', ['REPOSITORY_STATIC_CHECK','CANONICAL_IMPLEMENTATION_SOURCE'],'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-82655ae2a41381c9',[cli(0),agr('maintenance')],'The documented offer-expiration field is a planning input; the instruction asks the operator to choose a date they can honor without promising that it ends existing rentals.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-e45c878667d4446d',[cli(0),cli(1)],'Every flag and the MM/DD/YYYY form in this complete placeholder command is accepted by the pinned listing parser, and the client maps values into the create-offer payload. This is an interface example; the machine placeholder is intentionally not executed.', ['REPOSITORY_STATIC_CHECK','CANONICAL_IMPLEMENTATION_SOURCE'],'REVIEWED_TECHNICAL_DECLARATION',lim='No offer creation, account authorization, prices on a live listing, rental or successful backend response is claimed. The arbitrary example rates are not recommendations.')
# Notifications: schema and existing UI pixels, with transparent host-specific residuals.
add('CUR-29c27133c7022850',[pub('notifications',0),ref('notification-api','/excerpts/0/text'),ref('notification-api','/excerpts/1/text'),img(0)],'Public guide and approved API schema expose the shared types/preferences/webhooks concepts; the included product screenshot shows the console preference controls. This establishes documented surfaces, not synchronized save or delivery.', ['AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION'])
add('CUR-c8657007c73f9603',[pub('notifications',1),ref('notification-original','/excerpts/0/text'),img(0),ref('setup','/links/1/href')],'The provider-only Host visibility condition is supported as documented product semantics by Guthrie’s original guide and the current publication. The remaining discrepancy is navigation: the text links /account/ and calls the section Notification Settings, while public console navigation links /settings/ and the included screenshot labels Notification and Webhook Settings. Keep the complete compound passage pending that exact route/label check.',residual='Confirm the current account navigation destination and section label, then keep or correct this compound passage. The provider-only visibility description is source-supported; no new visibility, preference-save or delivery experiment is required.',topic=('host-notification-navigation','Current notification navigation'))
add('CUR-602015da707f3ac9',[pub('notifications',1),ref('notification-api','/excerpts/0/text')],'The endpoint is the declared complete per-user type source; the static page list is not independently demonstrated complete for all host events. Calling it every/full overstates the page inventory.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION',replacement='For descriptions of the host events covered here, see [All Host Notifications](#all-host-notifications). For the current types available to your account, see [Notification Type Keys](#notification-type-keys).')
add('CUR-b66a8e30a355a76e',[pub('notifications',1),ref('setup','/links/1/href')],'The public guide directs users to Account Settings, but the public console navigation currently exposes a Settings route and the included screenshot has no account route. Exact click-path naming is not independently settled.',residual='Confirm the current account navigation label and destination in the host view, then keep or update this one step; no settings mutation is required.',topic=('host-notification-navigation','Current notification navigation'))
add('CUR-b227589501d07173',[pub('notifications',1),img(0)],'The included product screenshot spells the panel title Notification and Webhook Settings. Align this navigation step with the visible label; no save or delivery result is required.',UI,'REVIEWED_NAVIGATION_INSTRUCTION',replacement='2. Go to **Notification and Webhook Settings**.',lim='Included screenshot date/version is unknown; current public guide uses the shorter Notification Settings label. This is a visible-title alignment, not a newly observed host-account view.')
add('CUR-521bfba4cdc61495',[pub('notifications',1),ref('notification-original','/excerpts/1/text')],'The exact Host-section instruction was authored in the original product guide before the local rewrite and remains published. It supports documented navigation within the host view, without asserting that a new account view was opened.',DOC,'REVIEWED_NAVIGATION_INSTRUCTION',lim='Original product navigation definition, not a new authenticated Host rendering. The separate Account Settings route/label mismatch remains open.')
add('CUR-e1e9f923cef59dd7',[img(0),pub('notifications',5)],'Included UI pixels show removable Email chips for optional events, and current public guide distinguishes optional email from mandatory messages. This is control guidance, not proof that a preference persisted.',UI,'REVIEWED_NAVIGATION_INSTRUCTION',lim='Screenshot shows optional Instance controls, not Host-specific availability. General optional-email control is supported; Host view remains a separate recorded gap.')
add('CUR-3a0e78b8622470dd',[img(0)],'The included product screenshot visibly contains Save. This exact step directs the reader to a control and does not promise persistence or delivery.',UI,'REVIEWED_NAVIGATION_INSTRUCTION',lim='Historical included screenshot with unknown capture date/version; Save presence only, not an executed click or persisted setting.')
for id in ['CUR-826bdfbfe197daf9','CUR-c5fd881d81cd799c','CUR-9e64f834e78595cb']:
 add(id,[pub('notifications',2),cli(0)],'In context this is an example action mapping to the host Machines page, not a promise that the application auto-routes the event. Public host guide gives the same example and CLI listing help independently names the destination.', ['REPOSITORY_STATIC_CHECK','AUTHORITATIVE_DOCUMENTATION_CITATION'],'REVIEWED_NAVIGATION_INSTRUCTION')
add('CUR-120533314ba45001',[pub('notifications',3),ref('notification-api','/excerpts/3/text'),ref('notification-api','/excerpts/4/text')],'The schema defines a full key with client/host context and its subscription example uses host:machine_offline. This is an exact identifier definition.',CODE)
add('CUR-72ef524cc858dd75',[pub('notifications',3),ref('notification-api','/excerpts/0/text'),ref('notification-api','/excerpts/3/text')],'The schema documents the authenticated notification-types endpoint and subscription full-key example; public reference explains context disambiguation. No subscription or endpoint execution is asserted.',BOTH)
add('CUR-6789df60650d4c71',[pub('notifications',6)],'Periodic review after configuration changes is qualified operational advice, supported by the existence of per-type preferences. No alert coverage or delivery guarantee is made.',ADVICE)
add('CUR-de0d79517b8ab841',[pub('notifications',4),ref('notification-original','/excerpts/2/text')],'The exact maintenance-event meaning appears in Guthrie’s original August 3 product notification directory, predating our host-doc rewrite, and remains in the current official publication. This is a source review of the declared event meaning, not an assertion that this review scheduled maintenance or delivered an email.',DOC,'REVIEWED_TECHNICAL_DECLARATION',lim='No notification was sent or received. Queuing/delivery implementation, recipient list and safe maintenance boundaries are not tested or accepted; HQ-RENTAL-AVAILABILITY remains open.',question=['HQ-RENTAL-AVAILABILITY'])
add('CUR-c012fa4f30d14ef2',[ref('notification-api','/excerpts/4/text'),img(0)],'The API type defaults/preferences represent email and webhook channel booleans; the console shows per-event email controls. The general one-or-more-channel description is an interface definition.',CODE)
add('CUR-24a2b7d7779c61d3',[pub('notifications',1),img(0)],'This channel table describes the purpose of Email and the UI labels it on events. It does not claim any particular message was sent or received.',ADVICE,'REVIEWED_TECHNICAL_DECLARATION')
add('CUR-6d0f565f20158470',[pub('notifications',5),ref('notification-api','/excerpts/4/text'),img(0)],'The published guide states mandatory-email exceptions, the schema has mandatory_email, and included UI shows some fixed Email chips alongside optional Email× chips. This supports the documented control restriction, not backend delivery.', ['AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION'])
add('CUR-490d53ce09ad83a6',[ref('notification-api','/excerpts/2/text'),ref('notification-api','/excerpts/4/text'),img(0)],'The actual preference schema nests email/webhooks under context and event, and the screenshot shows per-event settings. This exact data-shape statement does not require saving preferences.',CODE)
# Teams.
add('MCL-8c5cf0caa45a320c',[pub('teams',0),pub('api-keys',1)],'Under Check the account context, this bullet tells operators to confirm account context before making an automation key. Shared team resources and account keys supply the factual basis; it does not guarantee daemon registration rights.',ADVICE,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS',lim='The separate team-daemon registration authorization gap remains unresolved.')
add('MCL-c6d458ebbf10b4f6',[pub('teams',0),pub('permissions',1)],'In its account-context checklist this recommends checking the target account before potentially consequential machine operations. It does not establish registration, migration or deletion behavior.',ADVICE)
add('MCL-25ed3ff8b10db289',[pub('teams-quickstart',1)],'This introduces the following invite instructions; it contains no independent permission or backend outcome claim.',STATIC,'EDITORIAL_SCOPE_OR_LEAD_IN',status='NOT_APPLICABLE')
add('MCL-ec0258710264c66e',[ref('setup','/links/0/href'),pub('teams-quickstart',0)],'Fresh public console navigation exposes the exact Members URL, and current official Team Creation identifies Members as the management entry point. This verifies navigation, not successful invitation.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION')
add('MCL-a313bdc48d3cfd1d',[pub('teams',0),ref('team-gap','/lines/113-128')],'The public team documentation establishes separate accounts/resources. It does not prove the machine-registration ownership binding or the unspecified supported migration/re-registration flow.',residual='Obtain the machine registration account-binding implementation and an approved supported ownership-transfer/re-registration path, or correct this exact sentence to a documented context check without claiming a migration flow.',topic=('team-registration-authority','Team machine registration and ownership authority'))
add('MCL-095c216ebc2d9949',[pub('teams-roles',0),pub('permissions',1),img(3)],'Official permission descriptions and included role editor expose Machines Read/Write; the row recommends only additionally needed billing/team access. This is least-privilege advice, not sufficient rights for every daemon or registration action.',ADVICE)
add('MCL-68656ca5b481d313',[pub('permissions',0),pub('permissions',1),ref('team-gap','/lines/113-128')],'The known scope descriptions cover machine reading, listing/unlisting and maintenance, but the full occurrence adds registration, cleanup and daemon workflows. The adjacent page explicitly retains engineering confirmation for registration rights.',residual='Engineering must map each listed registration/daemon/cleanup operation to its actual key scopes, including machine registration rights beyond machine_read/write. Preserve the supported machine-management scope descriptions separately.',topic=('team-registration-authority','Team machine registration and ownership authority'))
add('MCL-4770382f022bdf39',[cli(3),pub('permissions',2),pub('teams-roles',3)],'Pinned command declarations expose show/invite/remove member, including role on invitation. Published team_read/team_write and owner permissions independently support the permission precondition.',BOTH)
add('MCL-7c7161f01748ef19',[img(1),pub('teams',0),agr('current-account')],'The included UI labels an urgent hosted-machine escalation contact; team accounts have separate settings and the Agreement requires current account info. Choosing the intended team and monitored on-call contact is advice, not a delivery guarantee.', ['REPOSITORY_STATIC_CHECK','AUTHORITATIVE_DOCUMENTATION_CITATION','RUNTIME_OR_UI_OBSERVATION'],'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-d9e4edf75220e0e2',[pub('hosting',0)],'Current published hosting setup explicitly separates host and client accounts. This bullet restates that supported account arrangement as advice.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-58e680bc26e5aa28',[pub('teams-roles',0),pub('permissions',1),img(3)],'These documented scopes and visible role-editor controls cover routine host machine operations. The role recommendation does not resolve the separate machine-registration/daemon scope question.',ADVICE)
add('MCL-96df2a40c896e287',[img(3),pub('2fa',1),pub('teams-roles',3)],'The included role dialog has global and per-permission 2FA controls for the named privileged categories. Requiring a second factor is a security recommendation, not a report of tested enforcement.', ['REPOSITORY_STATIC_CHECK','AUTHORITATIVE_DOCUMENTATION_CITATION','RUNTIME_OR_UI_OBSERVATION'])
add('MCL-7d6e7cb6bc2b668f',[pub('permissions',3),pub('earning',0)],'Published billing_read covers invoices/earnings and Earnings documents payout history. Limiting visibility to need-to-know roles is advice using those existing sensitive surfaces.',ADVICE)
add('MCL-dd84d312d6a6be96',[pub('teams-roles',3)],'Published Owner role has full resources/settings/member access. Restricting that role to an accountable principal is proportionate operational advice.',ADVICE)
add('MCL-e390eca6346a4612',[pub('teams-roles',3)],'The Owner/Manager distinction explicitly singles out team deletion; treating ownership/deletion as consequential business actions is advice, not a claim about a tested transfer.',ADVICE)
add('MCL-e932877c037fbfce',[img(2),ref('setup','/links/1/href')],'Included product screenshot shows Invoice Information and fresh public console navigation exposes the exact Settings URL. Together they support the route/feature mapping without editing or generating an invoice.',UI,'REVIEWED_NAVIGATION_INSTRUCTION')
# Datacenter conflict itself is verifiable; the policy resolution remains open.
add('MCL-1998fd97e70ac6c0',[pub('compliance',0),pub('security-2024',0),q('HQ-DATACENTER-CERTIFICATION')],'Fresh primary pages exhibit the exact conflict: current Compliance encourages but does not strictly require ISO/SOC; the dated security article states ISO minimum. The passage asks the owner to resolve it and does not claim the policy is settled.',DOC,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',question=['HQ-DATACENTER-CERTIFICATION'],lim='PASS is for accurate conflict reporting/escalation, not a certification eligibility ruling. Existing owner question stays open; owner confirmation is not needed merely to establish that the publications differ.')
# Payout preparation advice and product surface description.
add('MCL-ddb9ec73ee76751e',[pub('earning',1),nav('host/earning.mdx')],'This is a pre-selection checklist asking the operator to verify provider availability, account verification and suitability; it states no universal provider eligibility, fee or payout promise.',STATIC,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS',lim='Check actual provider/account requirements before choosing. No provider qualification or payout was performed.')
add('MCL-7b0fcb03188a5ffc',[pub('earning',1)],'The instruction asks for an active eligible receiving account and to inspect any holds. It asserts no specific provider policy or successful receipt.',STATIC,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-2d21bffd45660447',[pub('earning',0),pub('earning',2),pub('referral',1)],'The current official Earnings page independently distinguishes machine rental, referral and template earnings and links the referral program. This supports the high-level product description.', ['PRODUCT_PUBLICATION_SOURCE'])
add('MCL-32d00e380e928e12',[pub('calculator',0),pub('pricing',3),nav('host/earning.mdx'),nav('host/market-metrics.mdx'),nav('host/pricing-your-listing.mdx')],'The full passage offers variable earning inputs and links the actual relevant planning pages and official calculator. Public pricing identifies hardware, reliability and location; no predicted income is asserted.',ADVICE)
# Workload responsibilities and diagnosis routing.
add('MCL-21c026cd0206a1c8',[agr('privacy'),agr('safeguards'),pub('compliance',2)],'Fresh Agreement establishes privacy/safeguards, and Compliance describes tenant isolation. This is an operational instruction and explicitly says those clauses are not a substitute for configuring/checking isolation.',DOC,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',lim='No proof of actual tenant isolation, secure wiping or current machine configuration; HQ-STORAGE-REMOVAL remains open.')
add('MCL-946580941143d9c9',[agr('current-account'),img(1),ref('setup','/links/1/href')],'Fresh clause requires current account information; included UI specifically calls the fields escalation contact for urgent hosted-machine issues; fresh console navigation supplies Settings URL. The recommendation does not guarantee anyone receives or answers an escalation.', ['REPOSITORY_STATIC_CHECK','AUTHORITATIVE_DOCUMENTATION_CITATION','RUNTIME_OR_UI_OBSERVATION'],'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-acaef10115bb9592',[agr('uptime'),cli(0),agr('performance')],'The qualified legal availability duty is exact; maintenance/performance responsibility and CLI warnings support keeping the machine stable/performance-capable. The sentence is an obligation/checklist, not measured uptime.',BOTH,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-95331d12bb886909',[nav('cli/reference/reports.mdx'),pub('permissions',0)],'The precise Reports reference exists and documented machine_read includes reports. This navigation advice claims neither a current renter report nor a command result.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION')
x=read(R/S['tail-review']['path'])['claim_reviews'];ix=next(i for i,v in enumerate(x)if v['claim_id']=='MCL-5b8305045e67acdd')
add('MCL-8f779eb0bf4589a4',[ref('old-tail-result','/lines/21-36'),ref('tail-review',f'/claim_reviews/{ix}/command_audit/0/exact_command'),ref('tail-review',f'/claim_reviews/{ix}/command_audit/0/observed')],'The exact sudo tail -n 100 path has a retained Sep 2 execution (100 lines, exit 0) and independently audited raw/hash binding. The inline form is the same command as the previously reviewed fence, with no extra shell operation.', ['RUNTIME_OR_UI_OBSERVATION'],'REVIEWED_DIAGNOSTIC_RECIPE',lim='Reuses the historical Sep 2 Host observation and existing independent raw audit. No fresh Host run, daemon version, diagnosis, renter-data inspection or universal path availability is inferred.')
add('MCL-57589fd3e157cb1e',[pub('bittensor',0),pub('terms',0)],'Bittensor primary docs establish a token network that produces inference/compute, but this does not independently establish every training/proof-of-work category in the broad sentence. Narrow to the evidenced concrete distinction while preserving the policy warning.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',replacement='A blockchain-related label does not identify the workload by itself. For example, [Bittensor’s documentation](https://www.bittensor.com/docs) describes a token network whose subnets can provide compute and inference. Check the actual activity against Vast’s Terms; this example does not establish that a particular workload is allowed.',lim='No endorsement of Bittensor, classification of a renter workload or permission to mine; Terms/payment conditions and owner decisions remain authoritative.')
add('MCL-bdb61764c1323438',[pub('terms',0)],'The current Terms contain a payment-method-specific mining rule. Routing a specific policy question to governing Terms/support avoids inventing a blanket permission or prohibition.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-03c73e4182b1e7fe',[cli(0),agr('privacy')],'In context, an idle-looking rental may still be active. CLI warns not to interfere with rented machines and the Agreement bars inspecting user data; leaving it running is conservative operational advice, not a newly discovered universal policy or expiry rule.',ADVICE,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',question=['HQ-LOCAL-WORKLOADS','HQ-RENTAL-AVAILABILITY'])
add('MCL-3f04de251cb1812e',[nav('host/maintenance-windows.mdx'),cli(0),agr('maintenance')],'The instruction routes maintenance planning to the maintained page and the actual offer-expiration setting. It does not say offer expiry terminates rentals or proves downtime safe.', ['REPOSITORY_STATIC_CHECK','CANONICAL_IMPLEMENTATION_SOURCE','AUTHORITATIVE_DOCUMENTATION_CITATION'],'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-907bf683229f42ae',[nav('host/removing-recreating-machines.mdx')],'The destination begins by requiring review of active commitments/stored workloads and inspection before normal cleanup. The row directs users to that guarded flow; it does not authorize deletion of tenant data.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION',lim='No stale-storage diagnosis or cleanup was performed. The destination is navigation context, not independent proof that deleting storage is safe.')
add('CUR-2b941108a664d7e6',[agr('privacy')],'The exact fresh clause prohibits downloading, storing, reviewing, printing and saving Authorized User data. Do not copy/share private data is a conservative application of that privacy rule, without adding an inspection exception.',DOC,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('CUR-9a254ad0dbc63699',[agr('cooperate'),ref('old-tail-result','/lines/21-36'),nav('host/common-errors-diagnostics.mdx')],'The fresh security clause requires cooperation and prompt notification; the named host-log collection has retained observation and the diagnostic destination exists. The sentence recommends evidence collection/escalation and promises no support outcome.', ['REPOSITORY_STATIC_CHECK','AUTHORITATIVE_DOCUMENTATION_CITATION','RUNTIME_OR_UI_OBSERVATION'],'REVIEWED_ADVICE_WITH_GOVERNING_RULE',lim='Host-side diagnostic evidence only; no private renter files/output, no security case reproduction, no new escalation or response-time guarantee.')
# Agreement summary: legal clauses and public/CLI operational guidance have separate bases.
add('MCL-015fcb36fdd0e6f7',[agr('privacy'),agr('safeguards'),pub('compliance',2)],'The full checklist combines a direction to protect/isolate client data with accurate references to privacy/safeguard duties. Current Compliance separately states client isolation; this is duty guidance, not proof of machine configuration.',DOC,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
add('MCL-3b697c60823b74fb',[cli(0),agr('interfere')],'The linked CLI explicitly warns against interfering after rental; the Agreement independently prohibits disruption. The operational dedication/avoid competing work checklist has both sources, without claiming an owner-approved idle exception.',BOTH,'REVIEWED_ADVICE_WITH_GOVERNING_RULE',question=['HQ-LOCAL-WORKLOADS'])
add('MCL-fea1fab97cdb288b',[agr('hardware'),agr('performance'),pub('hosting-details',1)],'Hardware provision and operation duties are in fresh Agreement; the published Overview separately describes advertised specs. Together they support this operational provider checklist without proving contract enforcement.',DOC,'REVIEWED_ADVICE_WITH_GOVERNING_RULE')
# Community assistance should not promise results.
add('MCL-f90ada45bf0249ab',[nav('host/common-errors-diagnostics.mdx')],'A useful initial report can provide context but cannot guarantee faster or better replies. Replace the response promise with a direct request for relevant information; preserve the following list.',STATIC,'REVIEWED_ADVICE_WITH_FACTUAL_INPUTS',replacement='To help others understand the issue, include:')
add('MCL-051a699007f6dde8',[nav('host/how-to-self-test.mdx'),nav('host/common-errors-diagnostics.mdx')],'The collect-logs destination and diagnostic page exist; in community context the preceding guidance already excludes API keys, personal information and client data. This is a recommendation for relevant sanitized evidence, not a claim that a bundle always exists.',STATIC,'REVIEWED_NAVIGATION_INSTRUCTION')
assert set(D)==set(C),{'missing':sorted(set(C)-set(D)),'extra':sorted(set(D)-set(C))}
# Seal proof index and per-ID decisions. Keep all input records available in claims.json.
index={'record_type':'LANE_A_EXACT_RETAINED_SOURCE_INDEX','sources':S,'limits':'Current official publication, immutable client source, existing included UI pixels and historical execution remain distinct evidence roles. No new live resource/account actions.'}
(A/'sources.json').write_text(json.dumps(index,indent=2,ensure_ascii=False)+'\n')
ordered=[D[x['id']]for x in I['claims']]
out={'record_type':'LANE_A_FULL_LITERAL_REVIEW','state':'COMPLETE_PENDING_ROOT_REVIEW','reviewed_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline_commit':'61fbb472fadd1c9242a34fae14b67ddf0eb3f376','baseline_model_sha256':I['baseline_model_sha256'],'source_index':'sources.json','source_index_sha256':H((A/'sources.json').read_bytes()),'reviewed_count':len(ordered),'total_frozen_count':110,'decision_counts':dict(collections.Counter(d['decision']for d in ordered)),'proposed_status_counts':dict(collections.Counter(d['proposed_status']for d in ordered)),'decisions':ordered,'global_limits':['No docs/model/projection/owner registry changes made.','No paid runs, account mutations, Host SSH changes or external messages.','Original evidence and failures must remain attached; passage decisions do not promote a procedure.','Fresh public Setup contains adjacent contradictory numeric/platform requirements; only scoped same-model/Ubuntu/network guidance was used.','Included screenshots have unknown capture date/version. No inference of save persistence, Host visibility or alert delivery.']}
(A/'decisions.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
print(json.dumps({k:out[k]for k in ['reviewed_count','decision_counts','proposed_status_counts']}));print('decisions_sha256',H((A/'decisions.json').read_bytes()))
