"""Explicit 78-occurrence source review. Writes only this evidence directory."""
import hashlib,json,pathlib
from build_decisions import O,ROOT,rows,current,proof

def p(file,index=0):
 j=json.loads((O/(file+'.json')).read_text());assert j['excerpts'][index]['found']
 r=proof(file+'.json',f'/excerpts/{index}/text');r['source_revision']=j.get('source_revision')or j.get('title');r['source_response_sha256']=j.get('source_response_sha256');return r
P={
'apt22':p('apt-jammy-v2',1),'apt24':p('apt-noble-v2',1),'update':p('apt-noble-v2',0),'install':p('apt-noble-v2',2),'apt-status':p('apt-noble-v2',3),'autoremove':p('apt-noble-v2',4),
'only-upgrade':p('apt-get',0),'new-pkgs':p('apt-get',1),'policy':p('apt-cache-v2',0),'cache':p('apt-cache-v2',1),
'dpkg':p('dpkg-query-v2',0),'format':p('dpkg-query-v2',1),'ii':p('dpkg-query-v2',2),'sort':p('gnu-coreutils',0),'uname':p('uname',0),'shell':p('bash',0),'and':p('bash',2),'or':p('bash',3),'split':p('bash-splitting',0),'variables':p('bash-variables',1),
'hwe22':p('ubuntu-kernels',0),'hwe24':p('ubuntu-kernels',1),'hwe':p('ubuntu-kernels',4),'hwe-package':p('hwe-package',0),'edge-package':p('hwe-edge-package',0),
'grub22':p('grub-jammy-source',0),'grub24':p('grub-noble-source',0),'grub-default':p('grub-config-v2',0),'grub-saved':p('grub-config-v2',1),'grub-menu':p('grub-menu-v3',0),'grub-keys':p('grub-config-v2',3),'update-grub':p('update-grub',0),'grub-image':p('grub-linux-source',1),'grub-initrd':p('grub-linux-source',2),
'ssh22':p('sshd-jammy-v2',0),'ssh24':p('sshd-noble-v2',0),'ssh-test':p('sshd-noble-v2',1),'ssh-config':p('sshd-noble-v2',3),'include22':p('sshd-config-jammy',1),'include24':p('sshd-config-noble',1),'first':p('sshd-config-noble',0),'password':p('sshd-config-noble',2),'interactive':p('sshd-config-noble',3),'strict':p('sshd-config-noble',4),'match':p('sshd-config-noble',5),
'keycopy':p('ssh-copy-id',0),'keycopy-output':p('ssh-copy-source',0),'publickey':p('ssh-config',0),'cp22':p('cp-jammy',0),'cp24':p('cp-noble',0),'sed-case':p('gnu-sed-v3',0),'sed-backref':p('gnu-sed-v3',2),'nvidia':p('nvidia-smi',0),'policy-output':p('apt-policy-source-v4',0),'policy-table':p('apt-policy-source-v4',2),'skip-output':p('apt-install-source',0),'keyfiles':p('openssh-files',0),'keyperms':p('openssh-files',1),
}
# Each tuple is an individual whole-literal assessment, not a keyword status rule.
S4=[
('CUR-d963fc54f393ad3f',['apt22','apt24','hwe22','hwe24','grub22','grub24'],'Both supported Ubuntu releases expose these package and bootloader command interfaces. This scope statement does not promise identical package versions, hardware support or successful maintenance.'),
('CUR-7268bf180bdbfe17',['apt24','dpkg'],'The full apt upgrade path is not filtered to linux-generic package names; the kernel-only query explicitly is. Installed non-generic package names are examples, not a promise of availability or driver compatibility.'),
('CUR-07797f3c49f3beb9',['new-pkgs'],'This is a kept-back output example for the described dependency case; apt-get upgrade without with-new-pkgs does not install new dependencies. It is not an observed machine result, universal package list or current update count.'),
('CUR-3dfcbbd8b592bc98',['uname','sort','sed-backref'],'The pipeline displays the running release and highest version-sorted filename in the matched /boot set. Its definition is supportable; equality is not a complete boot, patch, GPU or service-health test.'),
('CUR-b06d4fb8eb052e3d',['dpkg','format','ii'],'The query only selects linux-generic* records with status ii; it does not discover every kernel family or every installed/held status. Narrow the lead-in to that exact query.', 'Find the installed `linux-generic*` metapackages selected by this query. Save\nthe names to a variable for the later commands; other kernel families and\npackages with a different dpkg selection state need separate review:'),
('CUR-dc15f757356d0e8e',['dpkg','format','ii','sort'],'The quoted package pattern and format are declared by dpkg-query. The awk predicate selects only ii records, then names are version-sorted and stored. No result on a real Host is inferred.'),
('CUR-f0dc315073c4db7e',['dpkg','hwe22'],'A single matching metapackage name is a valid illustrative query result. The example does not establish which kernel a machine is actually running.'),
('CUR-9b96f1395c404b8a',['dpkg','hwe22'],'The official Jammy HWE guidance names this metapackage. This is an illustrative matched name, not evidence of installed or booted HWE on a Host.'),
('CUR-54b525bbf018345d',['dpkg','ii','shell'],'The pipeline hides dpkg stderr and matches only ii, so empty output does not prove no installed generic package exists. Remove the paste-as-written and absence guarantees.', 'If `echo` printed nothing, stop and inspect the package query before continuing.\nThe later commands need a non-empty list of reviewed metapackage names. An empty\nresult can mean no matching `ii` records were returned or the query failed.'),
('CUR-7fa13addd6aee7b1',['dpkg','only-upgrade','install'],'Multiple names are valid, but apt can retain packages due to state or dependencies. Requesting all names does not guarantee every package changes.', 'More than one line is a valid result. The later install command requests an\nupgrade for each returned name; review APT’s proposed changes before accepting:'),
('CUR-5303a0ee01742a47',['dpkg','hwe-package','edge-package'],'Both named metapackages exist and the query permits multiple matches. Their joint presence here is illustrative, not proof of separate kernel payloads.'),
('CUR-e0f6859af3fcef01',['hwe-package','edge-package','grub-menu'],'The retained package pages show HWE and edge dependency versions can coincide; distinct names do not establish distinct installed kernel payloads. The original independent-stack and old-boot outcome assertions are not justified.', 'Different metapackage names do not by themselves establish separate kernel\nstacks. Check each package’s image and header dependencies, and review the\nactual package changes and boot entries.'),
('CUR-1d8527ed28f606bb',['variables','split'],'The assignment is a shell variable, with no export or persistence step. Recreate it after reconnecting rather than assuming a new shell inherited it.'),
('CUR-6f8ae343d412611d',['hwe22','hwe24','hwe'],'Ubuntu documents GA and HWE and also an OEM track. The statement only two stacks and the most-machines distribution claim are too broad.', 'Ubuntu provides a general availability (GA) kernel and hardware enablement\n(HWE) kernels for LTS releases. HWE provides newer kernel support for newer\nhardware. Ubuntu Server 22.04 and 24.04 default to GA and offer HWE as an option;\nother kernel variants also exist, so inspect the packages on your machine.'),
('CUR-3efa5d455e840d88',['only-upgrade','skip-output'],'Only-upgrade does not install an uninstalled requested package. This is an illustrative skipped-name summary; its 24 count is not current system state or independent successful-run evidence.'),
('CUR-90417e4b2b1f95a0',['update','cache'],'Refreshing configured repository metadata before comparing candidates is appropriate advice; a successful refresh and actual repository configuration still matter.'),
('CUR-f764b55aaa08bd3e',['update'],'apt update refreshes package metadata from configured sources. It is not itself package installation or proof the repositories were reachable.'),
('CUR-179635ff378fa441',['policy','cache'],'This introduces the package policy comparison of installed state and configured candidate selection; it promises no universally newest upstream kernel.'),
('CUR-f21b9b6c7cfdee85',['policy','split'],'With the preceding non-empty reviewed variable, shell word splitting supplies package names to apt-cache policy. The no-name behavior differs, which is why the stop condition matters.'),
('CUR-911fbf925b5a9836',['policy','cache','policy-output','policy-table'],'This is a package-policy output illustration. It does not prove these version strings were published in the listed archives, are current candidates or were observed on a Host.'),
('CUR-e95df0457694d116',['policy','dpkg'],'Reviewing every returned package block is sound contextual advice; policy accepts a list of named packages. It does not make candidate equality a universal security-patch test.'),
('CUR-071ae27e331a26d8',['uname','sort','sed-backref'],'This repeated occurrence declares the same running-release/filename comparison; it is not promoted to runtime maintenance success.'),
('CUR-b0878c786928790f',['install'],'Reading APT’s proposed summary is appropriate before accepting package changes. The advice does not promise a particular transaction.'),
('CUR-fad269e41c4872ce',['install','hwe-package'],'This is an illustrative five-new/three-upgrade transaction shape. Counts match the listed example names, but the versions, repository provenance and actual solver transaction are not a retained Host result.'),
('CUR-8d3cf5bdb16885c9',['install','only-upgrade'],'The displayed example names are kernel packages, but dependency solving is not a blanket guarantee that no other package changes. Scope the interpretation to the actual proposal.', 'In this example, the named changes are kernel packages. Your proposed changes\nmay differ, so inspect the full list, including dependencies, before accepting.\nThe `not upgraded` count alone does not prove that all other packages stay unchanged.'),
('CUR-473592d77f21d692',['autoremove','grub-menu'],'Retention and a bootable fallback depend on installed files, removal choices and menu generation. Replace the unconditional retention/recovery promise with a check.', 'Before rebooting, confirm that a known working previous kernel is still\ninstalled and available in the boot menu as a recovery option.'),
('CUR-b23d7be1968df284',['uname','sort','sed-backref'],'The command definition is the same after reboot, but no successful boot, update or GPU result is established here.'),
('CUR-ee242828500d3d5f',['uname','sort','grub-menu'],'The highest version-sorted filename need not be the intended kernel when multiple variants or custom boot choices exist. It is not a mandatory equality.', 'Compare the running release with the kernel you intended to boot. For a\nsingle kernel stack, the two lines may match as in this example; multiple\nvariants or a custom boot entry need separate interpretation:'),
('CUR-575aea631f47603a',['uname','sort'],'Two matching release strings are an illustrative comparison result. The specific version is not attributed to an executed maintenance run.'),
('CUR-a559945e17fa15d2',['dpkg','format','ii','policy'],'The combined command rebuilds the variable from the current package database and requests named policy blocks. A non-empty query must still be checked; this is command-definition proof only.'),
('CUR-6b4e95086ab62b5a',['nvidia'],'Checking that GPUs are visible after maintenance is scoped advice before further validation. nvidia-smi visibility alone does not prove workload health or Host availability.'),
('CUR-1f9574850b947bee',['nvidia'],'NVIDIA documents the monitoring utility. No current GPU inventory, driver compatibility or workload is asserted by this command fence.'),
('CUR-ca3078a7c825a5d0',['uname','sort','policy','grub-default'],'These observations show a running-release/file-selection difference, but do not prove an entire upgrade succeeded or uniquely diagnose GRUB.', 'If `uname -r` differs from the kernel you intended to boot, inspect the\ninstalled kernel files and boot configuration. Matching `Installed` and\n`Candidate` values describe the selected metapackage state; they do not by\nthemselves prove which kernel booted or that the upgrade completed correctly.'),
('CUR-2ebd75c40a5c75bd',['grub22','grub24'],'Both retained Ubuntu source versions source the main configuration before existing *.cfg drop-ins. This is the configuration-variable view only; generated entries and boot-time overrides also matter.'),
('CUR-b2181872a9ad2e1f',['grub22','grub24','variables'],'The Bash command displays variables after the same main/drop-in source order. It is not an exact execution of grub-mkconfig or proof of the currently booted entry; only trusted local configuration is assumed.'),
('CUR-6809a4c960eda2d5',['grub-default','grub-saved'],'These are valid illustrative configuration variable values. They do not guarantee entry zero is a particular kernel or that a machine boots it.'),
('CUR-7b73c6173802d7f6',['grub-default','grub-menu'],'Zero identifies the first generated entry, while the standard highest-kernel menu behavior is qualified and may be affected by custom entries or saved/one-time selection.', 'Entry `0` is the first entry in the generated menu. GRUB normally creates a\ntop-level entry for the highest-version kernel it finds, but custom entries\nand boot-time overrides can change what starts. Inspect the generated menu\nbefore choosing an entry.'),
('CUR-4e7986cff4ca2aba',['grub-default'],'This illustrates a quoted submenu/title selection rather than a universally present title. Its kernel version is an example, not actual boot configuration.'),
('CUR-813ddd58376f9ea4',['grub22','grub24'],'Tracing assignments before editing is appropriate contextual advice. The displayed grep finds only its exact line pattern and does not evaluate arbitrary shell code.'),
('CUR-529bcca689588850',['grub22','grub24'],'The static grep searches the named configuration tree for assignments beginning exactly GRUB_DEFAULT=. It does not parse every valid shell assignment or establish final values.'),
('CUR-4379d1862bb17e91',['grub-default'],'Choose zero only when the intended kernel is the first generated entry, rather than treating zero as a universal repair.', 'If the intended kernel is the first generated entry, set `GRUB_DEFAULT` to\n`0`, keeping a copy of the configuration first:'),
('CUR-b100a6b8811cf951',['shell','and','or'],'The semicolon runs sed even if the backup cp fails. Parenthesize the existing-backup-or-copy expression and AND-gate the edit.', "```bash\n([ -f /etc/default/grub.bak ] || sudo cp /etc/default/grub /etc/default/grub.bak) && sudo sed -i 's/^GRUB_DEFAULT=.*/GRUB_DEFAULT=0/' /etc/default/grub && grep '^GRUB_DEFAULT=' /etc/default/grub\n```"),
('CUR-8d310ddf00fa297c',['or'],'The file-existence guard preserves an existing .bak and skips creating another. It does not establish whether that existing backup is the desired baseline; inspect it before relying on recovery.'),
('CUR-586f9b05d71806be',['grub-saved'],'GNU GRUB explicitly limits SAVEDEFAULT usefulness to DEFAULT=saved. This is a variable interaction, not proof of the selected kernel.'),
('CUR-2d1d81288e4175bd',['grub22','grub24'],'Later sourced assignments can override the main variable. Review conflicting drop-in assignments; a file without an applicable assignment does not inherently override it.'),
('CUR-fcb16e03504f6ebf',['update-grub','grub22'],'The main/drop-in files are generator inputs, so editing them requires regeneration to change the generated menu. This does not prove the bootloader points to that menu.'),
('CUR-79a6df1e8bbad924',['update-grub'],'Ubuntu defines update-grub as running grub-mkconfig to write /boot/grub/grub.cfg. No actual menu generation or reboot was performed.'),
('CUR-b04fd6fd8740f725',['grub-image','grub-initrd'],'The scripts report images found; this should be an inspection instruction rather than a promised result.', 'Check the output for the intended kernel and its matching initrd. Investigate\nerrors or missing files before rebooting:'),
('CUR-49f721c7b1bd403d',['grub-image','grub-initrd'],'The source emits the displayed Found linux/initrd image labels. The paths and versions form an illustrative output example, not an observed generated menu or boot result.'),
('CUR-1af98b0b15519b08',['uname','grub-default'],'A configured default does not guarantee the highest filename is the correct boot choice. Verify the intended release after reboot.', 'Then repeat step 5 and confirm that `uname -r` reports the kernel you intended\nto boot. Investigate a mismatch before returning the machine to service.'),
('CUR-636734966b81d1e7',['grub-menu','grub-keys'],'A prior kernel may have been removed or may also fail; menu visibility and titles vary. The manual supports Shift/Esc in the relevant timeout modes, not a universal right-Shift recovery guarantee.', 'If a known working previous kernel is still installed and present in the\nGRUB menu, try booting it from the console. Holding **Shift** or pressing **Esc**\nmay reveal the menu, depending on the firmware and GRUB settings. Under\n**Advanced options for Ubuntu**, choose the entry for that kernel; its exact\ntitle and version depend on your installation.'),
('CUR-9c17c66b613dcdf7',['ssh22','ssh24','include22','include24'],'Jammy and Noble document these same server configuration and testing interfaces. This scope statement does not promise that custom images start with identical settings.'),
('CUR-1925fb93343cf99c',['publickey'],'A separate successful key-only login reduces risk, but cannot guarantee no lockout after a later configuration/restart failure. Preserve the precaution without the guarantee.', 'Do not turn off password login until a separate key-only connection succeeds.\nKeep your current session open and confirm that you have a recovery route before\nchanging or restarting SSH.'),
('CUR-491405aec946ed50',['ssh24','match'],'sshd -T reads and validates effective configuration and exits; it does not query the running daemon or attempt login. Match evaluation needs connection parameters.', 'This checks the configuration files and prints the effective settings, then\nexits. It does not query the running daemon or test a login. Connection-specific\n`Match` rules need an appropriate `-C` connection specification.'),
('CUR-7e77074195015fd0',['ssh24'],'The command filters effective test-mode configuration output for the named keyword. It is not a live password-authentication test.'),
('CUR-c103c9a09dd0aca0',['password','ssh24'],'This is an illustrative effective-setting output using a documented yes value, not proof of the current Host or every Ubuntu image default.'),
('CUR-cc56d7fed7a590cc',['ssh24','password','interactive','match'],'A global PasswordAuthentication no is not sufficient to claim all password-based access is off: Match, keyboard-interactive and running-daemon state matter.', 'If it says `no`, the displayed configuration disables the password\nauthentication method for that evaluation. Still review applicable `Match`\nrules and keyboard-interactive settings, and confirm access after applying\nchanges. If it says `yes`, continue.'),
('CUR-a5c155e49d0bbb7f',['keycopy'],'ssh-copy-id installs public keys at the remote account using the destination argument. Adjacent text supplies username/IP placeholders; no key installation was executed.'),
('CUR-08c0bd1c5797187f',['keycopy-output'],'The retained OpenSSH script emits Number of key(s) added: followed by the count. One is an illustrative value, not a retained result of this session.'),
('CUR-97f860901c54e022',['publickey'],'PreferredAuthentications=publickey restricts the client authentication methods to publickey. Actual successful login and which key was accepted need observation, not this declaration.'),
('CUR-cccaaf33c813b98a',['strict','publickey','keyfiles','keyperms'],'Publickey rejection does not uniquely mean a bad key; account, path, ownership and server policy can also prevent authentication. Reframe the checks as troubleshooting.', 'If you get `Permission denied (publickey)`, stop: that connection did not\nauthenticate with a key. Check the account, the server’s configured authorized\nkeys file, ownership and permissions, and the SSH server logs. For the usual\n`~/.ssh/authorized_keys` layout, modes `700` for `~/.ssh` and `600` for the file\nare restrictive choices; they do not by themselves prove login will work.'),
('CUR-4c05c6454b7e6248',['cp22','cp24','and'],'An unmatched *.conf glob is passed literally to cp, and separate commands do not gate the drop-in backup on main-file backup success. Guard regular files and stop on a copy failure.', '```bash\nsudo cp -n /etc/ssh/sshd_config /etc/ssh/sshd_config.orig &&\nsudo sh -c \'for f in /etc/ssh/sshd_config.d/*.conf; do [ -f "$f" ] || continue; cp -n "$f" "$f.orig" || exit; done\'\n```'),
('CUR-8a781b4b3ee17155',['include22','include24','password'],'The instruction targets existing directives in the standard main file/drop-in directory. Custom includes and conditional scopes still need review; this is configuration guidance, not verified authentication state.'),
('CUR-994864e626e37c79',['sed-case','sed-backref','and'],'The unguarded glob can pass a nonexistent file and stderr suppression hides edit failures. Preserve the substitution while selecting existing files and surfacing failure.', '```bash\nsudo sh -c \'\n[ -f /etc/ssh/sshd_config ] || exit 1\nfor file in /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf; do\n  [ -f "$file" ] || continue\n  sed -i -E "s/^[[:space:]]*#?[[:space:]]*(PasswordAuthentication)[[:space:]]+.*/\\\\1 no/I" "$file" || exit\ndone\'\n```'),
('CUR-798805fce5932096',['and','sed-backref'],'Silence alone is not successful editing. Replace the bare output assertion with a status/error instruction.', 'Successful editing normally produces no output. Check the command’s exit\nstatus and any error messages before continuing.'),
('CUR-aab78d01230cadd7',['sed-case','sed-backref','include24'],'The expression handles comments, leading space and keyword case only in supplied files; it does not catch every cloud-created file or add an absent directive.', 'This updates matching directives, including commented or indented ones, in\nthe main configuration and existing `.conf` files in the named directory. It\ndoes not add a missing directive or search other include paths.'),
('CUR-1d35238977984a80',['include24','password'],'The standard main configuration accepts the displayed directive. This is a manual-edit instruction, not proof no included/conditional value supersedes it.'),
('CUR-d55d8d105b5208a7',['password'],'The directive and no value are defined for the password authentication method. Other methods and applicable Match context remain distinct.'),
('CUR-8ddd4e60088f5136',['include24','match'],'The following grep only searches one directory, so it cannot establish nothing else overrides the value. Bound the purpose of this check.', 'Check the standard drop-in directory for other settings, and review any\ncustom `Include` paths or applicable `Match` blocks:'),
('CUR-af17cbe601f9bff5',['include24'],'This grep is a case-insensitive textual search in the standard directory only. It does not resolve Match scopes, custom includes or running daemon state; absence of stdout is inconclusive when errors are redirected.'),
('CUR-369807ee343ca7ec',['include22','include24','first','match'],'Include placement determines precedence; Ubuntu ships it at the start, and applicable Match blocks are a separate scope. Remove the universal directory-first rule.', 'Set the relevant `PasswordAuthentication` directives to `no`. Ubuntu’s\nshipped configuration includes this directory at the start, so earlier global\nvalues take precedence over later ones. Custom include placement and applicable\n`Match` blocks require separate review.'),
('CUR-d9859ac08ad2d5e2',['password','first'],'Comments do not activate a directive, and yes permits the password method. It does not guarantee a successful account login or disable keyboard-interactive.'),
('CUR-c45792c338dd5466',['ssh-test','and'],'No stdout does not establish two commands succeeded, and this source review cannot guarantee session survival through service management. Use exit status and a new connection.', 'Check that both commands completed successfully. Keep the original session\nopen while you test a new key-only connection; do not rely on silence or assume\nthat a restart preserves every session.'),
('CUR-dd6a893ee8bdc2d8',['ssh24'],'The following command evaluates files, not the running daemon or a password login. Correct its advertised purpose.', 'Recheck the effective configuration on disk. This command does not by itself\nconfirm that the running service rejects password logins:'),
('CUR-87807c07b36119df',['ssh24'],'This repeated test-mode command has the same source-defined scope after service changes; its placement does not make it runtime authentication evidence.'),
('CUR-eb3aafade07aecdb',['password','ssh24'],'No is a supported illustrative effective configuration value, not proof the running service or all connection contexts reject password-based authentication.'),
('CUR-7b9a0fdeb17059be',['publickey','ssh24','match'],'The final connection should explicitly be key-only. Effective-file output alone does not prove the target security behavior or safely authorize closing recovery access.', 'Repeat the key-only login from step 2 after applying the changes. Review any\nconnection-specific settings before closing the original session; the `no`\noutput alone is not a live authentication test.'),
('CUR-e5b9bf976e579a57',['include22','include24'],'Restoration depends on which files were changed. Ubuntu’s shipped include order is supported, but every machine does not necessarily have a changed disabling drop-in.', 'If you changed drop-in files, restore those backups as well as the main\nconfiguration. Ubuntu’s shipped configuration includes the drop-in directory\nat the start, so a remaining earlier setting can override a later main-file value.'),
]

def build():
 out=[]
 for id,tags,why,*repl in S4:
  x=rows[id];c=current(x)
  d={'id':id,'family':'S4','model_pointer':x['model_pointer'],'page':x['page'],'headings':c['headings'],'spans':c['spans'],'literal_sha256':x['literal_sha256'],'current_literal':c['text'],'decision':'correction'if repl else'supported','proofs':[P[t]for t in tags],'support_rationale':why,'limits':'Official command/configuration declarations, bounded static context and disposable fixture results only. No Ubuntu Host installation, boot, SSH authentication, GPU health, rental availability or policy enforcement was executed or validated. Examples are illustrative, not version-attributed runtime results.','next_action':'Apply the exact replacement, check the changed source span and preserve the original discrepancy.'if repl else'No additional Host run is required for this source-defined occurrence; retain the stated runtime and example limits.'}
  fixture_ids={'CUR-b100a6b8811cf951':[1,2,3],'CUR-4c05c6454b7e6248':[4,5],'CUR-994864e626e37c79':[6,7],'CUR-dc15f757356d0e8e':[8],'CUR-54b525bbf018345d':[8],'CUR-1d8527ed28f606bb':[9]}
  if id in fixture_ids:d['proofs'] += [proof('static-fixtures.json',f'/checks/{i}/finding') for i in fixture_ids[id]]
  if repl:d.update(original_discrepancy=why,replacement=repl[0],replacement_sha256=hashlib.sha256(repl[0].encode()).hexdigest(),replacement_review='Read the full replacement against the selected primary-source definitions and adjacent workflow. It removes the unsupported outcome or fixes local shell control flow without claiming a completed Host run.')
  out.append(d)
 assert len(out)==78 and {d['id']for d in out}=={x['id']for x in rows.values()if x['family']=='S4'}
 return out
if __name__=='__main__':
 j={'record_type':'EXPLICIT_S4_SOURCE_REVIEW','decisions':build()};(O/'decisions-s4.json').write_text(json.dumps(j,indent=2)+'\n');print({k:sum(d['decision']==k for d in j['decisions'])for k in['supported','correction','residual']})
