import datetime,hashlib,json,pathlib,subprocess
from decimal import Decimal as D
O=pathlib.Path(__file__).parent;repo=pathlib.Path('/private/tmp/host-docs-d10-3o6tftdu/current-cli');rev='1c6f8b61d3929a7ae423f89a3a0a53e4e9be02bc'
rows=[]
for key,ref,start,end in [('offer-fields','vastai/cli/commands/offers.py',74,127),('listing-controls','vastai/cli/commands/machines.py',230,259),('market-price-fields','vastai/cli/commands/metrics.py',20,54),('rental-price-scope','vastai/cli/commands/price_increase.py',123,145)]:
 b=(repo/ref).read_bytes();assert b==subprocess.check_output(['git','-C',str(repo),'show',rev+':'+ref]);text='\n'.join(b.decode().splitlines()[start-1:end])
 rows.append({'id':key,'repository':'vast-ai/vast-cli','revision':rev,'source_path':ref,'source_sha256':hashlib.sha256(b).hexdigest(),'source_url':f'https://github.com/vast-ai/vast-cli/blob/{rev}/{ref}#L{start}-L{end}','lines':[start,end],'text':text,'matches_pinned_git_blob':True})
(O/'canonical-cli-excerpts.json').write_text(json.dumps({'record_type':'EXACT_PINNED_CODE_EXCERPTS','excerpts':rows,'limit':'CLI declaration/source only. No new runtime, market ranking, usage frequency, profitability, or backend enforcement verification.'},indent=2)+'\n')
checks=[{'id':'utilization-fraction','expression':'55 / 100','actual':str(D(55)/100),'expected':'0.55'}, {'id':'monthly-example-p10','expression':'4 * 0.35 * 720 * 0.55','actual':str(4*D('.35')*720*D('.55')),'expected':'554.4000'}, {'id':'monthly-example-median','expression':'4 * 0.45 * 720 * 0.55','actual':str(4*D('.45')*720*D('.55')),'expected':'712.8000'},{'id':'monthly-example-p90','expression':'4 * 0.65 * 720 * 0.55','actual':str(4*D('.65')*720*D('.55')),'expected':'1029.6000'}, {'id':'price-utilization-tradeoff','expression':'1 * 720 * 0.10 < 0.50 * 720 * 0.80','actual':D('1')*720*D('.10') < D('.50')*720*D('.80'),'expected':True}, {'id':'net-margin-identity','expression':'712.80 - (100 + 50 + 80 + 20)','actual':str(D('712.80')-sum(map(D,['100','50','80','20']))),'expected':'462.80'}]
for c in checks:assert c['actual']==c['expected'],c
(O/'arithmetic-review.json').write_text(json.dumps({'record_type':'DISPOSABLE_ARITHMETIC_FIXTURE','created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'result':'PASS','checks':checks,'dimensional_check':'hourly price × utilization alone is not revenue: multiply by a fixed number of GPUs and hours; for equal GPU-hours, revenue is proportional to price × utilization.','limit':'Illustrative arithmetic and advice inputs only. These prices, utilization and costs are chosen examples, not actual earnings, demand forecasts, fee rules or investment recommendations.'},indent=2)+'\n')
print('4 pinned CLI excerpts; 6 exact arithmetic checks retained')
