/** Sealed evidence-reuse successor. Source definitions are not live outcomes. */
import crypto from 'node:crypto';
import {projectSourceFamilyReview} from './current_host_source_family_review.mjs';
export const EVIDENCE_REUSE_PATH='verification/current-host-evidence-reuse-review.json';
export const EVIDENCE_REUSE_SHA256='4de91a5ed44daa2546e3ccf5225f5bc48d54fe646f2fa2d1c92bf04f8da788e4';
export const EVIDENCE_REUSE_ATTEMPT='verification/evidence/2026-09-15-host-evidence-reuse-source-review-attempt-01';
const ADJACENT_SHA256='416e9bc1f35f345e247a0c526933169915acd5df846fb228cc81dcac8c2e46fe';
const A=EVIDENCE_REUSE_ATTEMPT,MARKER='HOST-EVIDENCE-REUSE-REVIEW-01';
const INVENTORY_SHA='4c9abd5c7feecad626ddd458d994f6f243973550802cce2881628e6857ea64ac',BASELINE_SHA='f65129d631011c03d344cd33b7e88004ed2f24f13e47bf7a9ec69a588c284021';
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v,serial=v=>JSON.stringify(canon(v)),equal=(a,b)=>serial(a)===serial(b),req=(v,m)=>{if(!v)throw Error('host evidence-reuse review: '+m);};
const lines=raw=>raw.toString().replace(/\n$/,'').split(/\r?\n/),index=m=>new Map(m.pages.flatMap(p=>p.claims.map(c=>[c.id,c]))),sameSet=(a,b)=>equal([...a].sort(),[...b].sort()),omit=(o,k)=>Object.fromEntries(Object.entries(o).filter(([name])=>name!==k));
function selection(raw,pointer){req(typeof pointer==='string'&&pointer.startsWith('/'),'invalid source selector');if(pointer.startsWith('/lines/')){const[first,last]=pointer.slice(7).split('-').map(Number),source=lines(raw);req(first>0&&first<=last&&last<=source.length,'invalid source line range');return source.slice(first-1,last).join('\n');}let value=JSON.parse(raw);for(const token of pointer.slice(1).split('/'))value=value[token.replace(/~1/g,'/').replace(/~0/g,'~')];return typeof value==='string'?value:serial(value);}
export function projectEvidenceReuseReview({read,exists}){
 const pin=(ref,wanted)=>{req(typeof ref==='string'&&ref&&!ref.startsWith('/')&&!ref.includes('\\')&&ref.split('/').every(p=>p&&!['.','..'].includes(p)),'unsafe path');const raw=read(ref);req(sha(raw)===wanted,'digest drift '+ref);return raw;};
 const registry=JSON.parse(pin(EVIDENCE_REUSE_PATH,EVIDENCE_REUSE_SHA256));req(sameSet(Object.keys(registry),['schema_version','record_type','generated_at','scope','sources','artifacts','transitions','procedures','limits']),'registry keys');req(registry.schema_version==='1.0'&&registry.record_type==='HOST_EVIDENCE_REUSE_REVIEW','registry type');
 const inventory=JSON.parse(pin(A+'/inventory.json',INVENTORY_SHA)),baselineCheck=JSON.parse(pin(A+'/integration-baseline.json',BASELINE_SHA));req(registry.scope.path===A+'/integration-scope.json','scope path');const scope=JSON.parse(pin(registry.scope.path,registry.scope.sha256)),expansion=JSON.parse(pin(A+'/adjacent-scope.json',ADJACENT_SHA256)),frozenClaims=[...inventory.claims,...expansion.claims],ids=new Set(frozenClaims.map(c=>c.id));Object.assign(inventory.source_hashes,expansion.source_hashes);req(ids.size===312&&inventory.claims.length===309&&expansion.claims.length===3&&sameSet(Object.keys(scope.decisions),ids),'frozen decision inventory');
 const before=new Map(),current=new Map(),maps=new Map(),afterHashes=new Map();
 for(const source of registry.sources){const ref=source.path;req(Object.hasOwn(inventory.source_hashes,ref)&&!before.has(ref),'source scope');req(source.before_artifact.path===A+'/sources-before/'+ref,'before source path');before.set(ref,pin(source.before_artifact.path,source.before_artifact.sha256));req(sha(before.get(ref))===inventory.source_hashes[ref],'before source drift');current.set(ref,pin(ref,source.after_sha256));afterHashes.set(ref,sha(current.get(ref)));const oldLines=lines(before.get(ref)),newLines=lines(current.get(ref)),map=new Map(source.line_map);maps.set(ref,map);req(map.size===source.line_map.length&&new Set(map.values()).size===map.size,'duplicate line map');req(equal([...map.keys()],[...map.keys()].sort((a,b)=>a-b))&&equal([...map.values()],[...map.values()].sort((a,b)=>a-b)),'unordered line map');for(const[a,b]of map)req(a>0&&a<=oldLines.length&&b>0&&b<=newLines.length&&oldLines[a-1]===newLines[b-1],'source relocation drift');const oldChanged=new Set(),newChanged=new Set();for(const e of source.edits){for(let n=e.before_start;n<=e.before_end;n++)oldChanged.add(n);for(let n=e.after_start;n<=e.after_end;n++)newChanged.add(n);}req([...map.keys()].every(n=>!oldChanged.has(n))&&sameSet([...map.keys(),...oldChanged],oldLines.map((_,i)=>i+1)),'before line partition');req([...map.values()].every(n=>!newChanged.has(n))&&sameSet([...map.values(),...newChanged],newLines.map((_,i)=>i+1)),'after line partition');}
 for(const[ref,wanted]of Object.entries(inventory.source_hashes))if(!before.has(ref))pin(ref,wanted);
 const historicalRead=ref=>before.get(ref)||read(ref),pre=projectSourceFamilyReview({read:historicalRead,exists}),baseline=pre.model,old=index(baseline);req(sha(serial(baseline))===baselineCheck.baseline_model_canonical_sha256,'complete predecessor differs from baseline');req(equal(Object.fromEntries([...old].map(([id,c])=>[id,sha(serial(c))])),baselineCheck.claim_hashes),'baseline claim inventory');req(sha(serial(baseline.pages.map(p=>p.procedures)))===baselineCheck.procedure_population_sha256,'baseline procedures');for(const c of frozenClaims)req(old.get(c.id).status===c.claim.status&&sha(old.get(c.id).text)===c.literal_sha256,'frozen literal drift');
 const artifacts=new Map(registry.artifacts.map(a=>[a.path,pin(a.path,a.sha256)]));req(artifacts.size===registry.artifacts.length,'duplicate artifact');
 const relocate=span=>{const map=maps.get(span.source_file);if(!map)return structuredClone(span);const values=[];for(let n=span.start;n<=span.end;n++)values.push(map.get(n));if(values.some((v,i)=>v===undefined||v!==values[0]+i))return null;return {...span,start:values[0],end:values.at(-1)};};
 const verify=span=>{const source=lines(current.get(span.source_file)||read(span.source_file));req(span.start>0&&span.start<=span.end&&span.end<=source.length,'span bounds');const text=source.slice(span.start-1,span.end).join('\n');req(sha(text)===span.text_sha256,'span text drift');return text;};
 const model=structuredClone(baseline),claims=index(model),entries=new Map(registry.transitions.map(e=>[e.claim_id,e]));req(registry.transitions.length===312&&sameSet(entries.keys(),ids),'transition scope');
 for(const[id,entry]of entries){const prior=old.get(id),patch=entry.after,decision=scope.decisions[id];req(entry.before_sha256===sha(serial(prior)),'claim predecessor '+id);req(equal(entry.residual_topic||null,decision.residual_topic||null),'unaccepted residual topic');req(Object.keys(patch).every(k=>['text','spans','status','classification','required_evidence_types','owner_role','rationale','next_action','evidence_refs','source_refs','coverage_state'].includes(k)),'unsupported patch');req(sha(serial(Object.fromEntries(['text','status','classification','required_evidence_types','owner_role'].map(k=>[k,patch[k]]))))===decision.fields_sha256,'accepted disposition drift '+id);req(['PASS','FAIL','BLOCKED','UNVALIDATED','NOT_APPLICABLE'].includes(patch.status),'unknown status');req(prior.evidence_refs.every(e=>patch.evidence_refs.some(a=>equal(a,e)))&&prior.source_refs.every(s=>patch.source_refs.some(a=>equal(a,s))),'discarded prior evidence');if(!equal(patch.required_evidence_types,prior.required_evidence_types))req(entry.method_rationale===decision.method_rationale&&Boolean(entry.method_rationale),'unjustified method change');req(entry.basis.length&&entry.limits&&patch.rationale,'missing scoped review');for(const basis of entry.basis){const ref=basis.artifactRef;req(artifacts.has(ref)&&selection(artifacts.get(ref),basis.text_pointer)===basis.excerpt,'source selector/excerpt drift '+id);req(basis.support_rationale&&patch.evidence_refs.some(e=>e.artifact_ref===ref),'unbound evidence');req(patch.source_refs.some(s=>s.path===(basis.sourceUrl||ref)&&s.locator===basis.text_pointer),'unbound source');}Object.assign(claims.get(id),structuredClone(patch),{history:{...prior.history,evidence_reuse_review:{marker:MARKER,before_claim_sha256:sha(serial(prior)),prior_status:prior.status,prior_text_sha256:sha(prior.text),prior_text:patch.text!==prior.text?prior.text:null,limits:entry.limits}}});}
 const procedureEntries=new Map(registry.procedures.map(p=>[p.model_pointer,p])),seenProcedures=new Set();req(procedureEntries.size===registry.procedures.length,'duplicate procedure review');
 for(const[pageIndex,page]of model.pages.entries()){if(afterHashes.has(page.source_file)){page.source_sha256=afterHashes.get(page.source_file);page.coverage_state='CHANGED';}for(const dep of page.dependencies)if(afterHashes.has(dep.source_file)){dep.source_sha256=afterHashes.get(dep.source_file);page.coverage_state='CHANGED';}for(const claim of page.claims){const id=claim.id;if(!Object.hasOwn(entries.get(id)?.after||{},'spans'))claim.spans=old.get(id).spans.map(relocate);req(!claim.spans.includes(null),'unreviewed changed occurrence '+id);const literal=claim.spans.map(verify).join('\n');if(claim.text!==old.get(id).text)req(literal===claim.text,'replacement literal drift '+id);if(!ids.has(id))req(equal(omit(claim,'spans'),omit(old.get(id),'spans')),'unrelated claim drift '+id);}for(const[procedureIndex,procedure]of page.procedures.entries())for(const[nodeIndex,node]of [procedure,...procedure.nodes].entries()){const pointer=`/pages/${pageIndex}/procedures/${procedureIndex}`+(nodeIndex?`/nodes/${nodeIndex-1}`:'');const entry=procedureEntries.get(pointer);if(entry){req(entry.id===node.id&&sha(serial(omit(node,'nodes')))===entry.before_sha256,'procedure predecessor');req(equal(entry.after,scope.procedures[pointer].after)&&entry.reason===scope.procedures[pointer].reason,'unaccepted procedure change');req(Object.keys(entry.after).every(k=>['spans','status','coverage_state','limits','history'].includes(k)),'procedure patch scope');Object.assign(node,structuredClone(entry.after));seenProcedures.add(pointer);}else{const spans=(node.spans||[]).map(relocate);req(!spans.includes(null),'unreviewed changed procedure '+node.id);node.spans=spans;}for(const span of node.spans||[])verify(span);}}
 req(sameSet(seenProcedures,procedureEntries.keys())&&sameSet(seenProcedures,Object.keys(scope.procedures)),'procedure scope drift');for(const item of model.source.source_manifest)if(afterHashes.has(item.path))item.sha256=afterHashes.get(item.path);req(old.size===2008&&sameSet(index(model).keys(),old.keys()),'active claim inventory drift');
 const count=values=>Object.fromEntries([...values.reduce((m,k)=>m.set(k,(m.get(k)||0)+1),new Map())].sort(([a],[b])=>a.localeCompare(b)));model.counts.claim_statuses=count([...claims.values()].map(c=>c.status));model.counts.page_coverage_states=count(model.pages.map(p=>p.coverage_state));model.generated_at=registry.generated_at;model.corrections.push({id:MARKER,scope:'312 frozen occurrences (309 review + 3 adjacent fixes)',history:'Sealed source-family predecessor replayed with exact before-source bytes; all prior findings and evidence retained.',current:'Accepted per-passage source reviews and corrections; explicit residual defects remain visible.',reason:registry.limits});
 const presentation=new Map(pre.presentation);for(const[id,entry]of entries)presentation.set(id,{previous:structuredClone(old.get(id)),method:entry.method,reviewRationale:claims.get(id).rationale,remaining:entry.limits,registryRef:EVIDENCE_REUSE_PATH,baselineRef:A+'/integration-baseline.json',basis:entry.basis.map(b=>({...structuredClone(b),kind:b.sourceKind==='STATIC_CONTEXT_REVIEW'?'CONTEXT_REVIEW':b.sourceKind,sourceLabel:b.sourceUrl||b.artifactRef})),auditHistory:pre.presentation.has(id)?[structuredClone(pre.presentation.get(id))]:[],evidenceReuse:true});
 const artifactHashes=new Map([...pre.artifactHashes,[EVIDENCE_REUSE_PATH,EVIDENCE_REUSE_SHA256],[A+'/inventory.json',INVENTORY_SHA],[A+'/integration-baseline.json',BASELINE_SHA],[A+'/adjacent-scope.json',ADJACENT_SHA256],[registry.scope.path,registry.scope.sha256],...afterHashes,...registry.sources.map(s=>[s.before_artifact.path,s.before_artifact.sha256]),...registry.artifacts.map(a=>[a.path,a.sha256])]);
 return {...pre,model,matches:new Map([...pre.matches].map(([id,match])=>[id,{...match,claim:claims.get(id)}])),presentation,artifactHashes,evidenceReuse:{registry,registrySha256:EVIDENCE_REUSE_SHA256,scope:registry.scope,baseline:A+'/integration-baseline.json',baselineSha256:BASELINE_SHA,resultRef:A+'/result.md'}};
}
export function loadEvidenceReuseReview({read,model,exists}){const present=exists?exists(EVIDENCE_REUSE_PATH):(()=>{try{read(EVIDENCE_REUSE_PATH);return true;}catch(error){if(error.code==='ENOENT')return false;throw error;}})(),marked=(model.corrections||[]).some(x=>x.id===MARKER);if(!present){req(!marked,'evidence-reuse-marked model has no registry');return null;}const projected=projectEvidenceReuseReview({read,exists});req(equal(projected.model,model),'whole model differs from evidence-reuse projection');return projected;}
