import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import {loadCurrentHostReviewTransition} from './current_host_review_transition.mjs';
import {validateAuthorityScanInput,loadAuthorityScan,canonicalHash,AUTHORITY_SCAN_PATH,AUTHORITY_SCAN_ATTEMPT,AUTHORITY_SCAN_BASELINE_PATH,AUTHORITY_SCAN_SNAPSHOT_PATH,AUTHORITY_SCAN_DECISION} from './current_host_authority_scan.mjs';

const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const encode=value=>Buffer.from(JSON.stringify(value));
const ids=['VOL-C06','VOL-C08','VOL-C10','VOL-C14','VOL-C16','VOL-C20','VOL-C21','MCL-17c8031cb2c7e34a','SOURCE-EXACT-01'];
// An independent synthetic before/after oracle, not the production projector.
// Population sizes deliberately match production so completeness checks run.
function fixture(source='Hosting providers maintain equipment.'){
  const files=new Map(),sourceHash=hash(source);
  const oldEvidence='verification/evidence/fixture-static.json',governing='verification/evidence/fixture-agreement.json';
  files.set(oldEvidence,encode({checks:[{result:'PASS',limit:'Client interface only.'}]}));
  files.set(governing,encode({url:'https://cloud.vast.ai/host/agreement',sections:[{text:source}]}));
  const pages=Array.from({length:44},(_,i)=>({route:`/host/page-${i}`,title:`Page ${i}`,source_file:`host/page-${i}.mdx`,source_sha256:sourceHash,dependencies:[],coverage_state:'UNCHANGED_EXACT',claims:[],procedures:[]}));
  const manifest=[];for(let i=0;i<144;i++){const path=i<44?pages[i].source_file:`snippets/source-${i}.mdx`;files.set(path,Buffer.from(source));manifest.push({kind:i<44?'PRIMARY':'RENDERED_DEPENDENCY',route:i<44?pages[i].route:pages[0].route,path,sha256:sourceHash});}
  for(let i=0;i<2013;i++){const page=pages[i%44],id=ids[i]||`CLAIM-${i}`,isPriorPass=i<8;page.claims.push({id,text:source,headings:['Introduction'],spans:[{source_file:page.source_file,start:1,end:1,text_sha256:sourceHash}],status:isPriorPass?'PASS':'UNVALIDATED',required_evidence_types:[isPriorPass?'REPOSITORY_STATIC_CHECK':'AUTHORITATIVE_DOCUMENTATION_CITATION'],owner_role:'Source reviewer',rationale:'Original finding.',next_action:'Inspect independent source.',evidence_refs:isPriorPass?[{id:'STATIC-01',role:'STATIC',limit:'Client interface only.',artifact_ref:oldEvidence}]:[],source_refs:[],history:{baseline_claim_id:id,baseline_source_text_sha256:sourceHash,carry_decision:'CARRIED_FORWARD_EXACT_SOURCE',reason:'Original exact occurrence.'},classification:'PRODUCT_BEHAVIOR',coverage_state:'UNCHANGED_EXACT'});}
  const support=Array.from({length:33},(_,i)=>({support_id:`SUPPORT-${i}`,source_file:`snippets/source-${i+44}.mdx`,fragment_file:`snippets/source-${i+44}.mdx`,central_reference_file:`snippets/source-${i+44}.mdx`,evidence_refs:[]}));
  const baseline={schema_version:'1.0',record_type:'HOST_DOCS_CURRENT_REVIEW',generated_at:'2026-09-09T00:00:00Z',source:{source_manifest:manifest},history:{source_revision:'a'.repeat(40),packages:[]},pages,support_layers:support,counts:{claims:2013,primary_pages:44,claim_statuses:{PASS:8,UNVALIDATED:2005},page_coverage_states:{UNCHANGED_EXACT:44}},corrections:[]};
  const snapshot={type:'SOURCE_UNDER_REVIEW_SNAPSHOT',records:manifest.map(item=>({path:item.path,sha256:item.sha256,snapshot:`${AUTHORITY_SCAN_ATTEMPT}/sources-before/${item.path}`}))};
  for(const row of snapshot.records)files.set(row.snapshot,Buffer.from(source));
  files.set(AUTHORITY_SCAN_BASELINE_PATH,encode(baseline));files.set(AUTHORITY_SCAN_SNAPSHOT_PATH,encode(snapshot));
  const transitions=ids.map(id=>{const before=pages.flatMap(p=>p.claims).find(c=>c.id===id);return {claim_id:id,before_claim_sha256:canonicalHash(before),method:id==='SOURCE-EXACT-01'?'SOURCE_ADJUDICATION':'PROVENANCE_DOWNGRADE',after:{classification:'PRODUCT_BEHAVIOR',status:id==='SOURCE-EXACT-01'?'PASS':'UNVALIDATED',required_evidence_types:id==='SOURCE-EXACT-01'?['AUTHORITATIVE_DOCUMENTATION_CITATION']:['CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION'],owner_role:'Source reviewer',rationale:'Exact source reviewed; broader partial static result is not runtime proof.',next_action:'Read the exact source scope; inspect any remaining implementation gap.',evidence_refs:id==='SOURCE-EXACT-01'?[{id:'AGREEMENT-01',role:'GOVERNING_SOURCE',limit:'Equipment maintenance obligation only.',artifact_ref:governing}]:before.evidence_refs.map(e=>({...e,role:'PARTIAL_STATIC'})),source_refs:id==='SOURCE-EXACT-01'?[{repository:'vast-ai/hosting-agreement',revision:`sha256:${hash(files.get(governing))}`,path:'https://cloud.vast.ai/host/agreement',locator:'Maintenance section',source_kind:'AUTHORITATIVE_DOCUMENTATION_CITATION'}]:[]},basis:id==='SOURCE-EXACT-01'?[{artifact_id:'AGREEMENT',lane:'AUTHORITATIVE_DOCUMENTATION_CITATION',text_pointer:'/sections/0/text',excerpt:source,support_rationale:'Maintenance obligation only; not acceptance or runtime health.'}]:[],review_rationale:'Independent source inspection, with previous record retained.'};});
  const registry={schema_version:'1.0',record_type:'HOST_AUTHORITY_SCAN_TRANSITION',generated_at:'2026-09-09T12:00:00Z',baseline:{path:AUTHORITY_SCAN_BASELINE_PATH,sha256:hash(files.get(AUTHORITY_SCAN_BASELINE_PATH))},source_snapshot:{path:AUTHORITY_SCAN_SNAPSHOT_PATH,sha256:hash(files.get(AUTHORITY_SCAN_SNAPSHOT_PATH))},artifacts:[{id:'STATIC',path:oldEvidence,sha256:hash(files.get(oldEvidence)),kind:'CONTEXT'},{id:'AGREEMENT',path:governing,sha256:hash(files.get(governing)),kind:'GOVERNING_SOURCE',origin:{url:'https://cloud.vast.ai/host/agreement'}}],source_transitions:[],transitions};
  files.set(AUTHORITY_SCAN_PATH,encode(registry));
  const pins={registry:hash(files.get(AUTHORITY_SCAN_PATH)),baseline:registry.baseline.sha256,snapshot:registry.source_snapshot.sha256};
  const model=structuredClone(baseline);model.generated_at=registry.generated_at;
  for(const entry of transitions){const c=model.pages.flatMap(p=>p.claims).find(c=>c.id===entry.claim_id);Object.assign(c,structuredClone(entry.after));c.history.carry_decision=AUTHORITY_SCAN_DECISION;c.history.reason+=' Exact current source/taxonomy transition is recorded in verification/current-host-authority-scan.json; full previous claim is retained in the frozen scan baseline.';}
  model.counts.claim_statuses={PASS:1,UNVALIDATED:2012};model.history.authority_scan={registry:AUTHORITY_SCAN_PATH,registry_sha256:pins.registry,baseline:registry.baseline,source_snapshot:registry.source_snapshot,limit:'Integrity and transition provenance only; not terminal product proof.'};model.corrections.push({id:'HOST-AUTHORITY-SOURCE-FIRST-SCAN-01',scope:'44 primary Host pages; all2013 claim IDs retained',history:'Frozen full before model and all144 source snapshots remain immutable.',current:'9 exact reviewed transitions; no taxonomy-only PASS.',reason:'Existing independent source authority precedes any genuine decision escalation; narrow retained proof does not validate broader claims.'});
  return {files,registry,pins,model,read:ref=>{if(!files.has(ref))throw Error(`Missing ${ref}`);return files.get(ref);}};
}
const validate=f=>validateAuthorityScanInput(f);
function resealFixture(f){f.files.set(AUTHORITY_SCAN_PATH,encode(f.registry));f.pins.registry=hash(f.files.get(AUTHORITY_SCAN_PATH));f.model.history.authority_scan.registry_sha256=f.pins.registry;}

test('independent full-population fixture preserves original evidence and exposes exact governing excerpt',()=>{const f=fixture(),result=validate(f);assert.equal(result.matches.size,2013);assert.equal(result.presentation.size,9);assert.equal(result.presentation.get('VOL-C06').previous.status,'PASS');assert.equal(result.matches.get('VOL-C06').claim.status,'UNVALIDATED');assert.equal(result.presentation.get('SOURCE-EXACT-01').basis[0].excerpt,'Hosting providers maintain equipment.');});
test('production wrapper rejects an unsealed or substituted registry even when it declares coherent hashes',()=>{const f=fixture();assert.throws(()=>loadAuthorityScan(f),/digest drift|unsealed trusted digest/);});
for(const [name,mutate]of [
  ['registry',f=>f.files.set(AUTHORITY_SCAN_PATH,encode({...f.registry,generated_at:'tampered'}))],
  ['whole baseline',f=>f.files.set(AUTHORITY_SCAN_BASELINE_PATH,Buffer.from('{}'))],
  ['source snapshot',f=>f.files.set(AUTHORITY_SCAN_SNAPSHOT_PATH,Buffer.from('{}'))],
  ['raw before source',f=>f.files.set(`${AUTHORITY_SCAN_ATTEMPT}/sources-before/host/page-0.mdx`,Buffer.from('drift'))],
  ['current source',f=>f.files.set('host/page-0.mdx',Buffer.from('drift'))],
  ['retained original evidence',f=>f.files.set('verification/evidence/fixture-static.json',Buffer.from('{}'))],
  ['status',f=>f.model.pages[0].claims[0].status='PASS'],
  ['unreviewed rationale',f=>f.model.pages[0].claims.at(-1).rationale='Invented closure.'],
  ['missing claim',f=>f.model.pages[0].claims.pop()],
  ['support layer',f=>f.model.support_layers[0].evidence_refs.push({artifact_ref:AUTHORITY_SCAN_PATH})],
  ['top-level history',f=>f.model.history.source_revision='b'.repeat(40)],
  ['injected self-model evidence',f=>f.model.pages[0].claims[0].evidence_refs[0].artifact_ref='verification/current-host-docs-review.json'],
])test(`fail closed on ${name} tampering`,()=>{const f=fixture();mutate(f);assert.throws(()=>validate(f),/authority scan/);});
test('even a separately resealed fixture cannot use graph-only proof',()=>{const f=fixture();const artifact=f.registry.artifacts.find(a=>a.id==='AGREEMENT');artifact.path='graphify-out/graph.json';f.files.set(artifact.path,f.files.get('verification/evidence/fixture-agreement.json'));resealFixture(f);assert.throws(()=>validate(f),/derived terminal/);});
test('an exact excerpt is required from the selected source, not merely a matching source count',()=>{const f=fixture();f.registry.transitions.at(-1).basis[0].excerpt='Every rental is guaranteed.';resealFixture(f);assert.throws(()=>validate(f),/excerpt absent/);});
test('taxonomy cannot create PASS even in an independently pinned fixture',()=>{const f=fixture();f.registry.transitions.at(-1).method='TAXONOMY_ONLY';resealFixture(f);assert.throws(()=>validate(f),/classification cannot manufacture proof/);});
function navigationFixture(source){const f=fixture(source),entry=f.registry.transitions.at(-1),artifact=f.registry.artifacts.find(a=>a.id==='AGREEMENT');const text=entry.after.text||f.model.pages.flatMap(p=>p.claims).find(c=>c.id===entry.claim_id).text;entry.method='NAVIGATION_RETEST';entry.after.required_evidence_types=['REPOSITORY_STATIC_CHECK'];entry.after.source_refs=[];entry.basis=[{artifact_id:'AGREEMENT',lane:'REPOSITORY_STATIC_CHECK',support_rationale:'Local navigation destination only.'}];artifact.kind='STATIC_RETEST';delete artifact.origin;f.files.set(artifact.path,encode({checks:[{claim_id:entry.claim_id,text_sha256:hash(text),source_sha256:hash(text),result:'PASS'}]}));artifact.sha256=hash(f.files.get(artifact.path));Object.assign(f.model.pages.flatMap(p=>p.claims).find(c=>c.id===entry.claim_id),structuredClone(entry.after));resealFixture(f);return f;}
test('neutral exact navigation independently resolves its local destination',()=>{const f=navigationFixture('See [Hosting](/host/page-0).');assert.equal(validate(f).matches.get('SOURCE-EXACT-01').claim.status,'PASS');});
test('navigation reports cannot promote an embedded material predicate',()=>{const f=navigationFixture('For why terms lock at rental time, see [Hosting](/host/page-0).');assert.throws(()=>validate(f),/material predicate/);});
test('an existing navigation report cannot be borrowed for a different current source or claim',()=>{const f=navigationFixture('See [Hosting](/host/page-0).'),artifact=f.registry.artifacts.find(a=>a.id==='AGREEMENT');f.files.set(artifact.path,encode({checks:[{claim_id:'OTHER',text_sha256:hash('See [Hosting](/host/page-0).'),source_sha256:hash('See [Hosting](/host/page-0).'),result:'PASS'}]}));artifact.sha256=hash(f.files.get(artifact.path));resealFixture(f);assert.throws(()=>validate(f),/navigation retest binding drift/);});
test('whole before/post projection preserves every occurrence through an exact source relocation',()=>{const f=fixture(),page=f.model.pages[0],ref=page.source_file,before=f.files.get(ref),after=Buffer.from('\n'+before);f.files.set(ref,after);f.registry.source_transitions.push({path:ref,before_sha256:hash(before),after_sha256:hash(after)});page.source_sha256=hash(after);page.coverage_state='CHANGED';for(const claim of page.claims){claim.spans[0].start++;claim.spans[0].end++;claim.coverage_state='CHANGED';if(!f.registry.transitions.some(e=>e.claim_id===claim.id)){claim.history.carry_decision='CURRENT_HOST_AUTHORITY_SCAN_RELOCATION';claim.history.reason+=' Exact unchanged source spans were relocated against the frozen scan source snapshot; no product evidence was added.';}}f.model.source.source_manifest.find(item=>item.path===ref).sha256=hash(after);f.model.counts.page_coverage_states={UNCHANGED_EXACT:43,CHANGED:1};resealFixture(f);const result=validate(f);assert.equal(result.matches.size,2013);assert.equal(result.matches.get('VOL-C06').claim.spans[0].start,2);assert.equal(result.artifactHashes.get(ref),hash(after));});
test('the actual current production model uses the sealed independent reader gate when a scan exists',()=>{const root=new URL('../',import.meta.url),read=ref=>fs.readFileSync(new URL(ref,root));const model=JSON.parse(read('verification/current-host-docs-review.json'));const scan=loadCurrentHostReviewTransition({read,model});if(scan){assert.equal(scan.matches.size,2013);assert.equal(scan.baseline.pages.flatMap(p=>p.claims).length,2013);for(const id of ids.slice(0,7))assert.equal(scan.matches.get(id).claim.status,'UNVALIDATED');}else assert.ok(!model.history.authority_scan);});
