/** Sealed closure successor: source review, retirement and partial observations. */
import crypto from 'node:crypto';
import { projectPayoutInvoiceCorrection } from './current_host_payout_invoice_correction.mjs';
export const CLOSURE_PATH='verification/current-host-closure-correction.json';
export const CLOSURE_SHA256='7db54cd1a7c993e65853419292e8d4f24df1cd71e10ab13f0988de9ce5b33164';
const A='verification/evidence/2026-09-14-host-closure-correction-attempt-01', BASE=A+'/pre-correction-model.json',BASE_SHA='56650fad892d1f1d387dd4328bdb474f7c2c923907419a2b74868c4a68b7daf5',MARKER='HOST-CLOSURE-CORRECTION-01';
const corrected=new Set(['CUR-a991f28f683ba829','CUR-93f089288e67669d','MCL-b61d15c0282ef567','MCL-c59caa4cd52bcc1f','MCL-af1c482a08b09316','MCL-393941d0e9be9d31','MCL-57133525f112013a','MCL-dcb653ae3a927dae','MCL-47b85b40f58091a2','MCL-ae7f4423cef61511']);
const rental=new Set(['MCL-470bf8ec992a342e','MCL-b7440bdb3eb40fa1','MCL-9cfc73236e4c395a','MCL-250a0c0aa31550a1','MCL-5286ec9ff0cc3272','MCL-6e0046c21ac71be4','MCL-939467a533f82627','MCL-e36ac539565db44a','MCL-c9441dfe43eb92f1']),adjacent=new Set(['MCL-5ab653314f9e68e8','MCL-23085b459da844bc']),A2='verification/evidence/2026-09-14-host-closure-correction-attempt-02';
for(const id of rental)corrected.add(id);
const retiredIds=new Set(['MCL-08d534d1cc02eb2c','MCL-4be2159765519977','MCL-b87645b43a9136dd','MCL-d5001953fbd7df0b','MCL-e03564808f65b40b']);
const runtime=new Set(['MCL-d2f649ad765ea7bb','MCL-b15c6cfc26e189c2','MCL-115b4938222083ac','MCL-9edeb94eaa736bca','MCL-e6fb82f7e167fdc8','MCL-3aca6b1f291d4d0c','VOL-C31','VOL-C33']);
const ids=new Set([...corrected,...adjacent,...runtime,'CUR-f9aad9428d594b40','MCL-217525688a0854b4','CUR-65ffc3ba1623ad1c','CUR-bf6233f2e53eca43','MCL-9dc3b0e54070a926','MCL-ab00ca89f31d5db1','MCL-0ae9c2fd5ac2ef9a','MCL-9459e18a155808c9']);
const unchangedIds=new Set(['MCL-b165e7ceb4cea896','MCL-66dcd03d8d3ac701','MCL-9a580f94561b2775','MCL-3b82e89867c343f8','CUR-86637c5b58be0905','CUR-a0c1b91834ef5f98','CUR-e2bb91ee982dd5b1','CUR-acbd513b75fc99a9','CUR-46851196d475b688','CUR-8b49b48a8f4b55e6','CUR-31030b5f3ede8df7','CUR-47f7eac245b806c6','CUR-fa63eb10bec89134','MCL-b4de2df6a8e20829','MCL-6bcbb0e678b9eb65','MCL-e9e8363bc9d2fc20','MCL-f48f7f89c7355a3f','MCL-14556d751bb3fc5b','MCL-582bf3922775c488','MCL-9006e38f7277157f','MCL-151132b1bb16b498','MCL-33c81159a9587c53','MCL-23baa90e841cbe43','MCL-e5ac633b4cd16181']),unchangedHeld=new Set(['CUR-d4f1da8861e06594','CUR-6a6640ac777aa39c']),U='verification/evidence/2026-09-14-host-unvalidated-source-attempt-01',UI=U+'/inventory.json',UI_SHA='fd7d453317ec6aebea68701e49e55fb93337134beb3095d42923d6c3855ec783';
for(const id of unchangedIds)ids.add(id);
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v,serial=v=>JSON.stringify(canon(v)),equal=(a,b)=>serial(a)===serial(b),req=(v,m)=>{if(!v)throw Error('host closure correction: '+m);};
const lines=raw=>raw.toString().replace(/\n$/,'').split(/\r?\n/),index=model=>new Map(model.pages.flatMap(p=>p.claims.map(c=>[c.id,c]))),sameSet=(a,b)=>equal([...a].sort(),[...b].sort());
function selection(raw,pointer){req(typeof pointer==='string'&&pointer.startsWith('/'),'invalid source selector');if(pointer.startsWith('/lines/')){const [first,last]=pointer.slice(7).split('-').map(Number),source=lines(raw);req(first>0&&first<=last&&last<=source.length,'invalid source line range');return source.slice(first-1,last).join('\n');}let value=JSON.parse(raw);for(const part of pointer.slice(1).split('/'))value=value[part];return typeof value==='string'?value:serial(value);}
export function projectClosureCorrection({read,exists}){
 const pin=(ref,wanted)=>{req(typeof ref==='string'&&ref&&!ref.startsWith('/')&&!ref.includes('\\')&&ref.split('/').every(p=>p&&!['.','..'].includes(p)),'unsafe path');const raw=read(ref);req(sha(raw)===wanted,'digest drift '+ref);return raw;};
 const registry=JSON.parse(pin(CLOSURE_PATH,CLOSURE_SHA256));req(sameSet(Object.keys(registry),['schema_version','record_type','generated_at','baseline','sources','artifacts','transitions','retirements','original_findings','limits']),'registry keys');req(registry.schema_version==='1.0'&&registry.record_type==='HOST_CLOSURE_CORRECTION','registry type');req(equal(registry.baseline,{path:BASE,sha256:BASE_SHA}),'baseline substitution');
 const baseline=JSON.parse(pin(BASE,BASE_SHA)),old=index(baseline);const inventory=JSON.parse(pin(UI,UI_SHA));req(sameSet(inventory.accepted_ids,unchangedIds)&&sameSet(inventory.held_ids,unchangedHeld)&&inventory.candidates.length===26,'unchanged review inventory');for(const item of inventory.candidates)req(equal(item.original_claim,old.get(item.claim_id))&&sha(serial(item.original_claim))===item.original_claim_sha256,'unchanged review predecessor');for(const [ref,wanted]of Object.entries(inventory.customer_mdx_sha256))pin(ref,wanted);req(old.size===2013&&registry.transitions.length===ids.size&&sameSet(registry.transitions.map(x=>x.claim_id),ids),'transition inventory');req(registry.retirements.length===5&&sameSet(registry.retirements.map(x=>x.claim_id),retiredIds),'retirement inventory');const findings=new Map(registry.original_findings.map(x=>[x.claim_id,x]));req(registry.original_findings.length===26&&sameSet(findings.keys(),[...old].filter(([,c])=>c.status==='FAIL').map(([id])=>id)),'original finding inventory');req(sameSet([...findings].filter(([,f])=>f.disposition==='CORRECT_NOW').map(([id])=>id),[...corrected,...retiredIds]),'correction decision scope');
 const before=new Map(),current=new Map(),maps=new Map(),afterHashes=new Map();
 for(const source of registry.sources){const ref=source.path;req(ref.startsWith('host/')&&!before.has(ref),'source scope');req(source.before_artifact.path===(['host/glossary.mdx','host/maintenance-windows.mdx','host/hosting-agreement.mdx'].includes(ref)?A2:A)+'/sources-before/'+ref,'source snapshot path');before.set(ref,pin(source.before_artifact.path,source.before_artifact.sha256));current.set(ref,pin(ref,source.after_sha256));afterHashes.set(ref,sha(current.get(ref)));const oldLines=lines(before.get(ref)),newLines=lines(current.get(ref)),map=new Map(source.line_map);maps.set(ref,map);req(map.size===source.line_map.length&&new Set(map.values()).size===map.size,'duplicate line map');req(equal([...map.keys()],[...map.keys()].sort((a,b)=>a-b))&&equal([...map.values()],[...map.values()].sort((a,b)=>a-b)),'unordered line map');for(const [a,b]of map)req(a>0&&a<=oldLines.length&&b>0&&b<=newLines.length&&oldLines[a-1]===newLines[b-1],'source relocation drift');const oldChanged=new Set(),newChanged=new Set();for(const e of source.edits){for(let n=e.before_start;n<=e.before_end;n++)oldChanged.add(n);for(let n=e.after_start;n<=e.after_end;n++)newChanged.add(n);}req([...map.keys()].every(n=>!oldChanged.has(n))&&sameSet([...map.keys(),...oldChanged],oldLines.map((_,i)=>i+1)),'before line partition');req([...map.values()].every(n=>!newChanged.has(n))&&sameSet([...map.values(),...newChanged],newLines.map((_,i)=>i+1)),'after line partition');}
 const pre=projectPayoutInvoiceCorrection({read:ref=>before.has(ref)?before.get(ref):read(ref),exists});req(equal(pre.model,baseline),'complete sealed predecessor differs from frozen baseline');
 const artifacts=new Map(registry.artifacts.map(a=>[a.path,pin(a.path,a.sha256)]));req(artifacts.size===registry.artifacts.length,'duplicate artifact');
 const relocate=span=>{const map=maps.get(span.source_file);if(!map)return structuredClone(span);const values=[];for(let n=span.start;n<=span.end;n++)values.push(map.get(n));if(values.some((v,i)=>v===undefined||v!==values[0]+i))return null;return {...span,start:values[0],end:values.at(-1)};};
 const verifySpan=span=>{const raw=current.get(span.source_file)||read(span.source_file),source=lines(raw);req(span.start>0&&span.start<=span.end&&span.end<=source.length,'claim span bounds');const text=source.slice(span.start-1,span.end).join('\n');req(sha(text)===span.text_sha256,'claim span hash drift');return text;};
 const model=structuredClone(baseline),claims=index(model),entries=new Map(registry.transitions.map(e=>[e.claim_id,e]));
 for(const entry of registry.transitions){const id=entry.claim_id,prior=old.get(id),patch=entry.after;req(sha(serial(prior))===entry.before_sha256,'claim predecessor '+id);req(Object.keys(patch).every(k=>['text','spans','status','classification','required_evidence_types','owner_role','rationale','next_action','evidence_refs','source_refs','coverage_state'].includes(k)),'unsupported claim patch');if(unchangedIds.has(id))req(prior.status==='UNVALIDATED'&&patch.status==='PASS'&&!Object.hasOwn(patch,'spans')&&['text','classification','required_evidence_types','owner_role'].every(k=>equal(patch[k],prior[k])),'unchanged review scope');if(runtime.has(id))req(patch.text===prior.text&&patch.status===(id.startsWith('VOL-')?'UNVALIDATED':prior.status),'runtime promotion forbidden');for(const basis of entry.basis){req(artifacts.has(basis.artifactRef)&&selection(artifacts.get(basis.artifactRef),basis.text_pointer)===basis.excerpt,'source selector/excerpt drift '+id);req(basis.support_rationale&&patch.evidence_refs.some(e=>e.artifact_ref===basis.artifactRef),'unbound scoped evidence');if(unchangedIds.has(id))req(patch.source_refs.some(ref=>ref.path===(basis.sourceUrl||basis.artifactRef)&&ref.locator===basis.text_pointer),'unchanged review canonical binding');if(basis.text_pointer.startsWith('/observations/')){const observation=JSON.parse(artifacts.get(basis.artifactRef)).observations[Number(basis.text_pointer.split('/')[2])];if(observation?.url)req(basis.sourceUrl===observation.url&&patch.source_refs.some(ref=>ref.path===observation.url&&ref.locator===basis.text_pointer),'selected observation canonical URL drift '+id);}}Object.assign(claims.get(id),structuredClone(patch),{history:{...prior.history,carry_decision:'CURRENT_HOST_CLOSURE_CORRECTION',reason:(prior.history?.reason||'')+' '+entry.limits,predecessor:{claim_id:id,status:prior.status,text:prior.text,text_sha256:sha(prior.text)}}});}
 for(const retired of registry.retirements)req(retired.before_sha256===sha(serial(old.get(retired.claim_id)))&&retired.replaced_by==='MCL-0ae9c2fd5ac2ef9a','retirement predecessor');claims.get('MCL-0ae9c2fd5ac2ef9a').history.superseded_claims=registry.retirements.map(x=>({claim:structuredClone(old.get(x.claim_id)),reason:x.reason}));
 for(const page of model.pages){page.claims=page.claims.filter(c=>!retiredIds.has(c.id));if(afterHashes.has(page.source_file)){page.source_sha256=afterHashes.get(page.source_file);page.coverage_state='CHANGED';}for(const dep of page.dependencies)if(afterHashes.has(dep.source_file)){dep.source_sha256=afterHashes.get(dep.source_file);page.coverage_state='CHANGED';}for(const claim of page.claims){const id=claim.id;if(!Object.hasOwn(entries.get(id)?.after||{},'spans')){claim.spans=old.get(id).spans.map(relocate);req(!claim.spans.includes(null),'unreviewed changed occurrence '+id);}const literal=claim.spans.map(verifySpan).join('\n');if(claim.text!==old.get(id).text)req(literal===claim.text,'changed literal mismatch '+id);if(!ids.has(id))req(equal(Object.fromEntries(Object.entries(claim).filter(([k])=>k!=='spans')),Object.fromEntries(Object.entries(old.get(id)).filter(([k])=>k!=='spans'))),'unrelated claim drift '+id);}for(const procedure of page.procedures)for(const node of [procedure,...procedure.nodes]){const relocated=(node.spans||[]).map(relocate);if(relocated.includes(null)){node.spans=[];node.status='STALE';node.coverage_state='CHANGED';node.limits=[...(node.limits||[]),'Closure source changed; retained procedure evidence does not transfer to changed steps.'];node.history={...node.history,carry_decision:'CURRENT_HOST_CLOSURE_SOURCE_CHANGED'};}else node.spans=relocated;}}
 for(const item of model.source.source_manifest)if(afterHashes.has(item.path))item.sha256=afterHashes.get(item.path);const remaining=index(model);req(remaining.size===2008&&sameSet(remaining.keys(),[...old.keys()].filter(id=>!retiredIds.has(id))),'active inventory drift');for(const [id,f]of findings)if(f.disposition!=='CORRECT_NOW')req(equal(remaining.get(id),old.get(id)),'unresolved stronger assertion changed '+id);
 req(sameSet(remaining.keys(),Object.keys(inventory.all_current_claim_hashes))&&[...remaining].every(([id,c])=>unchangedIds.has(id)||sha(serial(c))===inventory.all_current_claim_hashes[id]),'unrelated current claim changed');req(sha(serial(model.pages.map(p=>p.procedures)))===inventory.procedures_sha256,'unchanged review procedure drift');req(equal(model.source.source_manifest,inventory.source_manifest),'unchanged review source manifest drift');const owners=JSON.parse(read('verification/current-host-owner-questions.json'));delete owners.model_sha256;req(sha(serial(owners))===inventory.owner_questions_without_model_hash_sha256,'unchanged review owner question drift');
 const count=values=>Object.fromEntries([...values.reduce((m,key)=>m.set(key,(m.get(key)||0)+1),new Map())].sort(([a],[b])=>a.localeCompare(b)));model.counts.claims=remaining.size;model.counts.claim_statuses=count([...remaining.values()].map(c=>c.status));model.counts.page_coverage_states=count(model.pages.map(p=>p.coverage_state));model.generated_at=registry.generated_at;model.corrections.push({id:MARKER,scope:'24 original findings handled: 19 narrowed corrections and 5 retired checklist clauses; 2 adjacent rental edits; 8 bounded evidence/status reconciliations; upstream PR948 and CON1531 routing; 24 unchanged source/declaration occurrences from a frozen 26-candidate inventory',history:'Complete sealed predecessor replayed against exact frozen source bytes. Five historical FAIL objects remain in the application instruction history and frozen baseline.',current:'Two tax FAIL assertions remain open. Nine original rental FAIL assertions are retained in history after withdrawal from active prose; backend and maintenance owner questions remain open. Partial runtime observations do not promote compound workflows.',reason:registry.limits});
 const presentation=new Map([...pre.presentation].filter(([id])=>remaining.has(id)));for(const entry of registry.transitions){const id=entry.claim_id,history=pre.presentation.has(id)?[structuredClone(pre.presentation.get(id))]:[];for(const retired of registry.retirements.filter(r=>r.replaced_by===id))history.push({previous:structuredClone(old.get(retired.claim_id)),method:'WITHDRAWN_UNSUPPORTED_CHECKLIST',reviewRationale:retired.reason,remaining:retired.reason,registryRef:CLOSURE_PATH,baselineRef:BASE,basis:[],auditHistory:pre.presentation.has(retired.claim_id)?[structuredClone(pre.presentation.get(retired.claim_id))]:[]});presentation.set(id,{previous:structuredClone(old.get(id)),method:entry.method,reviewRationale:remaining.get(id).rationale,remaining:entry.limits,registryRef:CLOSURE_PATH,baselineRef:BASE,basis:structuredClone(entry.basis),auditHistory:history,closure:true});}
 const artifactHashes=new Map([...pre.artifactHashes,[CLOSURE_PATH,CLOSURE_SHA256],[BASE,BASE_SHA],...afterHashes,...registry.sources.map(s=>[s.before_artifact.path,s.before_artifact.sha256]),...registry.artifacts.map(a=>[a.path,a.sha256])]);
 return {...pre,model,matches:new Map([...pre.matches].filter(([id])=>remaining.has(id)).map(([id,match])=>[id,{...match,claim:remaining.get(id)}])),presentation,artifactHashes,closure:{registry,registrySha256:CLOSURE_SHA256,baseline:BASE,baselineSha256:BASE_SHA,resultRef:U+'/result.md',retiredClaims:registry.retirements.map(r=>structuredClone(old.get(r.claim_id)))}};
}
export function loadClosureCorrection({read,model,exists}){const present=exists?exists(CLOSURE_PATH):(()=>{try{read(CLOSURE_PATH);return true;}catch{return false;}})(),marked=(model.corrections||[]).some(x=>x.id===MARKER);if(!present){req(!marked,'closure-marked model has no registry');return null;}const projected=projectClosureCorrection({read,exists});req(equal(projected.model,model),'whole model differs from closure projection');return projected;}
