import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {validateClarificationInput,loadClarificationTransition,clarificationHash,CLARIFICATION_PATH,CLARIFICATION_BASELINE_PATH,CLARIFICATION_MARKER} from './current_host_clarification.mjs';
import {mergeClarificationScan} from './current_host_authority_scan.mjs';
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'); const enc=x=>Buffer.from(JSON.stringify(x));
function fixture(){const claim={id:'C1',text:'Advice.',headings:['H'],spans:[],status:'UNVALIDATED',required_evidence_types:['RUNTIME_OR_UI_OBSERVATION'],owner_role:'Old',rationale:'Old',next_action:'Old',evidence_refs:[],source_refs:[],history:{},classification:'IMPLEMENTATION_OR_CONCEPT',coverage_state:'UNCHANGED_EXACT'};const node={id:'N1',next_action:'Old node',status:'UNVALIDATED'};const procedure={id:'P1',next_action:'Old procedure',status:'UNVALIDATED',nodes:[node]};const baseline={generated_at:'old',pages:[{claims:[claim],procedures:[procedure]}],corrections:[]};const entry={claim_id:'C1',before_sha256:clarificationHash(claim),review_method:'ADVICE_REVIEW',review_rationale:'Advice only.',after:{classification:'OPERATIONAL_ADVICE',required_evidence_types:['REPOSITORY_STATIC_CHECK'],owner_role:'Docs',rationale:'Advice.',next_action:'Review advice.'}};const registry={schema_version:'1.0',record_type:'HOST_REVIEW_CLARIFICATION_TRANSITION',generated_at:'now',baseline:{path:CLARIFICATION_BASELINE_PATH,sha256:''},claims:[entry],nodes:[{node_id:'N1',before_sha256:clarificationHash(node),next_action:'Review node.'}],procedures:[{procedure_id:'P1',before_sha256:clarificationHash(procedure),next_action:'Review procedure.'}]};const files=new Map([[CLARIFICATION_BASELINE_PATH,enc(baseline)]]);registry.baseline.sha256=hash(files.get(CLARIFICATION_BASELINE_PATH));files.set(CLARIFICATION_PATH,enc(registry));const model=structuredClone(baseline);Object.assign(model.pages[0].claims[0],entry.after);model.pages[0].procedures[0].next_action='Review procedure.';model.pages[0].procedures[0].nodes[0].next_action='Review node.';model.generated_at='now';model.corrections.push({id:CLARIFICATION_MARKER,scope:'Bounded clarification transition',history:'Frozen phase-43 predecessor is hash-pinned and validated before patch projection.',current:`1 exact claim review-method corrections; 1 node and 1 procedure next-action corrections; registry SHA-256 ${hash(files.get(CLARIFICATION_PATH))}.`,reason:'Review-method/action provenance only; no status, source, citation, evidence, span, or runtime-proof transition is authorized.'});return {files,baseline,registry,model,pins:{registry:hash(files.get(CLARIFICATION_PATH)),baseline:registry.baseline.sha256},read:r=>files.get(r)}}
function reseal(f,{baseline=false}={}){if(baseline){f.files.set(CLARIFICATION_BASELINE_PATH,enc(f.baseline));f.registry.baseline.sha256=hash(f.files.get(CLARIFICATION_BASELINE_PATH));f.pins.baseline=f.registry.baseline.sha256;f.registry.claims[0].before_sha256=clarificationHash(f.baseline.pages[0].claims[0]);f.registry.nodes[0].before_sha256=clarificationHash(f.baseline.pages[0].procedures[0].nodes[0]);f.registry.procedures[0].before_sha256=clarificationHash(f.baseline.pages[0].procedures[0])}f.files.set(CLARIFICATION_PATH,enc(f.registry));f.pins.registry=hash(f.files.get(CLARIFICATION_PATH));}
test('exact predecessor gate and projection are required',()=>{const f=fixture(),calls=[];const r=validateClarificationInput({...f,validatePredecessor:x=>{calls.push(x);return {presentation:new Map(),artifactHashes:new Map()}}});assert.equal(calls.length,1);assert.equal(r.matches.get('C1').claim.status,'UNVALIDATED');});
test('resealed unauthorized status, predecessor hash, and projection drift fail',()=>{for(const mutate of [f=>f.registry.claims[0].after.status='PASS',f=>f.registry.claims[0].before_sha256='0'.repeat(64),f=>f.model.pages[0].claims[0].status='PASS']){const f=fixture();mutate(f);f.files.set(CLARIFICATION_PATH,enc(f.registry));f.pins.registry=hash(f.files.get(CLARIFICATION_PATH));assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>({presentation:new Map(),artifactHashes:new Map()})}),/clarification transition/);}});
test('nonempty evidence lanes and protected PASS/FAIL/BLOCKED semantics fail closed',()=>{
  let f=fixture();f.registry.claims[0].after.required_evidence_types=[];reseal(f);assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>({})}),/invalid evidence enum/);
  f=fixture();f.baseline.pages[0].claims[0].status='PASS';reseal(f,{baseline:true});assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>({})}),/PASS\/N\/A/);
  f=fixture();f.baseline.pages[0].claims[0].status='FAIL';f.baseline.pages[0].claims[0].required_evidence_types=['AUTHORITATIVE_DOCUMENTATION_CITATION'];reseal(f,{baseline:true});assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>({})}),/citation lane/);
  f=fixture();f.baseline.pages[0].claims[0].status='BLOCKED';reseal(f,{baseline:true});assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>({})}),/BLOCKED prerequisite/);
});
test('source-gate failures, absent marked registry, and malformed next actions fail closed',()=>{
  let f=fixture();assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>{throw new Error('phase43 source drift')}}),/source drift/);
  f=fixture();delete f.registry.nodes[0].next_action;reseal(f);assert.throws(()=>validateClarificationInput({...f,validatePredecessor:()=>({})}),/invalid node transition/);
  f=fixture();assert.throws(()=>loadClarificationTransition({model:f.model,read:()=>undefined,exists:()=>false,validatePredecessor:()=>({})}),/missing registry/);
});
test('clarification overlays claim text without replacing authority source basis',()=>{const authority={matches:new Map([['C1',{claim:{id:'C1',rationale:'old'},page:{route:'/host/x'},previous:{id:'C1'},entry:{basis:['retained']},pageChanged:false}]]),presentation:new Map([['C1',{basis:[{excerpt:'retained source',sourceLabel:'Agreement'}]}]]),artifactHashes:new Map([['old', 'a']])};const clarification={matches:new Map([['C1',{claim:{id:'C1',rationale:'new'}}]]),entries:new Map([['C1',{review_method:'ADVICE_REVIEW'}]]),presentation:new Map([['C1',{method:'ADVICE_REVIEW'}]]),contextHashes:new Map([['clarification','b']])};const merged=mergeClarificationScan(authority,clarification),match=merged.matches.get('C1');assert.equal(match.claim.rationale,'new');assert.equal(match.page.route,'/host/x');assert.equal(match.entry.basis[0],'retained');assert.equal(merged.presentation.get('C1').basis[0].excerpt,'retained source');assert.equal(merged.presentation.get('C1').clarification.method,'ADVICE_REVIEW');});
