/** Finite retirement; historical proof is replayed before removing current scope. */
import crypto from 'node:crypto';
import {projectFinalOwnerReview} from './current_host_final_owner_review.mjs';
export const TAX_RETIREMENT_PATH='verification/current-host-tax-guide-retirement.json';
export const TAX_RETIREMENT_SHA256='616212169f6e8d9a1a3a0e35296e96da6e0ce04ea9c63b770dfceea2f663ce8f';
export const TAX_RETIREMENT_ATTEMPT='verification/evidence/2026-09-15-host-tax-guide-retirement-attempt-01';
const MARKER='HOST-TAX-GUIDE-RETIREMENT-01';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),canon=x=>Array.isArray(x)?x.map(canon):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canon(x[k])])):x,serial=x=>JSON.stringify(canon(x)),oh=x=>sha(serial(x)),equal=(a,b)=>serial(a)===serial(b),req=(x,m)=>{if(!x)throw Error('Tax Guide retirement: '+m);},lines=x=>x.toString().replace(/\n$/,'').split(/\r?\n/),omit=(x,keys)=>Object.fromEntries(Object.entries(x).filter(([k])=>!keys.includes(k)));
export function projectTaxGuideRetirement({read,exists}){
 const pin=(ref,wanted)=>{const raw=read(ref);req(sha(raw)===wanted,'digest drift '+ref);return raw;};
 const r=JSON.parse(pin(TAX_RETIREMENT_PATH,TAX_RETIREMENT_SHA256));req(r.record_type==='HOST_TAX_GUIDE_RETIREMENT','registry type');const before=new Map(),current=new Map();
 for(const s of r.sources){before.set(s.path,pin(s.before_artifact.path,s.before_artifact.sha256));if(s.removed){req(s.path==='host/guide-to-taxes.mdx'&&!(exists?exists(s.path):(()=>{try{read(s.path);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}})()),'removed source is still current');continue;}let text=before.get(s.path).toString();for(const e of s.edits){req(text.split(e.before).length===2,'edit occurrence');text=text.replace(e.before,e.after);}current.set(s.path,pin(s.path,s.after_sha256));req(current.get(s.path).toString()===text,'unaccepted source change');}
 before.set('verification/current-host-owner-questions.json',pin(r.before_owners.path,r.before_owners.sha256));
 const pre=projectFinalOwnerReview({read:ref=>before.get(ref)||read(ref),exists:ref=>before.has(ref)||(exists?exists(ref):(()=>{try{read(ref);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}})())}),baseline=pre.model;req(oh(baseline)===r.baseline_canonical_sha256,'whole predecessor drift');
 const archive=JSON.parse(pin(r.archive.path,r.archive.sha256)),owners=JSON.parse(pin(r.before_owners.path,r.before_owners.sha256)),instruction=JSON.parse(pin(r.instruction.path,r.instruction.sha256));req(instruction.comment.id==='34984'&&instruction.comment.body.includes('just remove this tax section entirely.'),'removal instruction');
 const old=new Map(baseline.pages.flatMap(p=>p.claims.map(c=>[c.id,c]))),retired=new Set(r.retired_claim_ids),page=baseline.pages.find(p=>p.route===r.retired_route);req(equal(archive.page,page)&&equal(archive.faq_claim,old.get('MCL-7b86589912c968bb')),'retired record drift');req(retired.size===16&&equal([...retired].sort(),[...page.claims.map(c=>c.id),'MCL-7b86589912c968bb'].sort()),'retired scope');req(equal(archive.owner_question,owners.questions.find(q=>q.id==='HQ-VAST-TAX-HANDLING'))&&equal(r.retired_owner_ids,['HQ-VAST-TAX-HANDLING']),'retired owner scope');
 const model=structuredClone(baseline);model.pages=model.pages.filter(p=>p.route!==r.retired_route);const patches=new Map(r.claims.map(c=>[c.id,c])),seen=new Set(),seenprocs=new Set();
 const verify=s=>{const source=lines(current.get(s.source_file)||read(s.source_file));req(s.start>0&&s.start<=s.end&&s.end<=source.length,'span bounds');const text=source.slice(s.start-1,s.end).join('\n');req(sha(text)===s.text_sha256,'span literal drift');return text;};
 for(const p of model.pages){p.claims=p.claims.filter(c=>!retired.has(c.id));if(current.has(p.source_file)){p.source_sha256=sha(current.get(p.source_file));p.coverage_state='CHANGED';}for(const[i,prior]of p.claims.entries()){let c=prior;if(patches.has(c.id)){const patch=patches.get(c.id);req(oh(c)===patch.before_sha256,'claim before drift');const next=structuredClone(patch.after),changed=patch.text_changed,allowed=changed?['spans','text','history']:['spans'];req(equal(omit(c,allowed),omit(next,allowed)),'unaccepted claim fields');if(changed)req(['MCL-e9c7af0148732c9b','MCL-335de916e219e04a'].includes(c.id)&&Object.entries(c.history||{}).every(([k,v])=>equal(next.history[k],v)),'referral history');p.claims[i]=next;c=next;seen.add(c.id);}c.spans.forEach(verify);}
  for(const[pi,proc]of p.procedures.entries())for(const[ni,node]of [proc,...proc.nodes].entries()){const entry=r.procedures.find(e=>e.route===p.route&&e.procedure_index===pi&&e.node_index===(ni===0?null:ni-1));if(entry){req(oh(omit(node,['nodes']))===entry.before_sha256&&node.id===entry.id,'procedure before drift');const oldtext=node.spans.map(s=>lines(before.get(s.source_file)||read(s.source_file)).slice(s.start-1,s.end).join('\n')).join('\n'),newtext=entry.spans.map(verify).join('\n'),fences=t=>[...t.matchAll(/^```[^\n]*\n.*?^```/gms)].map(m=>m[0]);req(entry.fences_unchanged&&equal(fences(oldtext),fences(newtext)),'command fence changed');node.spans=structuredClone(entry.spans);seenprocs.add(`${p.route}/${pi}/${ni}`);}node.spans.forEach(verify);}
 }
 req(equal([...seen].sort(),[...patches.keys()].sort())&&seenprocs.size===r.procedures.length,'patch scope');model.source.source_manifest=model.source.source_manifest.filter(s=>s.path!=='host/guide-to-taxes.mdx');for(const s of model.source.source_manifest)if(current.has(s.path))s.sha256=sha(current.get(s.path));model.source.primary_route_count=43;
 const count=xs=>Object.fromEntries([...xs.reduce((m,k)=>m.set(k,(m.get(k)||0)+1),new Map())].sort(([a],[b])=>a.localeCompare(b)));Object.assign(model.counts,{primary_pages:43,total_host_routes:43,total_reviewed_layers:76,claims:1992,procedures:114,procedure_nodes:1071});model.counts.claim_statuses=count(model.pages.flatMap(p=>p.claims.map(c=>c.status)));model.counts.page_coverage_states=count(model.pages.map(p=>p.coverage_state));req(equal(model.counts.claim_statuses,{NOT_APPLICABLE:94,PASS:1898}),'retirement accounting');
 model.generated_at=r.generated_at;model.corrections.push({id:MARKER,scope:'Tax Guide page and its FAQ referral retired; two payout referrals narrowed.',history:'All 16 retired passages, two procedures, 14 nodes and the tax owner question remain in the immutable retirement archive and predecessor evidence.',current:'43 pages and 1,992 current passages. Tax guidance and its current owner follow-up are removed; zero new validation credit.',reason:r.limits});
 const artifactHashes=new Map(pre.artifactHashes);artifactHashes.delete('host/guide-to-taxes.mdx');artifactHashes.delete('verification/current-host-owner-questions.json');for(const[path,raw]of current)artifactHashes.set(path,sha(raw));artifactHashes.set(TAX_RETIREMENT_PATH,TAX_RETIREMENT_SHA256);for(const a of [r.archive,r.before_owners,r.instruction,...r.sources.map(s=>s.before_artifact)])artifactHashes.set(a.path,a.sha256);
 const active=new Map(model.pages.flatMap(p=>p.claims.map(c=>[c.id,c]))),presentation=new Map([...pre.presentation].filter(([id])=>active.has(id)));for(const entry of r.claims)if(entry.text_changed&&presentation.has(entry.id)){const p=presentation.get(entry.id);presentation.set(entry.id,{...p,retirementNote:'Tax Guide referral removed; prior source evidence applies only to the retained wording.'});}
 return {...pre,model,presentation,matches:new Map([...pre.matches].filter(([id])=>active.has(id)).map(([id,m])=>[id,{...m,claim:active.get(id)}])),artifactHashes,taxRetirement:{registry:r,registrySha256:TAX_RETIREMENT_SHA256,resultRef:TAX_RETIREMENT_ATTEMPT+'/result.md',archive,instruction}};
}
export function loadTaxGuideRetirement({read,model,exists}){const present=exists?exists(TAX_RETIREMENT_PATH):(()=>{try{read(TAX_RETIREMENT_PATH);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}})();if(!present){req(!(model.corrections||[]).some(x=>x.id===MARKER),'retirement registry missing');return null;}const out=projectTaxGuideRetirement({read,exists});req(equal(out.model,model),'whole model differs from retirement projection');return out;}
