/** Phase-47 Workload Policy Terms binding.  Published Terms proof is bounded;
 * registries/models are transition context, never product proof. */
import crypto from 'node:crypto';
import { loadAuthorityScan } from './current_host_authority_scan.mjs';
export const TERMS_PATH='verification/current-host-terms-binding.json';
export const TERMS_REGISTRY_SHA256='36961fcabe5fbd105a67c37ef8918e17e98c78351008f108224114abde77ac38';
export const TERMS_ATTEMPT='verification/evidence/2026-09-10-host-terms-binding-attempt-01';
export const TERMS_BASELINE_PATH=`${TERMS_ATTEMPT}/before-review.json`;
export const TERMS_BASELINE_SHA256='f4df32dc9fc85a0b31f578cc8481d0305cc7af9d530e110013769ce2ac6cce2b';
export const TERMS_SOURCE='host/workload-policy.mdx', TERMS_MARKER='HOST-TERMS-BINDING-01';
const IDS=new Set(['MCL-99ca28f707d5966a','MCL-2c3f7082e2c7fdf2','MCL-c4c4bfc59eb7b49f','MCL-399798a3c4946b5f','MCL-633317ca7ebecfef','MCL-fe3eccd1cd40b4bd']);
const AFTER=new Set(['classification','status','required_evidence_types','owner_role','rationale','next_action','text','headings','spans','evidence_refs','source_refs']);
const LANES=new Set(['CANONICAL_IMPLEMENTATION_SOURCE','RUNTIME_OR_UI_OBSERVATION','ACCOUNTABLE_OWNER_CONFIRMATION','AUTHORITATIVE_DOCUMENTATION_CITATION','REPOSITORY_STATIC_CHECK','PRODUCT_PUBLICATION_SOURCE']);
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'), fail=x=>{throw Error('terms binding: '+x)}, req=(x,m)=>{if(!x)fail(m)};
const canon=x=>Array.isArray(x)?x.map(canon):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canon(x[k])])):x;
const objhash=x=>hash(JSON.stringify(canon(x))), equal=(a,b)=>JSON.stringify(canon(a))===JSON.stringify(canon(b));
const difference=(left,right,at='$')=>{if(typeof left!==typeof right||left===null||right===null)return at;if(Array.isArray(left)||Array.isArray(right)){if(!Array.isArray(left)||!Array.isArray(right)||left.length!==right.length)return at;for(let i=0;i<left.length;i++){const hit=difference(left[i],right[i],`${at}[${i}]`);if(hit)return hit}return null}if(typeof left==='object'){const names=[...new Set([...Object.keys(left),...Object.keys(right)])].sort();for(const name of names){if(!Object.hasOwn(left,name)||!Object.hasOwn(right,name))return `${at}.${name}`;const hit=difference(left[name],right[name],`${at}.${name}`);if(hit)return hit}return null}return left===right?null:at};
const keys=(x,r,o=[],n='record')=>req(x&&typeof x==='object'&&!Array.isArray(x)&&r.every(k=>Object.hasOwn(x,k))&&Object.keys(x).every(k=>r.includes(k)||o.includes(k)),`invalid ${n} fields`);
const text=(x,n)=>{req(typeof x==='string'&&x.trim(),`missing ${n}`);return x};
const index=model=>{const claims=new Map(),nodes=new Map();for(const page of model.pages)for(const procedure of page.procedures){for(const node of [procedure,...procedure.nodes])nodes.set(node.id,node);for(const claim of page.claims)claims.set(claim.id,claim)}return {claims,nodes}};
const mapLines=(a,b)=>{req(a.length===b.length,'Terms source edit must preserve line count');return new Map(a.flatMap((line,index)=>line===b[index]?[[index+1,index+1]]:[]))};
const relocate=(span,map,lines)=>{const values=[];for(let n=span.start;n<=span.end;n++)values.push(map.get(n));if(values.includes(undefined)||values.some((n,i)=>i&&n!==values[i-1]+1))return null;const result={...span,start:values[0],end:values.at(-1)};req(hash(Buffer.from(lines.slice(result.start-1,result.end).join('\n')))==result.text_sha256,'relocated span drift');return result};
const pointer=(artifact,ref)=>{req(/^\/sections\/[01]\/(?:text|items\/[0-8]\/text)$/.test(ref),'invalid Terms pointer');let v=JSON.parse(artifact.bytes),parent;for(const p of ref.slice(1).split('/')){parent=v;v=Array.isArray(v)?v[Number(p)]:v?.[p]}req(typeof v==='string'&&v.trim()&&(!parent?.text_sha256||parent.text_sha256===hash(Buffer.from(v))),'Terms pointer/hash drift');return v};
const displayTermsBasis=(binding,artifact)=>{const capture=JSON.parse(artifact.bytes),parts=binding.text_pointer.split('/').filter(Boolean),section=capture.sections[Number(parts[1])],heading=section.heading.toLowerCase().replace(/\b\w/g,x=>x.toUpperCase()),item=parts[2]==='items'?section.items[Number(parts[3])].item:null;return {...binding,artifactRef:artifact.path,kind:artifact.kind,origin:artifact.origin,sourceLabel:'Terms of Service',sourceLocator:`${heading}${item?`, item ${item}`:''} — Version Date: November 10, 2025`,sourceUrl:'https://vast.ai/terms'}};
export function loadTermsBinding({read,model,exists}){
 const present=exists?exists(TERMS_PATH):(()=>{try{read(TERMS_PATH);return true}catch{return false}})(),marked=(model.corrections||[]).some(x=>x.id===TERMS_MARKER);if(!present){req(!marked,'missing Terms registry');return null}
 const rb=read(TERMS_PATH);req(hash(rb)===TERMS_REGISTRY_SHA256,'Terms registry drift');const r=JSON.parse(rb);keys(r,['schema_version','record_type','generated_at','baseline','source','artifacts','transitions'],[],'registry');req(r.schema_version==='1.0'&&r.record_type==='HOST_TERMS_BINDING_TRANSITION','wrong registry type');req(equal(r.baseline,{path:TERMS_BASELINE_PATH,sha256:TERMS_BASELINE_SHA256}),'baseline substitution');keys(r.source,['path','before_sha256','after_sha256','before_artifact'],[],'source');req(r.source.path===TERMS_SOURCE,'out-of-scope source');keys(r.source.before_artifact,['path','sha256'],[],'before source');const old=read(r.source.before_artifact.path);req(hash(old)===r.source.before_artifact.sha256&&hash(old)===r.source.before_sha256,'old source drift');const after=read(TERMS_SOURCE);req(hash(after)===r.source.after_sha256,'current source drift');const baselineBytes=read(TERMS_BASELINE_PATH);req(hash(baselineBytes)===TERMS_BASELINE_SHA256,'baseline drift');const baseline=JSON.parse(baselineBytes);
 const overlay=ref=>ref===TERMS_SOURCE?old:read(ref);const predecessor=loadAuthorityScan({read:overlay,model:baseline,exists});req(predecessor?.clarification,'Terms predecessor must retain the sealed clarification transition');const clarification=predecessor.clarification;
 const artifacts=new Map();for(const a of r.artifacts){keys(a,['id','path','sha256','kind','origin'],[],'artifact');req(a.kind==='GOVERNING_SOURCE'&&equal(a.origin,{url:'https://vast.ai/terms'})&&!a.path.startsWith('verification/current-'),'invalid Terms artifact');const bytes=read(a.path),capture=JSON.parse(bytes);req(capture.url==='https://vast.ai/terms'&&capture.version==='Version Date: November 10, 2025'&&capture.response_status===200&&hash(bytes)===a.sha256&&!artifacts.has(a.id),'Terms artifact drift');artifacts.set(a.id,{...a,bytes})}req(artifacts.size,'Terms source artifact required');
 const expected=structuredClone(baseline),before=index(baseline),out=index(expected),seen=new Set(),oldLines=old.toString().split(/\r?\n/),newLines=after.toString().split(/\r?\n/),map=mapLines(oldLines,newLines),presentation=new Map(predecessor.presentation);
 for(const e of r.transitions){keys(e,['claim_id','before_sha256','after','basis','review_rationale'],[],'claim');req(IDS.has(e.claim_id)&&!seen.has(e.claim_id)&&e.before_sha256===objhash(before.claims.get(e.claim_id)),'claim ID/predecessor drift');req(e.after&&typeof e.after==='object'&&Object.hasOwn(e.after,'spans')&&Object.keys(e.after).every(k=>AFTER.has(k))&&Array.isArray(e.basis)&&e.basis.length,'invalid Terms claim');const prior=before.claims.get(e.claim_id),c=out.claims.get(e.claim_id);Object.assign(c,structuredClone(e.after));req(['PASS','FAIL','UNVALIDATED'].includes(c.status)&&Array.isArray(c.required_evidence_types)&&c.required_evidence_types.every(l=>LANES.has(l)),'invalid Terms status/lanes');req(c.text===c.spans.map(s=>newLines.slice(s.start-1,s.end).join('\n')).join('\n'),'Terms claim span drift');for(const s of c.spans)req(s&&s.source_file===TERMS_SOURCE&&Number.isInteger(s.start)&&Number.isInteger(s.end)&&s.start>0&&s.end>=s.start&&s.end<=newLines.length&&hash(Buffer.from(newLines.slice(s.start-1,s.end).join('\n')))===s.text_sha256,'Terms claim span provenance drift');for(const b of e.basis){keys(b,['artifact_id','lane','text_pointer','excerpt','support_rationale'],[],'basis');const a=artifacts.get(b.artifact_id);req(a&&b.lane==='AUTHORITATIVE_DOCUMENTATION_CITATION'&&text(b.excerpt,'excerpt')&&pointer(a,b.text_pointer).includes(b.excerpt),'invalid Terms basis')}req((prior.evidence_refs||[]).every(ref=>c.evidence_refs?.some(x=>equal(x,ref)))&&(prior.source_refs||[]).every(ref=>c.source_refs?.some(x=>equal(x,ref)))&&c.evidence_refs?.some(ref=>[...artifacts.values()].some(a=>a.path===ref.artifact_ref))&&c.source_refs?.some(ref=>ref.path==='https://vast.ai/terms'&&ref.source_kind==='AUTHORITATIVE_DOCUMENTATION_CITATION'),'Terms transition dropped retained source/evidence');req(c.status!=='PASS'||equal(c.required_evidence_types,['AUTHORITATIVE_DOCUMENTATION_CITATION']),'Terms PASS must be narrow citation');c.history={...prior.history,carry_decision:'CURRENT_HOST_TERMS_BINDING',reason:`${prior.history.reason||''} Exact published Terms binding; no runtime, monitoring, escalation, or acceptance inference.`};c.coverage_state='CHANGED';const earlier=presentation.get(e.claim_id)||{};presentation.set(e.claim_id,{...earlier,previous:structuredClone(prior),method:'PUBLISHED_TERMS_RULE',reviewRationale:e.review_rationale,remaining:c.next_action,registryRef:TERMS_PATH,baselineRef:TERMS_BASELINE_PATH,basis:[...(earlier.basis||[]),...e.basis.map(b=>displayTermsBasis(b,artifacts.get(b.artifact_id)))],terms:{reviewRationale:e.review_rationale,remaining:c.next_action}});seen.add(e.claim_id)}req(seen.size===IDS.size&&[...IDS].every(id=>seen.has(id)),'six Terms claims required');
 for(const page of expected.pages)if(page.source_file===TERMS_SOURCE){page.source_sha256=hash(after);page.coverage_state='CHANGED';for(const c of page.claims)if(!seen.has(c.id)){const spans=before.claims.get(c.id).spans.map(s=>relocate(s,map,newLines));req(!spans.includes(null),'unpatched changed claim');if(!equal(spans,c.spans)){c.spans=spans;c.coverage_state='CHANGED';c.history={...before.claims.get(c.id).history,carry_decision:'CURRENT_HOST_TERMS_BINDING_RELOCATION'}}}for(const p of page.procedures)for(const n of [p,...p.nodes]){const spans=n.spans.map(s=>relocate(s,map,newLines));if(spans.includes(null)){n.spans=[];n.status='STALE';n.coverage_state='CHANGED';n.limits=[...n.limits,'Previous procedure span crosses the Terms-bound Workload Policy edit; no procedure evidence transfers.'];n.history={...n.history,carry_decision:'CURRENT_HOST_TERMS_BINDING_SOURCE_CHANGED'};}else if(!equal(spans,n.spans)){n.spans=spans;n.coverage_state='CHANGED';n.history={...n.history,carry_decision:'CURRENT_HOST_TERMS_BINDING_RELOCATION'}}}}
 const covered=new Set();for(const c of out.claims.values())for(const s of c.spans)if(s.source_file===TERMS_SOURCE)for(let line=s.start;line<=s.end;line++)covered.add(line);for(let index=0;index<newLines.length;index++)if(oldLines[index]!==newLines[index]){const line=newLines[index].trim(),structural=!line||line==='---'||line.startsWith('#')||line.startsWith('| ---')||line.startsWith('| Category |');req(structural||covered.has(index+1),'changed nonblank Workload Policy source line lacks a claim occurrence')}
 for(const item of expected.source.source_manifest)if(item.path===TERMS_SOURCE)item.sha256=hash(after);expected.counts.claim_statuses={};for(const c of out.claims.values())expected.counts.claim_statuses[c.status]=(expected.counts.claim_statuses[c.status]||0)+1;expected.generated_at=r.generated_at;expected.corrections.push({id:TERMS_MARKER,scope:'Six Workload Policy Terms bindings after frozen clarification',history:'Phase-43 authority and phase-46 clarification predecessors remain hash-pinned and are validated against the exact frozen Workload Policy bytes.',current:`6 exact Terms claim bindings; one source SHA-256 transition ${r.source.before_sha256} → ${r.source.after_sha256}.`,reason:'Published-rule citations are bounded policy source proof only; no runtime, monitoring, escalation, acceptance, or whole-page inference is authorized.'});req(equal(model,expected),`whole model differs from Terms projection at ${difference(model,expected)}`);const matches=new Map([...predecessor.matches].map(([id,match])=>[id,{...match,claim:out.claims.get(id),terms:IDS.has(id)?r.transitions.find(x=>x.claim_id===id):null}]));return {...predecessor,clarification,terms:{registry:r,registrySha256:hash(rb),artifacts,baseline:TERMS_BASELINE_PATH,baselineSha256:TERMS_BASELINE_SHA256,source:r.source},presentation,matches,artifactHashes:new Map([...predecessor.artifactHashes,[TERMS_SOURCE,hash(after)],[r.source.before_artifact.path,r.source.before_artifact.sha256],[TERMS_PATH,TERMS_REGISTRY_SHA256],[TERMS_BASELINE_PATH,TERMS_BASELINE_SHA256],...[...artifacts.values()].map(a=>[a.path,a.sha256])])};
}
