#!/usr/bin/env python3
"""Two sealed payout-publication corrections above the UI-provider projection."""
from __future__ import annotations
import copy, hashlib, importlib.util, json
from collections import Counter
from pathlib import Path
from typing import Any

REGISTRY='verification/current-host-payout-terms-correction.json'; REGISTRY_SHA256='de0274c91499680f7dabc974fecdd7ea004bf20fc88a8dfa1456727e903990dc'
ATTEMPT='verification/evidence/2026-09-14-payout-terms-correction-attempt-01'; BASELINE=ATTEMPT+'/pre-correction-model.json'; BASELINE_SHA256='39fe1128ebb56c2135b79fe1eeca9c5497056ed95dc517dbb7df203f9617a0dd'; BEFORE=ATTEMPT+'/pre-correction-payment.mdx'; BEFORE_SHA256='95e6585980cb936f72c657a0ef508abf917361b210faa8b86b4b5af5896ad0a9'; TERMS=ATTEMPT+'/terms-source-02.json'; TERMS_SHA256='f64399871ecdbad036b959e32613fc43ba2aa859d5b578552016b720e1487c4e'; FAQ=ATTEMPT+'/published-payout-faq-01.json'; FAQ_SHA256='b618d620ad6e263159e924f20148faee38c5887087de7c369075bb52ce159bfd'; SOURCE='host/payment.mdx'; MARKER='HOST-PAYOUT-TERMS-CORRECTION-01'
TERMS_ID='MCL-06956d724f70d2a3'; FAQ_ID='MCL-9826b26393329d27'; CHANGED={46,98,99,101}
TERMS_TEXT="The [Terms of Use, Disclaimer of Website](https://vast.ai/terms) include disclaimers for third-party products or services offered through the website. The [Miscellaneous section](https://vast.ai/terms) limits responsibility for delays or failures caused by circumstances beyond Vast's reasonable control. The [Limitations of Liability section](https://vast.ai/terms) notes that some exclusions may not apply under certain state laws."
FAQ_TEXT="[Vast's published payout guidance](https://docs.vast.ai/host/payment#can-vast-ai-send-my-payout-via-direct-bank-transfer-ach-swift-wire-transfer-etc-) says direct bank transfers, including ACH, wire and SWIFT, are unavailable."
FAQ_URL='https://docs.vast.ai/host/payment#can-vast-ai-send-my-payout-via-direct-bank-transfer-ach-swift-wire-transfer-etc-'; LIMIT_TERMS='Published Terms text only; no ruling on a particular payout, provider, enforceability, or Hosting Agreement priority.'; LIMIT_FAQ='Published payout guidance only; not independent backend/runtime absence, transfer completion, provider fees, or a specific account entitlement.'
def sha(v:bytes)->str:return hashlib.sha256(v).hexdigest()
def canon(v:Any)->str:return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False)
def fail(m):raise ValueError('payout Terms correction: '+m)
def req(v,m):
 if not v:fail(m)
def safe(root:Path,ref:str)->Path:
 req(isinstance(ref,str) and ref and not ref.startswith('/') and '\\' not in ref and all(part not in {'','.','..'} for part in ref.split('/')),'unsafe path')
 path=root.resolve()
 for part in ref.split('/'):
  path/=part;req(not path.is_symlink(),'unsafe symlink')
 req(path.is_file() and path.resolve().is_relative_to(root.resolve()),'missing path '+ref)
 return path
def pin(root,ref,want):
 value=safe(root,ref).read_bytes();req(sha(value)==want,'digest drift '+ref);return value
def mod(name):
 spec=importlib.util.spec_from_file_location(name,Path(__file__).with_name(name+'.py'));module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);return module
def span(lines,line):return {'source_file':SOURCE,'start':line,'end':line,'text_sha256':sha(lines[line-1].encode())}
def predecessor(root,baseline,before):
 provider=mod('current_host_payout_provider_correction');original=provider.pinned
 def frozen(repo,ref,wanted):return before if ref==provider.SOURCE and sha(before)==wanted else original(repo,ref,wanted)
 provider.pinned=frozen
 try:provider.validate_model(baseline,root)
 finally:provider.pinned=original
def project(root:Path)->dict:
 root=root.resolve();registry=json.loads(pin(root,REGISTRY,REGISTRY_SHA256));req(set(registry)=={'schema_version','record_type','generated_at','baseline','source','terms','faq','transitions'},'registry keys');req(registry['schema_version']=='1.0' and registry['record_type']=='HOST_PAYOUT_TERMS_CORRECTION','registry type');req(registry['baseline']=={'path':BASELINE,'sha256':BASELINE_SHA256},'baseline');req(registry['source']=={'path':SOURCE,'before_artifact':{'path':BEFORE,'sha256':BEFORE_SHA256},'before_sha256':BEFORE_SHA256,'after_sha256':registry['source']['after_sha256'],'changed_lines':sorted(CHANGED)},'source');req(registry['terms']=={'path':TERMS,'sha256':TERMS_SHA256},'terms source');req(registry['faq']=={'path':FAQ,'sha256':FAQ_SHA256},'FAQ source')
 before=pin(root,BEFORE,BEFORE_SHA256);after=pin(root,SOURCE,registry['source']['after_sha256']);old_lines,new_lines=before.decode().splitlines(),after.decode().splitlines();req(len(old_lines)==len(new_lines) and {i+1 for i,(old,new) in enumerate(zip(old_lines,new_lines)) if old!=new}==CHANGED and new_lines[45]==TERMS_TEXT and new_lines[97]=='<span id="direct-bank-transfer" aria-hidden="true" /><span id="how-do-i-set-up-payouts" aria-hidden="true" />' and new_lines[98]=='### Can Vast send direct bank transfers?' and new_lines[100]==FAQ_TEXT,'source wording')
 terms=json.loads(pin(root,TERMS,TERMS_SHA256));req(terms.get('version')=='Version Date: September 1, 2026' and terms.get('url')=='https://vast.ai/terms' and [section.get('heading') for section in terms.get('sections',[])]==['DISCLAIMER OF WEBSITE','LIMITATIONS OF LIABILITY','MISCELLANEOUS'],'Terms capture');sections=terms['sections'];req('PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY' in sections[0]['text'] and "delay or failure to act caused by any cause beyond Company's reasonable control" in sections[2]['text'] and 'SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU' in sections[1]['text'],'Terms excerpts')
 faq=json.loads(pin(root,FAQ,FAQ_SHA256));req(set(faq)=={'recorded_at','method','heading','heading_id','suggest_edits','text','title','url','text_sha256','limitations'},'FAQ capture keys');req(faq['recorded_at']=='2026-09-14T15:09:07.325Z' and faq['method']=='Unauthenticated public browser navigation and exact FAQ DOM extraction' and faq['heading_id']=='can-vast-ai-send-my-payout-via-direct-bank-transfer-ach-swift-wire-transfer-etc-' and faq['url']=='https://docs.vast.ai/host/payment' and faq['text_sha256']==sha(faq['text'].encode()) and all(item in faq['text'] for item in ['No.','Wise','PayPal','Stripe','Direct bank transfers, ACH payments, wire transfers, and SWIFT payments are not available.']),'FAQ capture')
 base=json.loads(pin(root,BASELINE,BASELINE_SHA256));predecessor(root,base,before);old={claim['id']:claim for page in base['pages'] for claim in page['claims']};req(len(old)==2013 and TERMS_ID in old and FAQ_ID in old,'baseline claim inventory');expected={TERMS_ID:'88ffda2451249d1f0f5d8bec981444c501449a0607d408e4f63cc2dc5e0336b9',FAQ_ID:'e871fbbb737d3f55efa220e254f16ce986709b908a414d29cb0aca6f8538757a'};req(isinstance(registry['transitions'],list) and {item.get('claim_id'):item.get('before_sha256') for item in registry['transitions']}==expected and all(sha(canon(old[key]).encode())==value for key,value in expected.items()),'claim predecessor')
 out=copy.deepcopy(base);claims={claim['id']:claim for page in out['pages'] for claim in page['claims']};terms_prior,faq_prior=old[TERMS_ID],old[FAQ_ID];terms_evidence=[{'id':'EV-PAYOUT-TERMS-02-'+str(index),'role':'PUBLISHED_TERMS_SECTION','limit':LIMIT_TERMS,'artifact_ref':TERMS} for index in (0,2,1)]
 claims[TERMS_ID].update({'text':TERMS_TEXT,'headings':['Payout Account'],'spans':[span(new_lines,46)],'status':'PASS','classification':'PUBLISHED_TERMS_SUMMARY','required_evidence_types':['AUTHORITATIVE_DOCUMENTATION_CITATION'],'owner_role':'Documentation authoritative-source reviewer','rationale':'Three named published Terms sections are summarized within their stated scope; the former payout/provider-specific exclusion was withdrawn.','next_action':'Recheck the cited Terms sections if the published Terms version changes.','evidence_refs':terms_evidence,'source_refs':[{'repository':'official-publication','revision':'sha256:'+TERMS_SHA256,'path':'https://vast.ai/terms','locator':'/sections/'+str(index)+'/text','source_kind':'AUTHORITATIVE_DOCUMENTATION_CITATION'} for index in (0,2,1)],'coverage_state':'CHANGED','history':{**terms_prior['history'],'carry_decision':'CURRENT_HOST_PAYOUT_TERMS_CORRECTION','reason':terms_prior['history'].get('reason','')+' Exact published-Terms summary; the withdrawn universal payout exclusion is not proven.','predecessor':{'claim_id':TERMS_ID,'status':terms_prior['status'],'text':terms_prior['text'],'text_sha256':sha(terms_prior['text'].encode())}}})
 claims[FAQ_ID].update({'text':FAQ_TEXT,'headings':['Can Vast send direct bank transfers?'],'spans':[span(new_lines,101)],'status':'PASS','classification':'PUBLICATION_DESCRIPTION','required_evidence_types':['AUTHORITATIVE_DOCUMENTATION_CITATION'],'owner_role':'Documentation authoritative-source reviewer','rationale':'The captured published payout FAQ supports this attributed route-availability description only; it is not independent product or runtime absence evidence.','next_action':'Recheck this exact published FAQ wording if the payout guidance or anchor changes.','evidence_refs':[{'id':'EV-PAYOUT-FAQ-01','role':'PUBLISHED_PAYOUT_GUIDANCE','limit':LIMIT_FAQ,'artifact_ref':FAQ}],'source_refs':[{'repository':'official-publication','revision':'sha256:'+FAQ_SHA256,'path':FAQ_URL,'locator':'/text','source_kind':'AUTHORITATIVE_DOCUMENTATION_CITATION'}],'coverage_state':'CHANGED','history':{**faq_prior['history'],'carry_decision':'CURRENT_HOST_PAYOUT_TERMS_CORRECTION','reason':faq_prior['history'].get('reason','')+' Exact attributed published payout guidance replaces the prior UI-only setup instruction; it is not independent transfer-availability proof.','predecessor':{'claim_id':FAQ_ID,'status':faq_prior['status'],'text':faq_prior['text'],'text_sha256':sha(faq_prior['text'].encode())}}})
 page=next(page for page in out['pages'] if page['source_file']==SOURCE);page['source_sha256']=sha(after);page['coverage_state']='CHANGED';req(all(claim['id'] in {TERMS_ID,FAQ_ID} or not any(item['start']<=line<=item['end'] for item in claim['spans'] for line in CHANGED) for claim in page['claims']),'unrelated changed claim')
 for procedure in page['procedures']:
  for node in [procedure,*procedure['nodes']]:
   if any(item['start']<=line<=item['end'] for item in node.get('spans',[]) for line in CHANGED):node['spans']=[];node['status']='STALE';node['coverage_state']='CHANGED';node['limits']=[*node.get('limits',[]),'Payout Terms source span changed; no procedure evidence transfers.'];node['history']={**node.get('history',{}),'carry_decision':'CURRENT_HOST_PAYOUT_TERMS_CORRECTION_SOURCE_CHANGED'}
 for item in out['source']['source_manifest']:
  if item['path']==SOURCE:item['sha256']=sha(after)
 req(sum(old[key]==claims[key] for key in old)==2011,'unrelated claim drift');out['counts']['claim_statuses']=dict(sorted(Counter(claim['status'] for claim in claims.values()).items()));out['generated_at']=registry['generated_at'];out['corrections'].append({'id':MARKER,'scope':'One Terms summary and one attributed direct-bank-transfer FAQ description','history':'Payout-provider predecessor and source are pinned.','current':'One Terms-backed summary and one attributed published payout FAQ description.','reason':'No payout/provider adjudication, enforceability decision, Hosting Agreement priority, or independent backend/runtime absence is inferred.'});return out
def validate_model(model,root):req(model==project(root),'whole model differs from payout Terms projection')
