/** Sealed published-guidance correction above the payout-Terms projection. */
import crypto from 'node:crypto';
import { projectPayoutTermsCorrection } from './current_host_payout_terms_correction.mjs';
export const PAYOUT_INVOICE_PATH='verification/current-host-payout-invoice-correction.json';
export const PAYOUT_INVOICE_SHA256='e956e3c121459722e024217eb371848d06c4e1252ef43f6ea8d895568bd7a7d6';
const A='verification/evidence/2026-09-14-payout-invoice-correction-attempt-01',BASE=A+'/pre-correction-model.json',BEFORE=A+'/pre-correction-payment.mdx',GUIDANCE=A+'/published-invoice-guidance-01.json',SOURCE='host/payment.mdx',MARKER='HOST-PAYOUT-INVOICE-CORRECTION-01';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),canon=x=>Array.isArray(x)?x.map(canon):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canon(x[k])])):x,equal=(a,b)=>JSON.stringify(canon(a))===JSON.stringify(canon(b)),req=(v,m)=>{if(!v)throw Error('payout invoice correction: '+m);};
const changed=new Set([53,54,55,58,84,106]),ids=new Map([['MCL-e2b956d14494e470',[53,'minimum-payout-threshold']],['MCL-df7b287adb0df683',[54,'invoice-generation']],['MCL-3d796f5ae7f2020e',[55,'payment-timeline']],['MCL-5936430d1b2d8de9',[58,'minimum-payout-threshold']],['MCL-3afd93ae0b6cf8a4',[84,'payment-timeline']],['MCL-bbd64c772e9b4693',[106,'invoice-generation']]]),limit='Published guidance checked. This checks what Vast publishes. It does not test invoice generation or payment processing.';
const index=model=>new Map(model.pages.flatMap(page=>page.claims.map(claim=>[claim.id,claim])));

export function projectPayoutInvoiceCorrection({read,exists}){
 const pin=(ref,wanted)=>{req(typeof ref==='string'&&!ref.startsWith('/')&&!ref.includes('\\')&&ref.split('/').every(p=>p&&!['.','..'].includes(p)),'unsafe path');const value=read(ref);req(sha(value)===wanted,'digest drift '+ref);return value;};
 const registry=JSON.parse(pin(PAYOUT_INVOICE_PATH,PAYOUT_INVOICE_SHA256));req(equal(Object.keys(registry).sort(),['baseline','generated_at','guidance','record_type','schema_version','source','transitions']),'registry keys');req(registry.schema_version==='1.0'&&registry.record_type==='HOST_PAYOUT_INVOICE_CORRECTION','registry type');req(equal(registry.baseline,{path:BASE,sha256:'9873666e659403459d9d0c7a10f8cd3d4372709d86e26c396d0ef604cd13d257'}),'baseline');req(equal(registry.guidance,{path:GUIDANCE,sha256:'9e4a9ff965510e9c08f6c45c929ab5a180d882e7dfe6c14bd65b7b30cef5814c'}),'guidance');req(registry.source.path===SOURCE&&registry.source.before_artifact.path===BEFORE&&registry.source.before_artifact.sha256==='6171ba7c1575be13bdbed837c9ea941c2a3314971c726dcd27f6fb2fd3932442'&&equal(registry.source.changed_lines,[...changed]),'source scope');
 const before=pin(BEFORE,registry.source.before_sha256),after=pin(SOURCE,registry.source.after_sha256),oldLines=before.toString().split(/\r?\n/),lines=after.toString().split(/\r?\n/);if(after.toString().endsWith('\n'))lines.pop();if(before.toString().endsWith('\n'))oldLines.pop();req(oldLines.length===lines.length&&equal(oldLines.flatMap((v,i)=>v===lines[i]?[]:[i+1]),[...changed]),'source edits exceed six approved lines');
 const guidance=JSON.parse(pin(GUIDANCE,registry.guidance.sha256)),sections=new Map(guidance.sections.map(s=>[s.heading_id,s]));req(guidance.url==='https://docs.vast.ai/host/payment'&&guidance.limitations==='This records current published Vast guidance from the same docs repository. It is not independent backend scheduling, account enforcement, actual payment, or owner approval evidence. The deployed Git revision is not identified by the page.','guidance provenance');req(equal([...sections.keys()],['minimum-payout-threshold','invoice-generation','payment-timeline','when-will-i-get-paid','my-account-is-not-generating-invoices'])&&[...sections.values()].every(s=>s.text_sha256===sha(s.text)),'guidance sections');req(sections.get('minimum-payout-threshold').text.includes('$20 USD before an invoice can be generated.')&&sections.get('minimum-payout-threshold').text.includes('roll forward until the minimum threshold')&&sections.get('invoice-generation').text.includes('weekly on Fridays')&&sections.get('invoice-generation').text.includes('valid payout method connected')&&sections.get('payment-timeline').text.includes('up to two weeks to receive your first payout')&&sections.get('payment-timeline').text.includes('depending on the provider and your region'),'guidance wording');
 const baseline=JSON.parse(pin(BASE,registry.baseline.sha256)),oldRead=ref=>ref===SOURCE?before:read(ref),pre=projectPayoutTermsCorrection({read:oldRead,exists});req(equal(baseline,pre.model),'sealed payout Terms predecessor differs from invoice baseline');const old=index(baseline);req(old.size===2013&&[...ids.keys()].every(id=>old.has(id)),'claim inventory');
 const registeredTransitions=Object.fromEntries(registry.transitions.map(x=>[x.claim_id,x.before_sha256]));
 const expectedTransitions={};for(const id of ids.keys())expectedTransitions[id]=sha(JSON.stringify(canon(old.get(id))));
 req(registry.transitions.length===ids.size&&equal(registeredTransitions,expectedTransitions),'claim predecessor');
 const model=structuredClone(baseline),claims=index(model),basis=[],lineSpan=line=>({source_file:SOURCE,start:line,end:line,text_sha256:sha(lines[line-1])});
 for(const [id,[line,anchor]] of ids){const prior=old.get(id),claim=claims.get(id),section=sections.get(anchor),sourceRef={repository:'official-publication',revision:'sha256:'+registry.guidance.sha256,path:'https://docs.vast.ai/host/payment#'+anchor,locator:'/sections/'+[...sections.keys()].indexOf(anchor)+'/text',source_kind:'AUTHORITATIVE_DOCUMENTATION_CITATION'},evidence={id:'EV-PAYOUT-INVOICE-GUIDANCE-01-'+anchor,role:'PUBLISHED_PAYOUT_INVOICE_GUIDANCE',limit,artifact_ref:GUIDANCE};Object.assign(claim,{text:lines[line-1],spans:[lineSpan(line)],status:'PASS',classification:'PUBLISHED_FINANCIAL_GUIDANCE_DESCRIPTION',required_evidence_types:['AUTHORITATIVE_DOCUMENTATION_CITATION'],owner_role:'Documentation authoritative-source reviewer',rationale:'Exact attributed published payout guidance supports this wording only. '+limit,next_action:'Recheck this exact published guidance section if its wording or anchor changes.',evidence_refs:[evidence,...(prior.evidence_refs||[])],source_refs:[sourceRef,...(prior.source_refs||[])],coverage_state:'CHANGED',history:{...prior.history,carry_decision:'CURRENT_HOST_PAYOUT_INVOICE_CORRECTION',reason:(prior.history?.reason||'')+' Exact published-guidance correction; no backend scheduling, account enforcement, actual payment, or owner approval is inferred.',predecessor:{claim_id:id,status:prior.status,text:prior.text,text_sha256:sha(prior.text)}}});basis.push([id,{kind:'PUBLISHED_PAYOUT_INVOICE_GUIDANCE',sourceLabel:'Published Host Payouts guidance',sourceLocator:anchor,sourceUrl:sourceRef.path,artifactRef:GUIDANCE,excerpt:section.text,text_pointer:sourceRef.locator,support_rationale:limit}]);}
 const page=model.pages.find(p=>p.source_file===SOURCE);page.source_sha256=sha(after);page.coverage_state='CHANGED';req(page.claims.every(c=>ids.has(c.id)||!c.spans.some(s=>[...changed].some(line=>s.start<=line&&s.end>=line))),'unrelated claim drift');for(const procedure of page.procedures)for(const node of [procedure,...procedure.nodes])if(node.spans?.some(s=>[...changed].some(line=>s.start<=line&&s.end>=line))){node.spans=[];node.status='STALE';node.coverage_state='CHANGED';node.limits=[...(node.limits||[]),'Payout/invoice source span changed; no procedure evidence transfers.'];node.history={...(node.history||{}),carry_decision:'CURRENT_HOST_PAYOUT_INVOICE_CORRECTION_SOURCE_CHANGED'};}for(const item of model.source.source_manifest)if(item.path===SOURCE)item.sha256=sha(after);req([...old].filter(([id,c])=>equal(c,claims.get(id))).length===2007,'unrelated claim drift');model.counts.claim_statuses={};for(const c of claims.values())model.counts.claim_statuses[c.status]=(model.counts.claim_statuses[c.status]||0)+1;model.generated_at=registry.generated_at;model.corrections.push({id:MARKER,scope:'Six exact Host Payouts invoice/payout guidance occurrences',history:'Payout Terms predecessor and pre-correction payment source are hash-pinned.',current:'Four former FAIL and two formerly UNVALIDATED occurrences are attributed to captured published guidance; agreement evidence remains separately bounded.',reason:'Published guidance only; no backend scheduling, invoice generation, payment processing, account enforcement, Finance approval, or owner acknowledgement is inferred.'});
 const presentation=new Map(pre.presentation);for(const [id,item] of basis){const priorBasis=pre.presentation.get(id)?.basis||[];const agreementBasis=['MCL-3d796f5ae7f2020e','MCL-3afd93ae0b6cf8a4'].includes(id)?priorBasis.map(entry=>({...structuredClone(entry),support_rationale:'Supports only the separately cited Hosting Agreement weekly billing-period and payment-payable-within-14-days clause; not invoice generation or payment processing.'})):[];presentation.set(id,{previous:structuredClone(old.get(id)),method:'PUBLISHED_PAYOUT_INVOICE_GUIDANCE_REVIEW',reviewRationale:claims.get(id).rationale,remaining:limit,registryRef:PAYOUT_INVOICE_PATH,baselineRef:BASE,basis:[item,...agreementBasis],auditHistory:[...(pre.presentation.get(id)?[structuredClone(pre.presentation.get(id))]:[])],payoutInvoice:true});}return {...pre,model,matches:new Map([...pre.matches].map(([id,match])=>[id,{...match,claim:claims.get(id)}])),presentation,artifactHashes:new Map([...pre.artifactHashes,[SOURCE,sha(after)],[PAYOUT_INVOICE_PATH,PAYOUT_INVOICE_SHA256],[BASE,registry.baseline.sha256],[BEFORE,registry.source.before_sha256],[GUIDANCE,registry.guidance.sha256]]),payoutInvoice:{registry,registrySha256:PAYOUT_INVOICE_SHA256,baseline:BASE,baselineSha256:registry.baseline.sha256,guidance:GUIDANCE,guidanceSha256:registry.guidance.sha256}};
}
export function loadPayoutInvoiceCorrection({read,model,exists}){const present=exists?exists(PAYOUT_INVOICE_PATH):(()=>{try{read(PAYOUT_INVOICE_PATH);return true;}catch{return false;}})(),marked=(model.corrections||[]).some(x=>x.id===MARKER);if(!present){req(!marked,'invoice-marked model has no registry');return null;}const projected=projectPayoutInvoiceCorrection({read,exists});req(equal(model,projected.model),'whole model differs from payout/invoice projection');return projected;}
