/** Fail-closed Terms and published-FAQ corrections above payout-provider UI. */
import crypto from 'node:crypto';
import {projectPayoutProviderCorrection} from './current_host_payout_provider_correction.mjs';
export const PAYOUT_TERMS_PATH='verification/current-host-payout-terms-correction.json';
export const PAYOUT_TERMS_SHA256='de0274c91499680f7dabc974fecdd7ea004bf20fc88a8dfa1456727e903990dc';
const A='verification/evidence/2026-09-14-payout-terms-correction-attempt-01',BASE=A+'/pre-correction-model.json',BEFORE=A+'/pre-correction-payment.mdx',TERMS=A+'/terms-source-02.json',FAQ=A+'/published-payout-faq-01.json',SOURCE='host/payment.mdx',TERMS_ID='MCL-06956d724f70d2a3',FAQ_ID='MCL-9826b26393329d27',MARKER='HOST-PAYOUT-TERMS-CORRECTION-01';
const TERMS_TEXT='The [Terms of Use, Disclaimer of Website](https://vast.ai/terms) include disclaimers for third-party products or services offered through the website. The [Miscellaneous section](https://vast.ai/terms) limits responsibility for delays or failures caused by circumstances beyond Vast\'s reasonable control. The [Limitations of Liability section](https://vast.ai/terms) notes that some exclusions may not apply under certain state laws.';
const FAQ_URL='https://docs.vast.ai/host/payment#can-vast-ai-send-my-payout-via-direct-bank-transfer-ach-swift-wire-transfer-etc-',FAQ_TEXT="[Vast's published payout guidance]("+FAQ_URL+") says direct bank transfers, including ACH, wire and SWIFT, are unavailable.",TERMS_LIMIT='Published Terms text only; no ruling on a particular payout, provider, enforceability, or Hosting Agreement priority.',FAQ_LIMIT='Published payout guidance only; not independent backend/runtime absence, transfer completion, provider fees, or a specific account entitlement.';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),canon=x=>Array.isArray(x)?x.map(canon):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canon(x[k])])):x,equal=(a,b)=>JSON.stringify(canon(a))===JSON.stringify(canon(b)),req=(v,m)=>{if(!v)throw Error('payout Terms correction: '+m);},lines=x=>x.toString().split(/\r?\n/).slice(0,x.toString().endsWith('\n')?-1:undefined),index=model=>new Map(model.pages.flatMap(page=>page.claims.map(claim=>[claim.id,claim]))),changed=new Set([46,98,99,101]);
const support=new Map([[0,'Supports only the published disclaimer for third-party products or services offered through the website.'],[2,"Supports only the published limitation for delay or failure caused by circumstances beyond Vast's reasonable control."],[1,'Supports only the published note that some exclusions may not apply under certain state laws.']]);

export function projectPayoutTermsCorrection({read,exists}){
 const pin=(ref,wanted)=>{req(typeof ref==='string'&&!ref.startsWith('/')&&!ref.includes('\\')&&ref.split('/').every(part=>part&&!['.','..'].includes(part)),'unsafe path');const value=read(ref);req(sha(value)===wanted,'digest drift '+ref);return value;};
 const registry=JSON.parse(pin(PAYOUT_TERMS_PATH,PAYOUT_TERMS_SHA256));req(equal(Object.keys(registry).sort(),['baseline','faq','generated_at','record_type','schema_version','source','terms','transitions']),'registry keys');req(registry.schema_version==='1.0'&&registry.record_type==='HOST_PAYOUT_TERMS_CORRECTION','registry type');req(equal(registry.baseline,{path:BASE,sha256:'39fe1128ebb56c2135b79fe1eeca9c5497056ed95dc517dbb7df203f9617a0dd'}),'baseline');req(registry.source.path===SOURCE&&registry.source.before_artifact.path===BEFORE&&registry.source.before_artifact.sha256==='95e6585980cb936f72c657a0ef508abf917361b210faa8b86b4b5af5896ad0a9'&&equal(registry.source.changed_lines,[...changed].sort((a,b)=>a-b)),'source');req(equal(registry.terms,{path:TERMS,sha256:'f64399871ecdbad036b959e32613fc43ba2aa859d5b578552016b720e1487c4e'}),'Terms source');req(equal(registry.faq,{path:FAQ,sha256:'b618d620ad6e263159e924f20148faee38c5887087de7c369075bb52ce159bfd'}),'FAQ source');
 const before=pin(BEFORE,registry.source.before_sha256),after=pin(SOURCE,registry.source.after_sha256),oldLines=lines(before),newLines=lines(after);req(oldLines.length===newLines.length&&equal(oldLines.flatMap((line,i)=>line===newLines[i]?[]:[i+1]),[...changed].sort((a,b)=>a-b))&&newLines[45]===TERMS_TEXT&&newLines[97]==='<span id="direct-bank-transfer" aria-hidden="true" /><span id="how-do-i-set-up-payouts" aria-hidden="true" />'&&newLines[98]==='### Can Vast send direct bank transfers?'&&newLines[100]===FAQ_TEXT,'source wording');
 const terms=JSON.parse(pin(TERMS,registry.terms.sha256));req(terms.version==='Version Date: September 1, 2026'&&terms.url==='https://vast.ai/terms'&&equal(terms.sections.map(item=>item.heading),['DISCLAIMER OF WEBSITE','LIMITATIONS OF LIABILITY','MISCELLANEOUS'])&&terms.sections[0].text.includes('PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY')&&terms.sections[1].text.includes('SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU')&&terms.sections[2].text.includes("delay or failure to act caused by any cause beyond Company's reasonable control"),'Terms evidence');
 const faq=JSON.parse(pin(FAQ,registry.faq.sha256));req(equal(Object.keys(faq).sort(),['heading','heading_id','limitations','method','recorded_at','suggest_edits','text','text_sha256','title','url'])&&faq.recorded_at==='2026-09-14T15:09:07.325Z'&&faq.method==='Unauthenticated public browser navigation and exact FAQ DOM extraction'&&faq.heading_id==='can-vast-ai-send-my-payout-via-direct-bank-transfer-ach-swift-wire-transfer-etc-'&&faq.url==='https://docs.vast.ai/host/payment'&&faq.text_sha256===sha(faq.text)&&['No.','Wise','PayPal','Stripe','Direct bank transfers, ACH payments, wire transfers, and SWIFT payments are not available.'].every(item=>faq.text.includes(item)),'FAQ evidence');
 const baseline=JSON.parse(pin(BASE,registry.baseline.sha256)),oldRead=ref=>ref===SOURCE?before:read(ref),pre=projectPayoutProviderCorrection({read:oldRead,exists});req(equal(baseline,pre.model),'sealed payout-provider predecessor differs from Terms baseline');const old=index(baseline),expected=new Map([[TERMS_ID,'88ffda2451249d1f0f5d8bec981444c501449a0607d408e4f63cc2dc5e0336b9'],[FAQ_ID,'e871fbbb737d3f55efa220e254f16ce986709b908a414d29cb0aca6f8538757a']]);req(old.size===2013&&registry.transitions.length===2&&[...expected].every(([id,hash])=>old.has(id)&&sha(JSON.stringify(canon(old.get(id))))===hash)&&equal(Object.fromEntries(registry.transitions.map(item=>[item.claim_id,item.before_sha256])),Object.fromEntries(expected)),'claim predecessor');
 const model=structuredClone(baseline),claims=index(model),termsPrior=old.get(TERMS_ID),faqPrior=old.get(FAQ_ID),order=[0,2,1],span=line=>({source_file:SOURCE,start:line,end:line,text_sha256:sha(newLines[line-1])});
 Object.assign(claims.get(TERMS_ID),{text:TERMS_TEXT,headings:['Payout Account'],spans:[span(46)],status:'PASS',classification:'PUBLISHED_TERMS_SUMMARY',required_evidence_types:['AUTHORITATIVE_DOCUMENTATION_CITATION'],owner_role:'Documentation authoritative-source reviewer',rationale:'Three named published Terms sections are summarized within their stated scope; the former payout/provider-specific exclusion was withdrawn.',next_action:'Recheck the cited Terms sections if the published Terms version changes.',evidence_refs:order.map(i=>({id:'EV-PAYOUT-TERMS-02-'+i,role:'PUBLISHED_TERMS_SECTION',limit:TERMS_LIMIT,artifact_ref:TERMS})),source_refs:order.map(i=>({repository:'official-publication',revision:'sha256:'+registry.terms.sha256,path:'https://vast.ai/terms',locator:'/sections/'+i+'/text',source_kind:'AUTHORITATIVE_DOCUMENTATION_CITATION'})),coverage_state:'CHANGED',history:{...termsPrior.history,carry_decision:'CURRENT_HOST_PAYOUT_TERMS_CORRECTION',reason:(termsPrior.history.reason||'')+' Exact published-Terms summary; the withdrawn universal payout exclusion is not proven.',predecessor:{claim_id:TERMS_ID,status:termsPrior.status,text:termsPrior.text,text_sha256:sha(termsPrior.text)}}});
 Object.assign(claims.get(FAQ_ID),{text:FAQ_TEXT,headings:['Can Vast send direct bank transfers?'],spans:[span(101)],status:'PASS',classification:'PUBLICATION_DESCRIPTION',required_evidence_types:['AUTHORITATIVE_DOCUMENTATION_CITATION'],owner_role:'Documentation authoritative-source reviewer',rationale:'The captured published payout FAQ supports this attributed route-availability description only; it is not independent product or runtime absence evidence.',next_action:'Recheck this exact published FAQ wording if the payout guidance or anchor changes.',evidence_refs:[{id:'EV-PAYOUT-FAQ-01',role:'PUBLISHED_PAYOUT_GUIDANCE',limit:FAQ_LIMIT,artifact_ref:FAQ}],source_refs:[{repository:'official-publication',revision:'sha256:'+registry.faq.sha256,path:FAQ_URL,locator:'/text',source_kind:'AUTHORITATIVE_DOCUMENTATION_CITATION'}],coverage_state:'CHANGED',history:{...faqPrior.history,carry_decision:'CURRENT_HOST_PAYOUT_TERMS_CORRECTION',reason:(faqPrior.history.reason||'')+' Exact attributed published payout guidance replaces the prior UI-only setup instruction; it is not independent transfer-availability proof.',predecessor:{claim_id:FAQ_ID,status:faqPrior.status,text:faqPrior.text,text_sha256:sha(faqPrior.text)}}});
 const page=model.pages.find(item=>item.source_file===SOURCE);page.source_sha256=sha(after);page.coverage_state='CHANGED';req(page.claims.every(item=>[TERMS_ID,FAQ_ID].includes(item.id)||!item.spans.some(span=>[...changed].some(line=>span.start<=line&&span.end>=line))),'unrelated changed claim');for(const procedure of page.procedures)for(const node of [procedure,...procedure.nodes])if(node.spans?.some(span=>[...changed].some(line=>span.start<=line&&span.end>=line))){node.spans=[];node.status='STALE';node.coverage_state='CHANGED';node.limits=[...(node.limits||[]),'Payout Terms source span changed; no procedure evidence transfers.'];node.history={...(node.history||{}),carry_decision:'CURRENT_HOST_PAYOUT_TERMS_CORRECTION_SOURCE_CHANGED'};}for(const item of model.source.source_manifest)if(item.path===SOURCE)item.sha256=sha(after);req([...old].filter(([id,item])=>equal(item,claims.get(id))).length===2011,'unrelated claim drift');model.counts.claim_statuses={};for(const item of claims.values())model.counts.claim_statuses[item.status]=(model.counts.claim_statuses[item.status]||0)+1;model.generated_at=registry.generated_at;model.corrections.push({id:MARKER,scope:'One Terms summary and one attributed direct-bank-transfer FAQ description',history:'Payout-provider predecessor and source are pinned.',current:'One Terms-backed summary and one attributed published payout FAQ description.',reason:'No payout/provider adjudication, enforceability decision, Hosting Agreement priority, or independent backend/runtime absence is inferred.'});
 const basis=order.map(i=>({kind:'PUBLISHED_TERMS_SECTION',sourceLabel:'Vast Terms of Use',sourceLocator:terms.sections[i].heading,sourceUrl:'https://vast.ai/terms',artifactRef:TERMS,excerpt:terms.sections[i].text,text_pointer:'/sections/'+i+'/text',support_rationale:support.get(i)+' '+TERMS_LIMIT}));basis.push({kind:'PUBLISHED_PAYOUT_GUIDANCE',sourceLabel:'Published Host Payouts FAQ',sourceLocator:faq.heading_id,sourceUrl:FAQ_URL,artifactRef:FAQ,excerpt:faq.text,text_pointer:'/text',support_rationale:'Supports only the attributed published direct-bank-transfer guidance. '+FAQ_LIMIT});
 return {...pre,model,matches:new Map([...pre.matches].map(([id,match])=>[id,{...match,claim:claims.get(id)}])),presentation:new Map([...pre.presentation,[TERMS_ID,{previous:structuredClone(termsPrior),method:'PUBLISHED_TERMS_SECTION_REVIEW',reviewRationale:claims.get(TERMS_ID).rationale,remaining:TERMS_LIMIT,registryRef:PAYOUT_TERMS_PATH,baselineRef:BASE,basis:basis.filter(item=>item.kind==='PUBLISHED_TERMS_SECTION'),auditHistory:[...(pre.presentation.get(TERMS_ID)?[structuredClone(pre.presentation.get(TERMS_ID))]:[])],payoutTerms:true}],[FAQ_ID,{previous:structuredClone(faqPrior),method:'PUBLISHED_PAYOUT_FAQ_REVIEW',reviewRationale:claims.get(FAQ_ID).rationale,remaining:FAQ_LIMIT,registryRef:PAYOUT_TERMS_PATH,baselineRef:BASE,basis:basis.filter(item=>item.kind==='PUBLISHED_PAYOUT_GUIDANCE'),auditHistory:[...(pre.presentation.get(FAQ_ID)?[structuredClone(pre.presentation.get(FAQ_ID))]:[])],payoutTerms:true}]]),artifactHashes:new Map([...pre.artifactHashes,[SOURCE,sha(after)],[PAYOUT_TERMS_PATH,PAYOUT_TERMS_SHA256],[BASE,registry.baseline.sha256],[BEFORE,registry.source.before_sha256],[TERMS,registry.terms.sha256],[FAQ,registry.faq.sha256]]),payoutTerms:{registry,registrySha256:PAYOUT_TERMS_SHA256,baseline:BASE,baselineSha256:registry.baseline.sha256,terms:TERMS,termsSha256:registry.terms.sha256,faq:FAQ,faqSha256:registry.faq.sha256}};
}
export function loadPayoutTermsCorrection({read,model,exists}){const present=exists?exists(PAYOUT_TERMS_PATH):(()=>{try{read(PAYOUT_TERMS_PATH);return true;}catch{return false;}})(),marked=(model.corrections||[]).some(item=>item.id===MARKER);if(!present){req(!marked,'Terms-marked model has no registry');return null;}const projected=projectPayoutTermsCorrection({read,exists});req(equal(model,projected.model),'whole model differs from payout Terms projection');return projected;}
