/** Fail-closed four-claim Payout Account UI correction above cleanup. */
import crypto from 'node:crypto';
import {loadReviewCleanup} from './current_host_review_cleanup.mjs';

export const PAYOUT_PATH='verification/current-host-payout-provider-correction.json';
export const PAYOUT_SHA256='a93f8976805b1cd773d1216780419fcb3e361d496142abe61484719f9bbe27be';
export const PAYOUT_ATTEMPT='verification/evidence/2026-09-14-payout-provider-correction-attempt-01';
export const PAYOUT_BASELINE=PAYOUT_ATTEMPT+'/pre-correction-model.json';
export const PAYOUT_BASELINE_SHA256='1b22bc97a8dc73fa34c047331a8a6a76e3a7564d8579cee5414139c269cf2857';
export const PAYOUT_BEFORE=PAYOUT_ATTEMPT+'/pre-correction-payment.mdx';
export const PAYOUT_BEFORE_SHA256='02022ade67dcc35c44c660a5d3cdac7547c889c3a30e239eff56b57b22525992';
export const PAYOUT_SOURCE='host/payment.mdx';
export const PAYOUT_OBSERVATION='verification/evidence/2026-09-14-payout-ui-intake-attempt-01/observation.json';
export const PAYOUT_OBSERVATION_SHA256='2ea94e5628c754d6d67ce4fb3b0f7fdcaf3bdb1a30ae28e50e483e83de19a9ef';
export const PAYOUT_STATIC_CHECK=PAYOUT_ATTEMPT+'/source-link-check.json';
export const PAYOUT_STATIC_CHECK_SHA256='004aa077b2b1f1c15f3213d705235ee91bd128718352b8bda9c3cb09026fc970';
export const PAYOUT_MARKER='HOST-PAYOUT-PROVIDER-CORRECTION-01';
const ids=new Map([['MCL-77f72f0e0ac77e54',['PayPal','PAYOUT-UI-PAYPAL-01']],['MCL-a04f3ef2f5a7d5fd',['Stripe','PAYOUT-UI-STRIPE-01']],['MCL-cc62439b0f816902',['Wise','PAYOUT-UI-WISE-01']],['MCL-9826b26393329d27',[null,'PAYOUT-UI-DIRECT-01']]]);
const changed=new Set([31,98,99,101]), lanes=['REPOSITORY_STATIC_CHECK','RUNTIME_OR_UI_OBSERVATION'];
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const canon=x=>Array.isArray(x)?x.map(canon):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canon(x[k])])):x;
const equal=(a,b)=>JSON.stringify(canon(a))===JSON.stringify(canon(b));
const objhash=x=>hash(JSON.stringify(canon(x)));
const req=(ok,message)=>{if(!ok)throw Error('payout provider correction: '+message)};
const keys=(x,names,label)=>req(x&&typeof x==='object'&&!Array.isArray(x)&&equal(Object.keys(x).sort(),[...names].sort()),'invalid '+label+' keys');
const lines=bytes=>bytes.toString().split(/\r?\n/).slice(0,bytes.toString().endsWith('\n')?-1:undefined);
const span=(start,end,source)=>({source_file:PAYOUT_SOURCE,start,end,text_sha256:hash(source.slice(start-1,end).join('\n'))});
const claimIndex=model=>new Map(model.pages.flatMap(page=>page.claims.map(claim=>[claim.id,claim])));

function correction(after){return {id:PAYOUT_MARKER,scope:'Four exact Host Payouts provider-list/setup occurrences',history:'The sealed cleanup predecessor and the pre-correction Host Payouts source are hash-pinned. Each predecessor FAIL literal remains in its claim history.',current:`Three bounded provider-list occurrences and one provider-setup instruction are tied to the user-supplied Payout Account UI transcription and user-attributed Earnings URL; Host Payouts source ${PAYOUT_BEFORE_SHA256} → ${after}.`,reason:'The UI crop supports displayed Stripe, PayPal and Wise choices only. It does not establish an active account, a completed payment, fees, eligibility, provider-mediated bank routes, or a universal ACH/wire/SWIFT exclusion.'};}

export function projectPayoutProviderCorrection({read,exists}){
 const pinned=(ref,wanted)=>{req(typeof ref==='string'&&!ref.startsWith('/')&&!ref.includes('\\')&&ref.split('/').every(x=>x&&!['.','..'].includes(x)),'unsafe path');const value=read(ref);req(hash(value)===wanted,'digest drift '+ref);return value};
 const registry=JSON.parse(pinned(PAYOUT_PATH,PAYOUT_SHA256));keys(registry,['schema_version','record_type','generated_at','baseline','source','static_check','observation','transitions'],'registry');
 req(registry.schema_version==='1.0'&&registry.record_type==='HOST_PAYOUT_PROVIDER_UI_CORRECTION','wrong registry type');req(equal(registry.baseline,{path:PAYOUT_BASELINE,sha256:PAYOUT_BASELINE_SHA256}),'baseline substitution');
 keys(registry.source,['path','before_artifact','before_sha256','after_sha256','changed_lines'],'source');keys(registry.source.before_artifact,['path','sha256'],'before source');
 req(registry.source.path===PAYOUT_SOURCE&&equal(registry.source.before_artifact,{path:PAYOUT_BEFORE,sha256:PAYOUT_BEFORE_SHA256})&&registry.source.before_sha256===PAYOUT_BEFORE_SHA256&&equal(registry.source.changed_lines,[...changed].sort((a,b)=>a-b)),'source scope drift');
 keys(registry.observation,['path','sha256'],'observation');req(equal(registry.observation,{path:PAYOUT_OBSERVATION,sha256:PAYOUT_OBSERVATION_SHA256}),'observation substitution');keys(registry.static_check,['path','sha256'],'static check');req(equal(registry.static_check,{path:PAYOUT_STATIC_CHECK,sha256:PAYOUT_STATIC_CHECK_SHA256}),'static check substitution');
 const beforeBytes=pinned(PAYOUT_BEFORE,PAYOUT_BEFORE_SHA256),afterBytes=pinned(PAYOUT_SOURCE,registry.source.after_sha256),beforeSource=lines(beforeBytes),afterSource=lines(afterBytes);
 req(beforeSource.length===afterSource.length,'line-stable source correction required');req(equal(beforeSource.flatMap((x,i)=>x===afterSource[i]?[]:[i+1]),[...changed].sort((a,b)=>a-b)),'source edits exceed exact approved lines');
 req(afterSource[30]==='The payout providers shown under [Earnings > Payout Account](https://cloud.vast.ai/earnings/) are:','provider wording drift');req(afterSource[97]==='<span id="direct-bank-transfer" aria-hidden="true" /><span id="can-vast-send-direct-bank-transfers" aria-hidden="true" />','legacy aliases missing');req(afterSource[98]==='### How do I set up payouts?'&&afterSource[100]==='Set up payouts through Stripe, PayPal or Wise under [Earnings > Payout Account](https://cloud.vast.ai/earnings/).','setup wording drift');req(!/ach|wire|swift|not available|direct bank/i.test(afterSource[100]),'unsupported global bank prohibition remains');const staticCheck=JSON.parse(pinned(PAYOUT_STATIC_CHECK,PAYOUT_STATIC_CHECK_SHA256));req(staticCheck.record_type==='PAYOUT_PROVIDER_SOURCE_LINK_CHECK'&&equal(staticCheck.source,{path:PAYOUT_SOURCE,sha256:hash(afterBytes)}),'static link source drift');const expectedStatic=Object.fromEntries([...ids].map(([id,[provider]])=>[id,provider?31:101]));req(equal(Object.fromEntries(staticCheck.checks.map(item=>[item.claim_id,item.line])),expectedStatic)&&staticCheck.checks.every(item=>item.href==='https://cloud.vast.ai/earnings/'&&item.result==='PASS'),'static link check drift');
 const observation=JSON.parse(pinned(PAYOUT_OBSERVATION,PAYOUT_OBSERVATION_SHA256));req(observation.record_type==='USER_SUPPLIED_PAYOUT_UI_EVIDENCE_INTAKE'&&observation.source?.attributed_url==='https://cloud.vast.ai/earnings/','invalid UI observation');const observed=new Map(observation.observations.map(item=>[item.id,item]));req(equal([...observed.keys()].sort(),[...ids.values()].map(x=>x[1]).sort()),'UI observations differ from four bounded findings');req(observed.get('PAYOUT-UI-DIRECT-01')?.supports.includes('Does not establish'),'bank-transfer limitation missing');
 const baseline=JSON.parse(pinned(PAYOUT_BASELINE,PAYOUT_BASELINE_SHA256));
 // Re-read the whole sealed predecessor against the frozen payment source; no
 // current payout edit is allowed to weaken any earlier gate.
 const oldRead=ref=>ref===PAYOUT_SOURCE?beforeBytes:read(ref);const predecessor=loadReviewCleanup({read:oldRead,model:baseline,exists});req(predecessor?.cleanup,'sealed cleanup predecessor required');
 const before=claimIndex(baseline);req(before.size===2013&&[...ids.keys()].every(id=>before.has(id)),'baseline claim inventory drift');
 const entries=new Map();for(const entry of registry.transitions){keys(entry,['claim_id','before_sha256','observation_ids'],'transition');const expected=ids.get(entry.claim_id)?.[0]?[ids.get(entry.claim_id)[1]]:['PAYOUT-UI-PAYPAL-01','PAYOUT-UI-STRIPE-01','PAYOUT-UI-WISE-01'];req(ids.has(entry.claim_id)&&!entries.has(entry.claim_id)&&entry.before_sha256===objhash(before.get(entry.claim_id))&&equal(entry.observation_ids,expected),'transition predecessor or observation drift');entries.set(entry.claim_id,entry)}req(entries.size===4,'four exact transitions required');
 const model=structuredClone(baseline),after=claimIndex(model),evidence=id=>({id:'EV-'+id,role:'USER_SUPPLIED_UI_OBSERVATION',limit:'User-supplied cropped Payout Account view, URL user-attributed and capture time unknown; no transaction, active-account, fee, eligibility, or bank-route proof.',artifact_ref:PAYOUT_OBSERVATION}),staticEvidence={id:'EV-PAYOUT-PROVIDER-SOURCE-LINK-01',role:'CURRENT_REPOSITORY_STATIC_CHECK',limit:staticCheck.limit,artifact_ref:PAYOUT_STATIC_CHECK};
 for(const [id,[provider,observationId]] of ids){const prior=before.get(id),claim=after.get(id);let spans,text,headings;if(provider){const line={Wise:33,PayPal:34,Stripe:35}[provider];spans=[span(31,31,afterSource),span(line,line,afterSource)];text=spans.map(s=>afterSource.slice(s.start-1,s.end).join('\n')).join('\n');headings=['Payout Methods'];}else{spans=[span(101,101,afterSource)];text=afterSource[100];headings=['How do I set up payouts?'];}const evidenceRefs=[staticEvidence,...entries.get(id).observation_ids.map(evidence)];Object.assign(claim,{text,headings,spans,status:'PASS',classification:'REVIEWED_UI_PROVIDER_OPTION',required_evidence_types:lanes,owner_role:'Documentation reviewer',rationale:'The bounded user-supplied Earnings > Payout Account UI observation shows the named provider choice, and the current source link was checked for the same scope.',next_action:'Recheck this exact Payout Account view and wording if the provider cards or Earnings route changes.',evidence_refs:evidenceRefs,source_refs:[],coverage_state:'CHANGED',history:{...prior.history,carry_decision:'CURRENT_HOST_PAYOUT_PROVIDER_UI_CORRECTION',reason:(prior.history.reason||'')+' Exact provider UI correction; no payout transaction or universal bank-transfer conclusion is inferred.',predecessor:{claim_id:id,status:prior.status,text:prior.text,text_sha256:hash(prior.text)}}});req(claim.text===claim.spans.map(s=>afterSource.slice(s.start-1,s.end).join('\n')).join('\n'),'claim literal/span drift '+id);if(provider)req(observed.get(observationId)?.claim_id===id,'observation claim binding drift');else req(entries.get(id).observation_ids.every(item=>observed.get(item)?.claim_id&&item!=='PAYOUT-UI-DIRECT-01'),'FAQ uses unsupported absence observation');}
 const page=model.pages.find(page=>page.source_file===PAYOUT_SOURCE);req(page,'payment page missing');page.source_sha256=hash(afterBytes);page.coverage_state='CHANGED';for(const claim of page.claims)if(!ids.has(claim.id))req(!claim.spans.some(s=>{for(let i=s.start;i<=s.end;i++)if(changed.has(i))return true;return false}),'unrelated changed claim '+claim.id);
 for(const procedure of page.procedures)for(const node of [procedure,...procedure.nodes])if(node.spans?.some(s=>{for(let i=s.start;i<=s.end;i++)if(changed.has(i))return true;return false})){node.spans=[];node.status='STALE';node.coverage_state='CHANGED';node.limits=[...(node.limits||[]),'Payout-provider source span changed; no procedure evidence transfers.'];node.history={...(node.history||{}),carry_decision:'CURRENT_HOST_PAYOUT_PROVIDER_UI_CORRECTION_SOURCE_CHANGED'};}
 for(const item of model.source.source_manifest)if(item.path===PAYOUT_SOURCE)item.sha256=hash(afterBytes);req([...before].filter(([id,claim])=>equal(claim,after.get(id))).length===2009,'unrelated claim drift');model.counts.claim_statuses={};for(const claim of after.values())model.counts.claim_statuses[claim.status]=(model.counts.claim_statuses[claim.status]||0)+1;model.generated_at=registry.generated_at;model.corrections.push(correction(hash(afterBytes)));const payoutPresentation=id=>({previous:structuredClone(before.get(id)),method:'USER_SUPPLIED_PAYOUT_ACCOUNT_UI_INSPECTION_AND_SOURCE_LINK_CHECK',reviewRationale:after.get(id).rationale,remaining:'Bounded displayed-provider/setup evidence only; no payout transaction, fee, eligibility or bank-route conclusion.',registryRef:PAYOUT_PATH,baselineRef:PAYOUT_BASELINE,basis:[{kind:'REPOSITORY_STATIC_CHECK',sourceLabel:'Payout options checked',sourceLocator:'Exact source href',sourceUrl:null,artifactRef:PAYOUT_STATIC_CHECK,excerpt:staticCheck.limit,text_pointer:'/limit',support_rationale:'Exact current source and href only.'},...entries.get(id).observation_ids.map(observationId=>{const index=observation.observations.findIndex(item=>item.id===observationId);return {kind:'USER_SUPPLIED_UI_OBSERVATION',sourceLabel:'Supplied UI checked',sourceLocator:'Payout Account; '+observationId,sourceUrl:'https://cloud.vast.ai/earnings/',artifactRef:PAYOUT_OBSERVATION,observationId,excerpt:observed.get(observationId).supports,text_pointer:'/observations/'+index+'/supports',support_rationale:'Bounded visible provider option only.'};})],auditHistory:[...(predecessor.presentation.get(id)?[structuredClone(predecessor.presentation.get(id))]:[])],payoutProvider:true});return {...predecessor,model,matches:new Map([...predecessor.matches].map(([id,match])=>[id,{...match,claim:after.get(id)}])),presentation:new Map([...predecessor.presentation,...[...ids].map(([id])=>[id,payoutPresentation(id)])]),artifactHashes:new Map([...predecessor.artifactHashes,[PAYOUT_SOURCE,hash(afterBytes)],[PAYOUT_PATH,PAYOUT_SHA256],[PAYOUT_BASELINE,PAYOUT_BASELINE_SHA256],[PAYOUT_BEFORE,PAYOUT_BEFORE_SHA256],[PAYOUT_OBSERVATION,PAYOUT_OBSERVATION_SHA256],[PAYOUT_STATIC_CHECK,PAYOUT_STATIC_CHECK_SHA256]]),payoutProvider:{registry,registrySha256:PAYOUT_SHA256,baseline:PAYOUT_BASELINE,baselineSha256:PAYOUT_BASELINE_SHA256,observation:PAYOUT_OBSERVATION,observationSha256:PAYOUT_OBSERVATION_SHA256,staticCheck:PAYOUT_STATIC_CHECK,staticCheckSha256:PAYOUT_STATIC_CHECK_SHA256}};
}

export function loadPayoutProviderCorrection({read,model,exists}){const present=exists?exists(PAYOUT_PATH):(()=>{try{read(PAYOUT_PATH);return true}catch{return false}})(),marked=(model.corrections||[]).some(item=>item.id===PAYOUT_MARKER);if(!present){req(!marked,'payout-marked model has no registry');return null}const projected=projectPayoutProviderCorrection({read,exists});req(equal(model,projected.model),'whole model differs from payout-provider projection');return projected;}
