# Individual review decisions; consumed by build_decisions.py only.
sm=code('vastai/cli/commands/machines.py',72,110)
sd=code('vastai/sdk.py',474,538)
lm=code('vastai/cli/commands/machines.py',265,310)
cl=code('vastai/cli/commands/machines.py',334,382)
mt=code('vastai/cli/commands/machines.py',466,526)
st=code('vastai/cli/commands/machines.py',699,731)
ss=code('vastai/sdk.py',1195,1197)
metrics=code('vastai/cli/commands/metrics.py',15,104)
trends=code('vastai/cli/commands/metrics.py',107,149)
locations=code('vastai/cli/commands/metrics.py',218,255)
ma=code('vastai/api/metrics.py',7,63)
auth=code('vastai/api/client.py',77,89)
bundle=code('vastai/cli/self_test/support_bundle.py',192,268)
hostbundle=code('vastai/cli/self_test/support_bundle.py',130,173)
redaction=code('vastai/cli/self_test/support_bundle.py',19,65)
dump=code('vastai/cli/commands/machines.py',612,692)
diag=code('vastai/cli/self_test/machine_diagnostics.py',349,426)
nccl=code('vastai/cli/self_test/runtime_diagnostics.py',191,196)
declared=['CANONICAL_IMPLEMENTATION_SOURCE','STATIC_CONTEXT_REVIEW']
for i,refs,why in [
 ('MCL-0b44a8d35cdf9e1a',[sm,sd],'The exact CLI command registrations and implemented SDK delegates expose the two machine-state reads; the row maps interfaces, not a current account result.'),
 ('MCL-31780c80ae3cac80',[lm,sd],'Both list/unlist CLI registrations and SDK implementations match; the row identifies entry points without asserting a successful listing mutation.'),
 ('MCL-d078ec43af5e7a28',[cl,sd],'Cleanup and defrag registrations/SDK delegates exist and match the linked names. Defrag rearranges GPU assignments rather than disk defragmentation; the broad repair/cleanup row is interface navigation only.'),
 ('MCL-d09f027e5f9f7b07',[metrics,trends,locations],'All three exact metrics commands are registered; the SDK column is explicitly qualified where available and does not invent a metrics SDK method.')]:
 add(i,refs,why,methods=declared)
add('MCL-39d956b828a766be',[st,ss],'The CLI self-test is implemented, but the advertised SDK method immediately raises NotImplementedError. The entire mapping needs an explicit CLI-only qualification.',decision='correction',replacement='| Run self-test | [self-test machine](/cli/reference/self-test-machine) | Use the CLI; the Python SDK method is not implemented. |',methods=declared)
add('MCL-94bb4bab675fa0c6',[sm,lm,cl,mt,st],'The source defines available operations but contains no measurement showing what most hosts use. Replace the usage-population claim with an introduction to available commands.',decision='correction',replacement='Use the CLI for the following tasks; the SDK supports the implemented methods listed above:',methods=declared,classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
for i,refs,why in [
 ('MCL-34aff665d1e50aaa',[st,ss],'Self-test can be invoked through the documented CLI entry point after a fix. Together with the proposed introduction, this recommends running a diagnostic and does not claim that the SDK stub works or that the fix succeeded.'),
 ('MCL-119bcf4f43e4cb51',[sm,diag],'The CLI reads hosted-machine payloads and diagnostics inspect rented, verification and error fields. The bullet describes checking reported state rather than independently establishing live health.'),
 ('MCL-ea667318b74d816b',[lm,sd],'The command declarations explicitly support listing/updating pricing and unlisting. Review covers available operations, not resulting rentability or current rental-price changes.'),
 ('MCL-403d274d53dcff55',[mt,sd],'Both scheduling and cancellation commands and SDK delegates are implemented. No accepted maintenance window, downtime permission, or backend success is inferred.'),
 ('MCL-07e440c43f3b61fb',[cl],'The declared cleanup operation removes expired storage instances. The bullet describes that task and does not guarantee free space or authorize deleting current customer workloads.'),
 ('MCL-5ce91758cdd42a6d',[lm,sd],'The plural CLI command and SDK list_machines iterate supplied machine IDs from one client. This supports multi-machine operation from one workstation without executing changes.')]:
 add(i,refs,why)
for i,refs,why in [
 ('CUR-a79e559ca5aceabf',[metrics,ma],'This is a lead-in to the registered current snapshot command immediately below; it does not assert a current measured snapshot.'),
 ('CUR-a3757b11890b02da',[trends,ma],'This lead-in names the adjacent registered GPU-history command; it makes no market-result claim.'),
 ('CUR-8f415e72697f67a5',[locations,ma],'This lead-in names the adjacent registered locations command; it does not claim geographic accuracy of a live result.'),
 ('CUR-767c47b216acfb02',[auth],'The client explicitly formats Authorization as Bearer plus the API key. This proves header syntax, not permissions or successful authentication.'),
 ('CUR-9eb72db181f81086',[ma],'The following parameter rows refer to the source-defined REST metrics request parameters; this is a table lead-in.'),
 ('CUR-13159c926782a164',[ma],'The REST API wrapper declares verified values yes/no/all. These are REST values; CLI --verified uses true/false/all and translates them.'),
 ('CUR-c5970a3bcb839da9',[ma],'The REST API wrapper declares secure_cloud/community/all hosting_type values; this does not imply CLI --datacenter accepts those literals.'),
 ('CUR-8bd3f260907a9130',[ma],'The API wrapper declares start/end Unix timestamps and serializes present values into query arguments.'),
 ('CUR-6859da618cb3827f',[ma],'The API wrapper declares step in seconds between data points. No exact server sampling cadence is asserted.')]:
 add(i,refs,why)
add('MCL-4fbce74c8314d7c9',[diag],'The diagnostic source reads vericode on offers and treats numeric/string zero as empty state while rendering other codes. The glossary does not assign bit meanings or promise a definitive verification verdict.')
for i,why,refs in [
 ('MCL-7ffec0f9b23aaf16','The lead-in is explicitly conditional; the source writes supplied output/result and manifest/error members, with optional extra files.',[bundle]),
 ('MCL-d3cae0fb3cb5c9d6','The flag defaults false; collection reads the local filesystem only. Its local-host qualifier and manual review instruction correctly limit a remote CLI bundle. This is not a claim that arbitrary remote access is impossible.',[bundle,hostbundle,redaction,dump]),
 ('MCL-e36f08c1dedadcc9','The support checklist asks for a bundle only when available; source defines its creation and errors, without requiring every collection to succeed.',[bundle]),
 ('MCL-df0057a65286eb13','The checklist is conditional on a self-test error; the source-defined bundle supplies relevant result and command context when created.',[bundle])]:
 add(i,refs,why)
for i in ['MCL-884394079ab58c34','MCL-e3dbeb7aa010c7e5','MCL-0aeb0b73ffda8457','CUR-5b27db1b2c1d625e']:
 add(i,[bundle,diag],'This exact item is an editorial request for diagnostic context in the support checklist, not a technical promise or mandatory support acceptance rule. Error text/timing/rental context helps distinguish the source-defined diagnostic conditions.',methods=['STATIC_CONTEXT_REVIEW'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('CUR-7c0d43b9bed78244',[redaction],'The source redacts known sensitive fields, and the instruction to review broader secrets/customer information is conservative sharing advice rather than a guarantee that automatic redaction is complete.',methods=['STATIC_CONTEXT_REVIEW','CANONICAL_IMPLEMENTATION_SOURCE'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
for i in ['CUR-651294992dada22c','CUR-546b560d7396ac07','CUR-86bd3f3370a7484d','CUR-be15e303131a0f07']:
 add(i,[public('systemctl')],'The complete fence is standard systemctl status syntax for the Vastai service. Source verification establishes the requested snapshot operation only; adjacent recovery or healthy-state assertions are not transferred.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-5b4120877294038d',[public('systemctl')],'The complete fence requests activation of vastai.service; this validates command semantics, not the surrounding promise that starting it recovers an offline machine.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
for i in ['CUR-c2b72b6b624b25d7','CUR-3ab39720adfd3881','CUR-008dd7b297cfe335']:
 add(i,[oldtool(11)],'The NVIDIA manual defines the complete nvidia-smi query; -q selects its detailed report. Values and unsupported fields vary by driver/device; no machine health conclusion or current execution is asserted.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-cbc7aaf13af05a1f',[oldtool(6),oldtool(7)],'dmesg -T reads the kernel ring buffer with converted timestamps; grep -iE applies the displayed case-insensitive alternatives. No matches may produce exit1; timestamps can be inaccurate after suspend and this is not a complete GPU-health test.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-8deeeeeae7529d2e',[oldtool(1),oldtool(7)],'journalctl -k -b selects retained kernel entries from the current boot; grep -iE searches the literal alternatives. This validates syntax and selection, not complete retained history or absence of a GPU fault.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-097897b950a25c64',[public('ping')],'The fence sends four ICMP requests to the given IPv4 address; its context already separates ICMP from DNS/general Internet health.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-a6fb4be482b49cc3',[public('nslookup')],'The fence is a noninteractive name lookup using the configured resolver; it does not assert a particular current answer.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-bd934e556fa399f2',[public('curl'),public('ifconfig')],'The fence requests the documented IP-reporting interface with IPv4 resolution. It provides an HTTP egress observation when successful, without promising current availability or inbound reachability.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-8ab6037f36301981',[public('rfc5737'),public('ifconfig')],'The full literal is explicitly labelled an expected sample and the next paragraph says the address will differ. TEST-NET-3 is suitable documentation notation, not a runtime value to reproduce.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-848fef3fdd4eee35',[public('ping')],'The fenced ping response is illustrative output showing four replies and0%loss; reply counts and rounded timings are internally compatible. It is not retained runtime evidence or a required exact latency/TTL value.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-201737b41ce0ff38',[public('nslookup')],'The full fence illustrates a DNS response and the following explanation explicitly permits a different returned IP. The local resolver and target IP are example values, not assertions about current Vast DNS.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'])
for i,why in [
 ('CUR-b36aa1c240836460','This is an instruction to inspect the following service-status snapshot, not a claim that a service is active.'),
 ('CUR-8123840c36bb1246','This is a request to inspect service state after the preceding procedure, not a guarantee that the procedure restored service or sustained availability.'),
 ('CUR-c229d76db9f47b74','This conditional recommends investigation when service/GPU queries are abnormal; it neither diagnoses one unique cause nor promises recovery.')]:
 add(i,[public('systemctl'),oldtool(11)],why,methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('CUR-ebd77d25aa1975ef',[public('systemctl')],'This labels the adjacent illustrative systemctl display. Normal is scoped to the displayed service process state, not full host health or actual current hardware.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-b4953b096644b00f',[public('systemctl')],'The full fence is explicitly example output. The active state, PID, cgroup and truncated lines follow the documented human-readable status layout; the date/memory/PID are illustrative and not a current Host claim.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-e68bd48f2d0e208a',[public('systemctl')],'The explanation interprets the displayed activation timestamp and elapsed time as service uptime. A good sign is qualified advice; it does not assert complete machine health or that a service cannot fail next.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-e89f14f59bbe9fdf',[public('nvidia_driver'),oldtool(8)],'The literal conflates driver communication failure with invisibility to the entire system. Driver-not-loaded and PCIe disappearance are distinct; remove the unsupported universal conclusion and unmeasured frequency.',decision='correction',replacement='- **`NVIDIA-SMI has failed because it couldn\'t communicate with the NVIDIA driver`** — `nvidia-smi` cannot communicate with the driver. Check the driver and kernel state; this message alone does not show whether the GPUs remain visible on PCIe.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-9216e1cdd3e0869b',[public('journald'),oldtool(1)],'The kernel journal can outlast ring-buffer entries but collection and retention are conditional. Replace the categorical historical-capture promise with the actual journal boundary.',decision='correction',replacement='Search retained kernel journal entries for the current boot for the same NVIDIA/PCIe error patterns. Entries already captured by journald may remain after the kernel ring buffer overwrites them; availability depends on journal collection and retention:',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('CUR-289bb4892fc1ed78',[public('systemctl')],'A status snapshot shows service state and recent logs; a single read does not always establish a restart loop or its duration. Qualify the diagnostic value.',decision='correction',replacement='Current state of the Vastai service, including its activation time and recent log messages. Repeated status checks and journal entries can help identify a restart loop:',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('MCL-806f2d92f1fa26f2',[public('docker_permissions'),oldtool(7)],'In the documented standard rootful Host installation, Docker socket access uses authorized group access or sudo. grep exit1 means no matching output line; this statement alone does not establish that Docker info succeeded. Rootless and custom-socket setups are outside this Host default context.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION'])
add('MCL-281a990a183c3268',[public('fabric'),nccl],'This is qualified NVSwitch diagnostic advice: inspect applicable Host fabric services because a container NCCL error alone does not observe their systemd state. NVLSM applies only on relevant architectures; no reset or repair is asserted.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE'])
add('MCL-f0f80d6abe9fe6ca',[nccl],'The runtime diagnostic catalog defines nccl_failed as a distributed communication test failure and recommends multi-GPU connectivity/NCCL transport investigation. This full row is a route, not an actual fault or repair claim.',methods=declared)
add('MCL-71aa729580ef41f6',[diag],'The diagnostic source explicitly distinguishes machine/offer visibility, rented state and no-rentable-offer state. The row routes to investigation without promising what caused the state or that it clears.',methods=declared)
add('MCL-496140cb2d389f83',[diag,owner(58492,1,5)],'The row provides a broad health/platform-state route consistent with owner-defined machine states and CLI diagnostic observations; it makes no claim that every red message de-verifies or unlists the machine.',methods=['CANONICAL_IMPLEMENTATION_SOURCE','AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
add('MCL-bfc6481ee67f3d04',[owner(58492,18),public('xid79')],'The engineering owner describes the PCIe/AER condition, and NVIDIA identifies Xid79 as fallen off the bus. The row selects a hardware-path investigation without claiming a uniquely proven bad component.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
for i in ['CUR-81159e163bace8db','CUR-98fe1a3036cb8de0']:
 add(i,[public('market_ui')],'The published upstream Vast guide identifies this exact dashboard URL. This passage is a navigation entry; accepting it does not imply a fresh authenticated screen or market data capture.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
add('CUR-537c45cc5c041c21',[public('market_ui'),trends],'The independently published upstream dashboard definition names this view and its historical counts/P10/median/P90 contents, consistent with the current CLI fields. No live values or update rate are asserted.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE'])
add('CUR-591de37ea1d33168',[public('calculator')],'The official current endpoint identifies itself as the earnings calculator. Review accepts the navigation destination only, not its unrelated commercial claims.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
add('CUR-2f4cb77bf9345643',[public('market_ui'),public('calculator')],'The lead-in recommends existing Vast-owned planning resources. It makes no precise income forecast or endorsement of every statement on either destination.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('CUR-d87b7e0c4ec551b4',[public('market_ui'),ma],'The sentence directs readers to the official market-data surface for current signals. In context the page explicitly declines cadence guarantees and treats revenue as an estimate; source of truth is an attribution to Vast data rather than an assertion of perfect freshness.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
for i,why in [
 ('CUR-6f4e9e6b2ac6e6bd','This is an introduction to a rough compute-only arithmetic estimate, with the following page text excluding expenses and other revenue. Multiplying an hourly rate by an assumed occupied-time fraction is dimensional arithmetic, not a prediction that a particular machine will achieve that utilization.'),
 ('CUR-25b06b9e16051c3c','The entire literal is explicitly hypothetical (Example: if). The source schema identifies30-day utilization and median per-GPU hourly price. The example numbers are assumptions;0.361*0.65=0.23465 and multiplying720hours gives168.948, which rounds to168.95. No current market rate or actual earnings claim is inferred.')]:
 add(i,[ref(OUT/'metrics_gpu.yaml',89,105)],why,methods=['STATIC_CONTEXT_REVIEW','CANONICAL_IMPLEMENTATION_SOURCE'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
schemas=[]
for name in ['metrics_gpu.yaml','metrics_gpu_trends.yaml','metrics_gpu_locations.yaml']:
 p=OUT/name
 schemas.append(ref(p,1,len(p.read_text().splitlines()),url=f'https://github.com/vast-ai/docs/blob/bfa926c9421521767fa7411718bd31ea38b38528/api-reference/openapi/yaml/{name}',revision='bfa926c9421521767fa7411718bd31ea38b38528'))
add('CHC-MARKET-METRICS-FRESHNESS-01',schemas,'All three complete pinned definitions were inspected. They define endpoint/request/response structures and an x-rate-limit per-IP frequency hint, but not a public update cadence, cache duration, or per-user allowance. The sentence intentionally avoids converting that hint into a timing guarantee.')
add('MCL-b106578dbaccc269',[],'The checked CLI search ordering is not the console AutoSort algorithm. No retained owner definition or exact console implementation in this review establishes default selection, ranking inputs and randomness together. Obtain the AutoSort implementation/owner definition; a command search result is insufficient.',decision='residual',limit='No new defect is asserted: the complete algorithm statement remains unsupported by the sources inspected. Existing Not in Search prose is not independent proof.')
add('MCL-1cd1cc2855505c7e',[public('dlperf')],'The linked official FAQ directly defines DLPerf as an estimated deep-learning score. The glossary is deliberately narrower than the FAQ performance examples.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
dph=code('vastai/cli/commands/machines.py',265,270)
add('MCL-1bcb7e2c373afcd2',[dph],'The machine-price declaration explicitly uses dollars per GPU per hour. The glossary expands the abbreviation and qualifies the common compute-price usage without asserting fee, tax or payout treatment.')
service=ref('verification/evidence/2026-09-01-host-diagnostics-readonly-attempt-01/result.md',28,40,'RUNTIME_OR_UI_OBSERVATION')
installer_default=ref(OUT/'installer-1405-1405.txt',1,url='https://console.vast.ai/install',revision='sha256:6b00488ccf837ed6b7b5375270b75db284c3906f6aec832ad9c8573f44eaac6c')
installer_open=ref(OUT/'installer-1436-1438.txt',1,3,url='https://console.vast.ai/install',revision='sha256:6b00488ccf837ed6b7b5375270b75db284c3906f6aec832ad9c8573f44eaac6c')
installer_archive=ref(OUT/'installer-219-247.txt',1,29,url='https://console.vast.ai/install',revision='sha256:6b00488ccf837ed6b7b5375270b75db284c3906f6aec832ad9c8573f44eaac6c')
installer_daemonlog=ref(OUT/'installer-1901-1910.txt',1,10,url='https://console.vast.ai/install',revision='sha256:6b00488ccf837ed6b7b5375270b75db284c3906f6aec832ad9c8573f44eaac6c')
add('MCL-2fd86ac820a14d5d',[service,installer_daemonlog],'The retained Host service/journal read shows vastai.service and the retained installer reads the kaalia daemon log in its initialization flow. This supports the service/daemon glossary identity; it does not assert present machine state.',methods=['RUNTIME_OR_UI_OBSERVATION','CANONICAL_IMPLEMENTATION_SOURCE'])
add('MCL-32d82f5e40edc067',[public('cli_link')],'This is a standalone navigational link to an official console route. Source/route inspection is proportionate; the exact literal does not claim installation or authentication completed. The public fetch exposed only the shell, so no authenticated screen details are inferred.',methods=['STATIC_CONTEXT_REVIEW'],classification='EDITORIAL_STATIC_API_ROUTING')
host_api=code('vastai/api/machines.py',1,31)
add('MCL-0eacd4728ea36c84',[host_api,diag,public('api_keys')],'Host reads use owner=me and the diagnostic specifically asks for an account that owns or can inspect the Host. Matching owner/team permissions is access advice; it does not assert a present team membership or key grant.',methods=['CANONICAL_IMPLEMENTATION_SOURCE','AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-b3e9fdd5c4698cd3',[public('keys'),public('api_keys'),redaction],'Official key guidance provides reset/rotation through the Keys page; the prohibition on sharing credentials is conservative handling advice. It makes no claim that a rotation or revocation was performed.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-95d8c362e5ebc79f',[installer_default,installer_open],'The retained installer defaults to a relative filename then resolves it in the launch directory, but --logfile can override it. Qualify the universal statement as default behavior.',decision='correction',replacement='By default, the installer writes `vast_host_install.log` in the directory where you launched it. The `--logfile` option can set a different path.')
add('MCL-275ad9daca24ba6c',[installer_archive],'The complete literal is explicitly conditional. The source can create vastai_install_logs.tar.gz and collect the installer log; the paragraph does not promise that every installation creates an archive.')
add('MCL-53625fe44180286a',[installer_daemonlog,service],'The following exact tail fence uses the kaalia.log path read by the installer and successfully read in retained Host diagnostics. This identifies a log location, not guaranteed error completeness.')
add('MCL-9a47d3bb5fa94c59',[installer_default,installer_daemonlog,oldtool(1)],'This support checklist requests relevant available installer/daemon/kernel logs. The sources establish the artifact types and paths; the request does not promise every log exists or contains the failure.',methods=['STATIC_CONTEXT_REVIEW','CANONICAL_IMPLEMENTATION_SOURCE','AUTHORITATIVE_DOCUMENTATION_CITATION'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('MCL-43c8af4794b1f5a5',[public('udp'),owner(58017,31)],'TCP and UDP exposure are independently configured. The full quick-route row identifies the protocol-specific investigation, not a unique diagnosis or repaired public route.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
cuda=code('test_NCCL.py',40,48,repo='self-test')
add('MCL-8644eedd5436393a',[cuda],'The exact message is raised when torch.cuda.is_available() is false inside the tested process. Routing to driver/runtime/container CUDA visibility is appropriate and does not identify one unique Host fault.',methods=declared)
add('MCL-1221941af8a7a4fe',[],'The retained support-tools guide contains the exact bad bandwidthtest2 label and its reporter groups bandwidthtest messages, but neither establishes the full GPU-transfer/PCIe diagnostic meaning. The fetched Hanran catalog does not define this legacy label. Inspect its daemon/test emitter or obtain a focused owner definition; no induced hardware fault is required.',decision='residual',limit='Do not substitute the current NCCL container test for the separate legacy daemon bandwidthtest2 emitter. No failure/recovery outcome is inferred.')
add('MCL-f4b6d52c5154f056',[oldtool(9),oldtool(4)],'This row routes storage-capacity symptoms to a capacity investigation. It does not claim that Docker object usage uniquely explains the error or that a cleanup recovers space.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','STATIC_CONTEXT_REVIEW'])
injection=ref('verification/evidence/2026-09-02-host-gpu-injection-attempt-03/result.md',9,23,'RUNTIME_OR_UI_OBSERVATION')
add('MCL-4880790be6ba445f',[owner(58017,28,30),injection],'The owner recommends the registered nvidia runtime form, and the previously corrected form ran successfully on the retained RTX6000Ada Host after direct --gpus was rejected. This conditional is a next diagnostic command, not a universal fix for CDI faults.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','RUNTIME_OR_UI_OBSERVATION'],limit='Historical tested environment is the September2 idle four-RTX6000Ada Host. Source/sequence reuse supports the conditional diagnostic form; no current Host state or universal CDI recovery is inferred.')
add('MCL-d35784fe85b17d51',[nccl,public('fabric')],'The literal directs readers to the existing nccl_failed heading, whose section includes the named fabric-service checks. It is navigation to the source-defined error, not a new runtime outcome.',methods=['STATIC_CONTEXT_REVIEW','CANONICAL_IMPLEMENTATION_SOURCE'])
add('MCL-f3e7dae0a707f1d0',[oldtool(9),oldtool(4),oldtool(5),cl],'The commands support examining capacity, mount selection and retained objects, but the source does not establish that these are the usual cause in every listed symptom. Replace the unmeasured frequency/diagnosis with an explicit investigation route.',decision='correction',replacement='For full client storage, `no space left on device`, or missing expected disk space, check Docker storage capacity and the mount location. Review space used by images, stopped containers, volumes, and expired rental data before choosing a cleanup action.',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('CUR-958cf6cbe25a6f9a',[oldtool(2),installer_daemonlog],'The command shows at most the last100lines of one daemon log, which may not include the actual crash error. Replace the categorical actual-error assertion with qualified inspection advice.',decision='correction',replacement='Show up to the last 100 lines of the Vastai daemon log. Look for relevant messages before the service exited or crashed; the cause may also require the service journal or kernel logs:',methods=['STATIC_CONTEXT_REVIEW','AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
add('CUR-ee46b4e9a6417e1a',[oldtool(2),installer_daemonlog,service],'The exact tail command uses the source-defined daemon path and the documented -n100 option; it also matches retained successful collection. This is log retrieval only, not proof that a failure cause is present.',methods=['AUTHORITATIVE_DOCUMENTATION_CITATION','CANONICAL_IMPLEMENTATION_SOURCE'])
add('CUR-a8e9eacd3b6e388b',[installer_daemonlog,hostbundle],'The source consistently reads kaalia.log and optionally kaalia.log* files; the specific literal kaalia.logX is not established as the full log filename. Point to the known main log and qualify rotated logs by availability.',decision='correction',replacement='- The Vastai daemon log, `/var/lib/vastai_kaalia/kaalia.log`, and relevant rotated `kaalia.log*` files when available.',methods=['CANONICAL_IMPLEMENTATION_SOURCE','STATIC_CONTEXT_REVIEW'],classification='REVIEWED_ADVICE_WITH_FACTUAL_INPUTS')
# The public import path reaches the SDK implementation, including the self-test stub.
DEC['MCL-39d956b828a766be']['source_refs'].append(code('vastai/__init__.py',24,24))
# Public state remains scoped to retained historical observations; no re-execution.
DEC['MCL-b106578dbaccc269']['source_refs'].append(code('vastai/cli/commands/offers.py',25,35))
secondary=[]
for rel,start,end in [('support-tools/agent_support/knowledge/fleet_database_guide.md',120,126),('support-tools/fleet_assessment/fleet_report.py',51,57)]:
 p=Path('/Users/hanneszietsman/VastAi/source-snapshots/20260624-con1531')/rel
 target=OUT/(p.name+'.excerpt.txt');target.write_text('\n'.join(p.read_text().splitlines()[start-1:end])+'\n')
 rr=ref(target,1,end-start+1,'SECONDARY_SOURCE_CONTEXT');rr.update(original_path=str(p),original_sha256=sha(p),original_line_range=[start,end],limit='Secondary support-tools catalog/report, retainedJune24; establishes label presence/classification only, not the daemon emitter GPU-transfer semantics.')
 secondary.append(rr)
DEC['MCL-1221941af8a7a4fe']['source_refs'].extend(secondary)
for d in DEC.values():
 if d['decision']=='supported':d['next_action']='Retain the exact source binding and recheck this assertion if the source or wording changes; no duplicate live run is needed for this review scope.'
