from pathlib import Path
import json,hashlib,datetime
B=Path('/Users/hanneszietsman/VastAi/CON-1584/docs-pr185-closure-20260914'); P=B/'verification/evidence/2026-09-15-host-unvalidated-source-families-attempt-01/s1'; S=json.loads((P/'sources.json').read_text())['sources']; D=json.loads((P/'decisions.json').read_text()); C=json.loads((B/'verification/current-host-docs-review.json').read_text())['pages'][15]['claims']; items={x['id']:x for x in D['decisions']}
def ref(key,a,z):
 ls=(B/S[key]['path']).read_text().splitlines();return {'source':key,'locator':f'L{a}-L{z}','text_pointer':f'/lines/{a}-{z}','source_excerpt':'\n'.join(ls[a-1:z])}
def jr(key,pointer):
 v=json.loads((B/S[key]['path']).read_text());
 for part in pointer.strip('/').split('/'):v=v[int(part)] if isinstance(v,list) else v[part]
 return {'source':key,'json_pointer':pointer,'source_excerpt':v}
def add(i,refs,rationale,decision='supported',replacement=None,limit=None,next_action=None,status=None,method_reason=None):
 c=C[i];assert c['status']=='UNVALIDATED'; x={'id':c['id'],'literal_sha256':hashlib.sha256(c['text'].encode()).hexdigest(),'location':c['spans'][0],'decision':decision,'source_refs':refs,'support_rationale':rationale,'limitation':limit or 'Source-defined behavior or diagnostic recommendation at the pinned revisions; no new host run, fault occurrence, successful repair, deployment qualification, or human acceptance is claimed.','next_action':next_action}
 if replacement is not None:x['proposed_replacement']=replacement;x['proposed_replacement_sha256']=hashlib.sha256(replacement.encode()).hexdigest();x['next_action']=next_action or 'Apply the complete replacement and, if generator-owned, update the matching generator wording in the same change; keep immutable source pins unchanged.'
 if decision!='residual':
  x['proposed_methods']=['CANONICAL_IMPLEMENTATION_SOURCE','REPOSITORY_STATIC_CHECK'];x['proposed_classification']='REVIEWED_TECHNICAL_DECLARATION';x['method_rationale']=method_reason or rationale+' Review establishes this definition/recommendation, not execution on every host.'
 if status:x['proposed_status']=status
 items[c['id']]=x

def save():
 D['decisions']=sorted(items.values(),key=lambda x:x['location']['start']);D['reviewed_count']=len(items);D['reviewed_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();D['source_index_sha256']=hashlib.sha256((P/'sources.json').read_bytes()).hexdigest();(P/'decisions.json').write_text(json.dumps(D,indent=2)+'\n');print('saved',len(items))

add(1,[ref('machines',699,716),ref('machines',994,1015)],'CLI command is a check and workload entry point; no comparative speed evidence establishes “quickest”, and its pinned thresholds must not be equated with every platform policy.','correction','The host self-test checks a listed machine against the CLI’s preflight requirements and runs a temporary diagnostic workload.')
add(2,[ref('machines',919,955),ref('machines',994,1015),ref('machines',1101,1134),ref('machines',1313,1323),ref('machines',1585,1620)],'Normal control flow selects an offer, gates creation, polls progress and attempts cleanup; cleanup exceptions explicitly warn about a still-running instance.','correction','When you run `vastai self-test machine <machine>`, the CLI selects a rentable offer for that machine and checks its preflight requirements. If those checks pass, it rents one temporary diagnostic instance, starts the self-test image, polls its progress endpoint, reports the result, and attempts to destroy the instance. Check any cleanup warning and destroy the temporary instance manually if cleanup failed.')
add(3,[ref('published_verification',11,22)],'Published guidance requires both baseline and health/stability checks; a CLI pass alone must not promise eligibility or immediate verification.','correction','Passing this self-test alone does not guarantee verification. The platform also evaluates ongoing health, reliability, supply and demand, and its other verification criteria.')
add(4,[ref('machines',729,732),ref('machines',994,1015),ref('machines',1626,1633)],'The CLI warning explicitly limits ignored requirements to diagnostic use and rejects verification qualification.')
add(5,[ref('machines',994,1015),ref('machines',1510,1563)],'The command separates preflight diagnostics from its instance/runtime phase; the statement describes that output structure.')
add(6,[ref('machines',994,1015),ref('machines',1411,1415),ref('published_verification',11,22)],'Normal success means CLI preflight plus runtime success, but platform eligibility also requires independent health/stability evaluation.','correction','| Normal pass | The CLI preflight checks and runtime workload passed. This result alone does not guarantee platform verification. | Keep the host stable and listed. Verification remains automated and also depends on the platform’s other criteria. |')
add(7,[ref('machines',994,1015),ref('machine_diag',533,540)],'Required-check failure returns before create-instance in the normal flow; rerunning without the bypass is the corresponding gate check.')
add(8,[ref('runtime_diag',75,110),ref('machines',1101,1166)],'Runtime-failure diagnostics include create-instance and startup errors before the image executes; the current row incorrectly guarantees successful launch.','correction','| Runtime failure | The CLI could not complete instance creation, startup, progress collection, or a runtime test stage. The failure code and stage show how far the run reached. | Use the failure code, last reported stage, and available diagnostic bundle to choose the next check. |')
add(9,[ref('machines',729,732),ref('machines',994,1015)],'The same checks are computed and failures recorded even with the flag; only enforcing them as a pass/fail gate is skipped.','correction','| Pass with `--ignore-requirements` | The runtime workload passed, but the CLI did not enforce its preflight requirements as a pass/fail gate. This does not qualify the machine for verification. | Treat this as runtime validation only. Rerun without `--ignore-requirements` to check the normal preflight gate. |')
add(10,[ref('machines',729,732),ref('machines',994,1015),ref('machines',1411,1415)],'A successful runtime result concerns the tested workload; the explicit ignored-requirements warning prevents transferring that outcome to qualification.')
add(11,[ref('machines',994,1015),ref('machines',1101,1134)],'The source proves a return before instance creation, not an independent account-wide billing guarantee.','correction','These checks run before the CLI rents the temporary self-test instance. Failed required checks stop the normal flow before that instance is created.')
add(12,[ref('machine_diag',167,178)],'The full CUDA row matches the implemented threshold and source-authored purpose; Console confirmation is an editorial way to inspect the listed/healthy state, not a guaranteed driver repair.')
add(13,[ref('machine_diag',179,189)],'The strict greater-than reliability comparison and its guardrail/stabilization guidance match the complete canonical check.')
add(14,[ref('machine_diag',157,161),ref('machine_diag',190,206)],'The minimum, listed-GPU multiplier, purpose and conditional symmetric-protocol guidance match the complete canonical check.')
add(15,[ref('machine_diag',207,217)],'The strict PCIe threshold, units, possible failure impact and BIOS/slot triage match the complete canonical check.')
add(16,[ref('machine_diag',218,228),ref('util',706,719)],'The full formula is the unrounded required_inet_mbps result used by the download comparison; the rest of the row is the canonical declared purpose/advice.')
add(17,[ref('machine_diag',229,239),ref('util',706,719)],'The upload comparison uses the same unrounded machine-total VRAM formula; purpose and prescribed triage match the source.')
add(18,[ref('machine_diag',38,48),ref('machine_diag',240,250)],'The executable conversion/comparison uses GiB. The purpose inherited “GB”, which is a different unit; correct that single unit consistently.','correction',C[18]['text'].replace('7 GB of VRAM','7 GiB of VRAM'))
add(19,[ref('machine_diag',23,26),ref('machine_diag',162,163),ref('machine_diag',251,267)],'Threshold uses machine-total VRAM in MiB with a 2,000,000 MiB cap; purpose and remedial advice match the declared check. “About 2 TB” is an approximation, with exact MiB already stated.')
for i in [20,50]:
 refs=[ref('machine_diag',151,164),ref('machine_diag',269,277),ref('systemreq',28,45),ref('remote',345,358),jr('cpu_owner','/comment/body'),ref('generator',215,253)]
 add(i,refs,'SOURCE_VERSION_CONFLICT: the literal says the tester requires one physical CPU core per GPU, but pinned CLI requires 2 × listed GPUs using offer.cpu_cores; pinned image source uses 2 × visible GPUs using physical psutil.cpu_count(logical=False). Hanran Yang’s retained June 16 owner guidance requires one physical core per GPU, but does not establish implementation alignment. Generator overrides the source-derived threshold to one.','residual',limit='This fails as a claim about the pinned tester, not as a rejection of the owner’s one-physical-core product requirement. The runtime row also presents PyTorch process allocation counters as global free VRAM; exact memory-scope wording needs alignment.',next_action='Source owner must identify or implement the CLI/image revisions that enforce the approved one-physical-core rule and define how the offer CPU counter maps to physical cores; then regenerate the CPU rows together against those exact revisions. Preserve the owner requirement meanwhile.',status='FAIL')
add(21,[ref('machine_diag',157,161),ref('machine_diag',280,302),ref('machine_diag',306,307)],'Source proves the CLI advisory threshold is informational. Its hardcoded explanation alone does not prove the backend’s universal per-instance port maximum.','correction','| `network.direct_ports.recommended_max`<br />Direct port count advisory | Advisory: direct ports &lt;= 64 * listed GPUs | The CLI flags counts above 64 ports per listed GPU as an advisory about oversized mappings. | This is advisory only, not a self-test gate. Keep enough direct ports for self-test and normal workloads, and review very large unused ranges. |')
add(23,[ref('remote',14,18),ref('machines',1313,1323),ref('machines',1516,1544)],'The runtime binds container TCP 5000; the CLI uses public_ipaddr and the HostPort mapping rather than connecting to container port 5000 directly.')
add(24,[ref('machine_diag',157,160),ref('machine_diag',190,206)],'The numeric minimum and listed-GPU denominator match the executable preflight gate.')
add(25,[ref('machine_diag',157,161),ref('machine_diag',280,302)],'Source proves the advisory threshold, but source-authored guidance alone is not independent backend port-cap authority.','correction','- Advisory: the CLI flags more than 64 direct ports per listed GPU as an oversized mapping. This advisory does not fail the self-test.')
add(26,[ref('runtime_diag',123,132)],'Canonical unreachable-endpoint remediation explicitly says to forward the mapped public TCP port to the host LAN IP.')
add(27,[ref('machine_diag',202,205)],'The conditional TCP/UDP symmetry recommendation exactly matches canonical remediation; it does not assert UDP is used by the HTTPS progress request.')
add(28,[ref('machines',1434,1446),ref('runtime_diag',275,306)],'Endpoint diagnostic stores/reports the actual external mapping and the failure guidance directs checking its NAT/firewall path.')
add(29,[ref('runtime_diag',123,132),ref('machines',1443,1446)],'Source explicitly identifies same-LAN hairpin failure as a possibility and recommends an outside-network retry; this is a discriminating check, not proof every failure is hairpinning.')
add(30,[ref('runtime_diag',275,306),ref('machines',1523,1544)],'The endpoint object records the attempted progress mapping and all reported mappings, but does not test every direct port. No source establishes which future backend mechanism is mandatory.','correction','The CLI can report the external progress port it tested when that mapping is available. That result is not a scan of every direct port; the self-test does not provide a per-port failure list for the entire configured range.')
add(31,[ref('util',706,719)],'Both thresholds call the same total-VRAM-scaled function with a floor and cap; the following table supplies the bounded arithmetic details.')
save()

for i,ver,torch,target,platform,makerange in [
 (40,'11.8','2.7.1','Pre-sm_70 (Maxwell, Pascal); legacy GPU target','linux/amd64',(34,44)),
 (41,'12.8','2.10.0','sm_70+ (Volta and newer)','linux/amd64, linux/arm64',(46,54)),
 (42,'13.0','2.11.0','sm_75+ (Turing and newer)','linux/amd64, linux/arm64',(56,64)),
 (43,'13.3','2.12.0','sm_75+ (Turing and newer); PyTorch index `cu132`','linux/amd64, linux/arm64',(66,74))]:
 add(i,[ref('machines',1017,1079),ref('image_dockerfile',8,23),ref('image_dockerfile',68,75),ref('image_makefile',14,20),ref('image_makefile',*makerange)],f'CLI source declares the {ver} v2 tag; image build source declares the PyTorch pin, architecture targets and build platforms. Current unqualified cells could imply those mutable tags were inspected or paid-qualified, which was not established.','correction',f'| `vastai/test:self-test-v2-cuda-{ver}` (CLI-selected tag) | Build pin: {torch} | Build target: {target} | Build platforms: {platform} |',limit='Source mapping/build declaration only. No registry existence, immutable image digest, successful build, contents of the mutable v2 tag, or actual GPU/driver/platform compatibility is established. The source Makefile default prefix is self-test-cuda-, while the CLI selects self-test-v2-cuda-; prefix equivalence must not be inferred.',next_action='Apply source-declaration wording to the generated row and matching generator output. Add one table-level note that build declarations are not image publication or compatibility evidence; do not change any runtime tag.')
add(44,[ref('machines',1017,1079)],'“Selection rules:” is an editorial lead-in; following rule occurrences carry their own source proof.',status='NOT_APPLICABLE')
items[C[44]['id']]['proposed_methods']=[];items[C[44]['id']]['proposed_classification']='EDITORIAL_SCOPE_OR_LEAD_IN'
add(46,[ref('machines',1029,1047),ref('image_dockerfile',8,14)],'The explicit compute-capability branch caps the CUDA selection at 12.8 below 750, and both CLI/build source document Volta wheel support as the reason. This verifies the source-selected rule and its declared rationale, not every published wheel or image.')
add(48,[ref('machines',994,1015),ref('machines',1101,1134),ref('machines',1516,1529),ref('remote',16,18)],'The ordinary post-preflight path starts the selected image and connects through the external mapping for container TCP 5000; adjacent direct-port context already distinguishes container and external ports.')
add(49,[ref('remote',24,30),ref('remote',219,243)],'Event is emitted before torch import, and its purpose/last-event guidance match the runtime event catalog. This is the declared event meaning, not evidence that the HTTPS listener has accepted an external connection.')
add(51,[ref('remote',37,42),ref('remote',440,463),ref('resnet',13,31),ref('resnet',46,97)],'Runner launches the ResNet18 workload over visible CUDA devices and exits on the first successful tested batch; event purpose and remediation exactly match the complete row.')
add(52,[ref('remote',43,48),ref('remote',465,488),ref('ecc',7,41)],'Allocation sizes use integer element counts and a floored square dimension, so exact 95% allocation is not guaranteed; the stage deliberately targets approximately 95%.','correction',C[52]['text'].replace('The test allocates 95% of total memory on each visible GPU.','The test targets approximately 95% of total memory on each visible GPU and passes only if the allocations succeed.'),limit='Verifies allocation algorithm and stage success condition; this is not a hardware ECC certification or evidence of all-memory error detection.')
add(53,[ref('remote',49,54),ref('remote',521,546),ref('nccl',40,79),ref('nccl',105,153)],'NCCL stage demands at least one GPU, launches one rank per visible GPU on one machine, and synchronizes ranks; event guidance matches the source. This defines the test criterion without asserting a successful run.')
add(54,[ref('remote',55,60),ref('remote',553,588),ref('remote',605,618)],'Both subprocesses launch before collection, receive 60-second durations, and the stage passes only when both return zero; purpose and triage match the event catalog.')
add(55,[ref('remote',61,66),ref('remote',402,409)],'Final summary explicitly encodes overall status and exit code; purpose and remediation exactly match the canonical event.')
add(56,[ref('machine_diag',6,20),ref('machine_diag',339,345),ref('machine_diag',469,482),ref('machine_diag',520,540)],'Code constants, returned failures and confidence-bearing heuristic implement stable preflight identifiers and likely root states; the literal correctly preserves uncertainty.')
add(57,[ref('machine_diag',339,345),ref('machine_diag',520,529)],'Current source proves attempted state disambiguation, but this review has no immutable previous implementation comparison supporting the historical “old” wording.','correction','The CLI uses visible offer and machine state to suggest a likely reason before giving guidance. Treat the reported root state as a diagnostic hint, with the confidence and evidence shown in the output.')
add(58,[ref('machine_diag',339,345)],'The following items are hypotheses from a deliberately heuristic lookup, not proven root causes.','correction','Possible states inferred from CLI-visible data:')
add(59,[ref('machine_diag',373,387)],'In the surrounding list of possible states, visible rented=true offers support currently-rented as a candidate explanation; source returns medium confidence.')
add(60,[ref('machine_diag',339,345),ref('machine_diag',432,444)],'No offers returned to this account is weaker than proving zero active offers exist globally.','correction','- The machine is visible, but no active on-demand offers are visible to the API account.')
add(61,[ref('machine_diag',446,466)],'Offline, unlisted and account-invisible are explicitly alternative possibilities; source preserves low confidence when it lacks authoritative machine state.')
add(62,[ref('machine_diag',389,418)],'Reliability, verification fields, nonzero vericode and error metadata are the exact signals supporting this possible quality-gate state; no claim identifies a specific backend cause.')
add(63,[ref('machine_diag',356,370),ref('machine_diag',477,483)],'401 and invalid/expired keys are included, so it is wrong to assert authentication has necessarily succeeded.','correction','- The API key or account cannot inspect the required host or offer state; check both key validity and permissions.')
add(64,[ref('machine_diag',348,350),ref('machine_diag',373,418),ref('machine_diag',432,459)],'The recommended state checks correspond to the actual signals and corrective questions in CLI diagnostics. Console is a customer-facing inspection route, not an assertion that the CLI proves these states.')
add(65,[ref('machine_diag',496,518)],'no_offer summary matches the canonical failure; the next step checks the online/listed/visibility conditions named in its causes.')
add(66,[ref('machine_diag',484,495)],'Visible broad offers with no rentable strict selection produce no_rentable_offer; waiting or inspecting state corresponds to its declared causes and remediation.')
add(67,[ref('machine_diag',356,371),ref('machine_diag',477,483)],'The row correctly describes inability to inspect state rather than promising successful authentication; account/key visibility remediation matches the source.')
add(68,[ref('machine_diag',533,540),ref('machines',994,1015),ref('machines',729,732)],'Stable code and failed-check semantics match normal preflight gating; optional ignored-requirement continuation is explicitly restricted to runtime diagnostics.')
add(69,[ref('machine_diag',373,387)],'The root-state row describes exactly the visible-offer/rented flag condition; surrounding heuristic context prevents treating it as independently verified machine-wide occupancy.')
add(70,[ref('machine_diag',389,418)],'This root-state row lists each source predicate and says the metadata points to a gate, preserving inference rather than claiming the exact backend rule.')
add(71,[ref('machine_diag',339,345),ref('machine_diag',432,444)],'The machine lookup is visible but the offer search is account-scoped; the current assertion of no active listed offers exceeds what source says it can prove.','correction',C[71]['text'].replace('The machine is visible, but no active on-demand offers are listed for it.','The machine lookup is visible, but no on-demand offers were returned to this API account. This is a likely state, not proof that no offers exist.'))
add(72,[ref('machine_diag',446,466)],'The row preserves alternatives and “appears”; no specific offline/unlisted state is asserted beyond the CLI visibility heuristic.')
add(73,[ref('machine_diag',420,430)],'Visible offers without a classified reason map directly to this low-confidence state and refresh/inspection recommendation.')
add(77,[ref('runtime_diag',1,14),ref('runtime_diag',15,63)],'Runtime diagnostics module defines the named stable catalog identifiers for host-facing output; this is an interface definition.')
add(78,[ref('machines',1434,1490)],'Progress timeouts distinguish never reachable, empty output and lost connection. Source gives possible causes, not frequency evidence that connectivity/startup is usually responsible.','correction','A `no response` or progress timeout means the CLI did not receive usable progress from the temporary self-test instance. Check whether the endpoint was never reachable, returned no output, or became unreachable after connecting; then use the failure code and last stage to guide diagnosis.')
add(79,[ref('machines',1443,1446),ref('machines',1461,1464),ref('machines',1481,1484)],'List introduces candidate causes without evidence about prevalence.','correction','Possible causes to check:')
add(80,[ref('runtime_diag',123,132)],'Canonical unreachable-endpoint advice requires mapped public TCP forwarding to the host LAN IP, so an incorrect target is an appropriate candidate cause.')
add(81,[ref('runtime_diag',123,132),ref('machines',1443,1446)],'The literal enumerates conditional network-path possibilities expressly named by the CLI; it is not a diagnosis of a tested host.')
add(82,[ref('machines',1443,1446),ref('machines',1481,1484)],'Failure guidance expressly includes an unstarted/unbound progress server and container crash/exit as possible causes.')
add(83,[ref('runtime_diag',167,172),ref('machines',1461,1464)],'The catalog identifies container/daemon startup problems and directs inspection of Docker/OCI/NVIDIA runtime/host daemon; startup stall is a triage possibility, not observed damage.')
add(84,[ref('machines',1461,1464),ref('machines',1481,1484)],'Source explicitly lists GPU hangs, host stalls and resets among absent-progress possibilities; the instruction makes no successful repair assertion.')
add(85,[ref('runtime_diag',133,142),ref('machines',1481,1484)],'The endpoint-lost catalog and runtime guidance name network loss between CLI and host as a possible absent-response cause.')
add(86,[ref('runtime_diag',123,142)],'“First checks:” is an editorial lead-in to separately assessed diagnostic instructions.',status='NOT_APPLICABLE');items[C[86]['id']]['proposed_methods']=[];items[C[86]['id']]['proposed_classification']='EDITORIAL_SCOPE_OR_LEAD_IN'
add(87,[ref('machines',819,856),ref('machines',1434,1442)],'Failure output records the diagnostic code, stage and actual tested endpoint when known, which supports this read-only inspection instruction.')
add(88,[ref('runtime_diag',123,132)],'The complete instruction directly follows the canonical mapped-public-port-to-host-LAN-IP remediation.')
add(89,[ref('machines',578,609),ref('machines',760,803)],'When an instance ID exists, CLI attempts the named instance/log API collections and records individual collection errors. “Inspect ... when existed” is an inspection recommendation, not a guarantee all three files were collected.',limit='Bundle may omit failed API collections; review collection-errors.json. No new instance log access or host-local collection was performed.')
add(90,[ref('runtime_diag',123,132)],'The outside-network retry is the exact canonical recommendation to distinguish NAT hairpin behavior; it does not promise every other network configuration is correct.')
add(113,[ref('runtime_diag',244,250),ref('runtime_diag',370,393),ref('remote',490,519)],'The parser classifies NCCL by stage or broad error text, and the runtime may fail GPU visibility before NCCL starts; it need not be a multi-GPU initialization failure.','correction','`nccl_failed` is the CLI’s NCCL-related failure classification, based on the runtime stage or error text. Inspect the original error and last stage: the code alone does not prove that NCCL initialized, that more than one GPU was visible, or that one specific subsystem caused the failure.')
add(117,[ref('machines',775,803),ref('support',39,41),ref('support',192,215)],'Failure calls best-effort bundle creation, but filesystem/collection errors can prevent the tarball; the current unconditional assertion is too strong.','correction','When a self-test fails, the CLI attempts to build a redacted diagnostic tarball unless bundle creation is disabled. Check the reported path or bundle-creation warning.')
add(121,[ref('machines',612,638),ref('machines',640,678)],'The exact manual command/parser and default CLI-visible collection boundary match the instruction; no host-local artifacts are enabled by default.')
add(122,[ref('machines',616,634),ref('support',228,231)],'The flag explicitly enables local OS/kaalia collection and help warns it reads the executing machine, requiring the actual host.')
add(123,[ref('support',219,252),ref('machines',578,609),ref('machines',775,797)],'Normal self-test call supplies result/output and bundle always adds manifest/errors; runtime API collections are expressly conditional (“can also include”).',limit='File/API collection can fail, and output.log is omitted if no CLI output exists; this describes the normal recorded self-test bundle, not universal artifact availability.')
add(124,[ref('machines',626,634),ref('support',130,164),ref('support',176,185),ref('support',244,249)],'Collector reads local paths/subprocesses only; machine_id does not redirect them to the host. The manifest expressly identifies local-host versus daemon/backend collection as the boundary.')
add(125,[ref('support',19,30),ref('support',48,74),ref('support',254,263),ref('support',275,290)],'Constants are 262144 but JSON artifacts bypass final truncation and truncation prefixes can exceed that byte count. The blanket byte-cap assertion is false; redaction is pattern/explicit-secret based.','correction','The bundle uses 262,144-byte truncation limits for collected text/log content; truncation notices can add bytes, and JSON artifacts are not uniformly capped by that limit. It redacts recognized secret fields, assignments, and explicitly supplied secrets, but hosts should still review the tarball before sharing it with support.')
save()

# The additional records are shared retained sources, not copies of the model.
S=json.loads((P/'sources.json').read_text())['sources']
add(75,[jr('vericode_guide','/excerpt'),ref('owner_errors',14,25)],'The Vast support-tools field guide documents bit8 as error_msg and names daemon/CDI/PCIe examples; Hanran Yang’s dated primary error catalog distinguishes public-port networking from NVIDIA/Docker/CDI/PCIe and other machine errors. Together these support interpreting the exact message rather than treating vericode8 as a port-only code.',limit='Dated documented field mapping and primary Engineering error definitions; not a direct inspection of the current backend producer, current machine state, full live catalog, or evidence that a suggested repair succeeds.')
items[C[75]['id']]['proposed_methods']=['PRIMARY_ENGINEERING_SOURCE','REPOSITORY_STATIC_CHECK'];items[C[75]['id']]['method_rationale']='The occurrence defines a documented status field and directs message-specific triage. Exact retained field-guide plus primary Engineering catalog comparison is suitable; a live aggregate of vericode values without error_msg would not prove this definition.'
add(76,[ref('owner_errors',16,17),ref('owner_error_checks',31,31),ref('machine_diag',202,205),ref('runtime_diag',123,132)],'Engineering explicitly names inbound advertised-range failure, firewall/NAT, CGNAT and double NAT. CLI guidance supplies LAN target and protocol symmetry. Checking that the configured range is current is a diagnostic recommendation, not a claim about a specific stale-range detector.',limit='Supports the checklist of possible network-path/configuration causes. Does not establish the present public IP, current router configuration, external reachability, or a successful repair; the two linked local routes exist but their entire content is outside this occurrence.')
items[C[76]['id']]['proposed_methods']=['PRIMARY_ENGINEERING_SOURCE','CANONICAL_IMPLEMENTATION_SOURCE','REPOSITORY_STATIC_CHECK']
add(114,[ref('runtime_diag',173,178),ref('runtime_diag',191,196),ref('remote',37,54),ref('owner_error_checks',20,20),jr('nvidia_primary','/sources/nccl'),jr('nvidia_primary','/sources/nv_smi')],'The complete diagnostic instruction combines canonical NCCL/NVML/ResNet triage, Engineering enumeration/bus-error guidance, and NVIDIA’s primary peer-communication/topology troubleshooting. Each item is an investigation step, not a uniquely identified cause.')
items[C[114]['id']]['proposed_methods']=['CANONICAL_IMPLEMENTATION_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION','REPOSITORY_STATIC_CHECK']
add(115,[jr('nvidia_primary','/sources/fabric'),ref('remote',490,546)],'NVIDIA documents the Host service and platform-specific FM/NVLSM behavior; the pinned runtime only observes GPU enumeration/NCCL process outcome, not Host systemd status. In the stated NVSwitch context this is an appropriate host-side diagnostic boundary.',limit='Applicable NVSwitch generations differ; checking the relevant installed service does not require assuming NVLSM on every HGX/DGX machine. No current Fabric Manager/NVLSM health is claimed.')
items[C[115]['id']]['proposed_methods']=['CANONICAL_IMPLEMENTATION_SOURCE','PUBLISHED_VENDOR_DOCUMENTATION','REPOSITORY_STATIC_CHECK']
add(116,[jr('nvidia_primary','/sources/fabric'),jr('nvidia_primary','/sources/journalctl'),jr('nvidia_primary','/sources/nv_smi'),jr('prior_tools','/sources/7')],'The four commands are read-only inspection syntax: service status, that service’s last24hours of retained journal, supported query fields filtered around Fabric headings, and the GPU/NIC topology matrix. Source review establishes their diagnostic purpose; no output or healthy-service result is asserted.',limit='Run on the actual applicable NVSwitch host with permission to read system status/journal (use sudo if necessary). Missing service, unavailable journal, unsupported fields or grep exit1 are not healthy results; -A2 shows only a partial Fabric excerpt. Driver output formatting varies. No fresh command execution was performed.',method_reason='This fence specifies a collection recipe without sample output or a claimed result. Primary command definitions and full-argument inspection can verify that recipe; an induced NCCL failure is irrelevant and a healthy status run would not prove fault repair.')
items[C[116]['id']]['proposed_methods']=['PUBLISHED_VENDOR_DOCUMENTATION','REPOSITORY_STATIC_CHECK'];items[C[116]['id']]['proposed_classification']='REVIEWED_DIAGNOSTIC_RECIPE'
# Normalize all exact JSON selectors for the existing reviewer UI.
for d in items.values():
 for r in d['source_refs']:
  if 'json_pointer' in r:r['text_pointer']=r['json_pointer']
D['state']='COMPLETE_PENDING_INDEPENDENT_ROOT_REVIEW';D['counts']={k:sum(x['decision']==k for x in items.values()) for k in ['supported','correction','residual']};D['proposed_status_counts']={'FAIL':sum(x.get('proposed_status')=='FAIL' for x in items.values()),'NOT_APPLICABLE':sum(x.get('proposed_status')=='NOT_APPLICABLE' for x in items.values())};D['no_live_execution']=True;D['all_full_current_literals_reviewed']=True
save()
assert len(items)==110
# Verify every source remains hash-bound and each excerpt resolves exactly.
for k,s in S.items():assert hashlib.sha256((B/s['path']).read_bytes()).hexdigest()==s['sha256'],k
for d in items.values():
 for r in d['source_refs']:
  p=r['text_pointer'];source=B/S[r['source']]['path']
  if p.startswith('/lines/'):
   a,z=map(int,p.split('/')[-1].split('-'));v='\n'.join(source.read_text().splitlines()[a-1:z])
  else:
   v=json.loads(source.read_text())
   for part in p.strip('/').split('/'):v=v[int(part)] if isinstance(v,list) else v[part]
  assert v==r['source_excerpt'],(d['id'],r['source'],p)
print('110/110 exact source selectors resolved;',D['counts'])
