import fs from 'node:fs';import path from 'node:path';import {pathToFileURL}from'node:url';import{execFileSync}from'node:child_process';
const dir='verification/evidence/2026-09-14-payout-terms-correction-attempt-01',name=process.argv[2];
if(!/^offline-[0-9]+$/.test(name))throw Error('Unique offline attempt required');const out=dir+'/'+name+'.json';if(fs.existsSync(out))throw Error('Refuse overwrite');
const started_at=new Date().toISOString(),session='payout-terms-offline-review';
const browser=(...args)=>execFileSync('agent-browser',['--session',session,...args],{encoding:'utf8',maxBuffer:20*1024*1024,timeout:45000});let observation,error=null;
try{browser('open',pathToFileURL(path.resolve('verification/host-docs-review.html')).href);browser('wait','--fn','!!document.querySelector("#search")');
const js=`(()=>{const id='MCL-06956d724f70d2a3',data=JSON.parse(document.getElementById('report-data').textContent),claim=data.claims.find(c=>c.id===id);document.getElementById('clear').click();document.getElementById('status').value='ALL';const search=document.getElementById('search');search.value=id;search.dispatchEvent(new Event('input'));const card=document.querySelector('.claim');const initial=card?.innerText||'';const basis=[...card.querySelectorAll('[data-basis]')],proof=[];for(const b of basis){b.click();const body=document.getElementById('viewer-body'),text=body.textContent;proof.push({index:b.dataset.basis,open:document.getElementById('viewer').open,sourceLink:!!body.querySelector('a[href="https://vast.ai/terms"]'),hasExactSource:/DISCLAIMER OF WEBSITE|MISCELLANEOUS|LIMITATIONS OF LIABILITY/.test(text),hasFingerprint:text.includes('SHA-256'),hasScope:/particular payout|enforceability|published Terms|Published Terms/.test(text)});document.getElementById('close-viewer').click();}card.querySelector('[data-passage]').click();const passage=document.querySelector('.source-line.highlight')?.textContent;const checks={claimPass:claim.status==='PASS',noMissingCitationFinding:!initial.includes('Missing authoritative citation'),allThreeSections:basis.length>=3&&proof.every(p=>p.open&&p.sourceLink&&p.hasExactSource&&p.hasFingerprint),exactCustomerPassage:passage?.includes('Terms of Use')&&passage?.includes('certain state laws'),noBlanketExclusion:!claim.text.includes('Vast is not responsible for payout delays'),zeroRemoteResources:performance.getEntriesByType('resource').length===0};return {checks,claim:{id:claim.id,status:claim.status,text:claim.text,reader_copy:claim.reader_copy},proof,passage,counts:data.counts||null};})()`;
observation=JSON.parse(browser('eval','-b',Buffer.from(js).toString('base64')));}catch(e){error=String(e.message).slice(0,1200);}
const result={started_at,finished_at:new Date().toISOString(),method:'Offline reviewer exact passage and embedded source dialogs; no external retrieval or payout action.',result:!error&&Object.values(observation.checks).every(Boolean)?'PASS':'FAIL',observation,error};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({artifact:out,result:result.result,checks:observation?.checks,error}));process.exitCode=result.result==='PASS'?0:1;
