import fs from 'node:fs';import {execFileSync}from'node:child_process';
const dir='verification/evidence/2026-09-14-payout-terms-correction-attempt-01',name=process.argv[2];
if(!/^(before|after)-[0-9]+$/.test(name))throw Error('Use new before/after attempt name');
const out=dir+'/'+name+'.json';if(fs.existsSync(out))throw Error('Refuse overwrite');
const started_at=new Date().toISOString(),session='payout-terms-local-review';
const browser=(...args)=>execFileSync('agent-browser',['--session',session,...args],{encoding:'utf8',maxBuffer:16*1024*1024,timeout:45000});
let observation,error=null;
try{
 browser('open','http://127.0.0.1:4000/host/payment#payout-account');
 browser('wait','--fn','!!document.querySelector("#__vast_review_host__")?.shadowRoot.querySelector("#current-section-filter")');
 const code=`(async()=>{const id='MCL-06956d724f70d2a3',r=await fetch('/__review__/api/context?path=%2Fhost%2Fpayment'),context=await r.json(),current=context.currentReview,c=current.page.claims.find(c=>c.id===id),shadow=document.querySelector('#__vast_review_host__').shadowRoot;if(!shadow.querySelector('#panel').classList.contains('open'))shadow.querySelector('#pill').click();const card=shadow.querySelector('[data-current-claim="'+id+'"]'),main=document.querySelector('main')||document.body;card.querySelector('[data-show-current-claim]').click();const highlighted=[...(CSS.highlights.get('vast-review-claim')||[])].map(r=>r.toString());const links=[...card.querySelectorAll('a[href*="basis="]')];const evidence=[];for(const link of links){const url=new URL(link.href,location.href);if(url.origin!==location.origin)throw Error('Nonlocal evidence');const response=await fetch(url),text=await response.text();evidence.push({href:url.pathname+url.search,status:response.status,hasSource:text.includes('https://vast.ai/terms'),hasContext:text.includes(id),hasClause:/DISCLAIMER OF WEBSITE|LIMITATIONS OF LIABILITY|MISCELLANEOUS/.test(text),hasLimit:/particular payout|enforceability|published Terms|Published Terms/.test(text)});}const checks={claimPresent:!!c,revisedPass:c.status==='PASS',renderedPass:card.querySelector('[data-status]')?.dataset.status==='PASS',sourceCitationCount:[...main.querySelectorAll('a[href="https://vast.ai/terms"]')].length>=3,qualifiedDelay:main.innerText.replaceAll("’", "'").includes("beyond Vast's reasonable control"),stateLawQualification:main.innerText.includes('some exclusions may not apply under certain state laws'),oldBlanketRemoved:!main.innerText.includes('Vast is not responsible for payout delays, account holds'),exactPassageHighlighted:highlighted.length>0&&highlighted.join(' ').includes('Terms of Use'),noMissingCitationFinding:!card.querySelector('.vv-reader-finding')?.textContent.includes('missing'),exactProofLinks:evidence.length>=3&&evidence.every(e=>e.status===200&&e.hasSource&&e.hasContext&&e.hasClause)};return {checks,claim:{id:c.id,status:c.status,text:c.text,readerCopy:c.readerCopy},highlighted,evidence,sourceHeader:r.headers.get('x-vast-review-source-sha256')};})()`;
 observation=JSON.parse(browser('eval','-b',Buffer.from(code).toString('base64')));
}catch(e){error=String(e.message).slice(0,1200);}
const result={started_at,finished_at:new Date().toISOString(),method:'Rendered localhost exact claim, source citations, highlight and local proof controls; no financial account or payout action.',expected:'The narrowed Terms summary is PASS with three exact source bindings, applicable limits and no blanket payout exemption.',result:!error&&Object.values(observation.checks).every(Boolean)?'PASS':'FAIL',observation,error};
fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({artifact:out,result:result.result,checks:observation?.checks,error}));process.exitCode=result.result==='PASS'?0:1;
