import fs from 'node:fs';import crypto from 'node:crypto';import{execFileSync}from'node:child_process';
const dir='verification/evidence/2026-09-14-payout-terms-correction-attempt-01',name=process.argv[2];
if(!/^final-audit-[0-9]+$/.test(name))throw Error('Unique final-audit attempt required');const out=dir+'/'+name+'.json';if(fs.existsSync(out))throw Error('Refuse overwrite');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>fs.readFileSync(f),json=f=>JSON.parse(read(f)),stable=x=>Array.isArray(x)?x.map(stable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x,equal=(a,b)=>JSON.stringify(stable(a))===JSON.stringify(stable(b));
const baseline=json(dir+'/baseline.json'),before=json(dir+'/pre-correction-model.json'),model=json('verification/current-host-docs-review.json'),claims=m=>new Map(m.pages.flatMap(p=>p.claims.map(c=>[c.id,c]))),bc=claims(before),ac=claims(model),id='MCL-06956d724f70d2a3';
const changes=[...bc].filter(([id,c])=>!equal(c,ac.get(id))).map(([id])=>id),changedFiles=baseline.files.filter(f=>f.type==='file'&&(!fs.existsSync(f.path)||hash(read(f.path))!==f.sha256)).map(f=>f.path),priorEvidence=baseline.files.filter(f=>f.path.startsWith('verification/evidence/')&&!f.path.startsWith(dir+'/'));
const target=ac.get(id),faqId='MCL-9826b26393329d27',faq=ac.get(faqId),source=json(dir+'/terms-source-02.json'),faqSource=json(dir+'/published-payout-faq-01.json'),lines=read('host/payment.mdx').toString().split('\n'),oldLines=read(dir+'/pre-correction-payment.mdx').toString().split('\n');
const checks={twoExactClaimsChanged:equal([...changes].sort(),[id,faqId].sort()),allOtherClaimsUnchanged:bc.size===2013&&ac.size===2013&&changes.length===2,onlyPaymentHostSourceChanged:equal(changedFiles.filter(f=>f.startsWith('host/')),['host/payment.mdx']),onlyApprovedLinesChanged:lines.length===oldLines.length&&equal(lines.flatMap((v,i)=>v===oldLines[i]?[]:[i+1]),[46,98,99,101]),correctTotals:equal(model.counts.claim_statuses,{PASS:313,FAIL:30,BLOCKED:23,NOT_APPLICABLE:87,UNVALIDATED:1560}),boundedPass:target.status==='PASS'&&target.text===lines[45]&&target.required_evidence_types.includes('AUTHORITATIVE_DOCUMENTATION_CITATION'),priorFailurePreserved:target.history.predecessor.status==='FAIL'&&target.history.predecessor.text===bc.get(id).text,sourceBound:target.evidence_refs.every(e=>e.artifact_ref===dir+'/terms-source-02.json')&&target.source_refs.length===3&&target.source_refs.every(s=>s.path==='https://vast.ai/terms'&&/^\/sections\/[012]\/text$/.test(s.locator)),exactSectionHashes:source.sections.every(s=>hash(s.text)===s.text_sha256),faqAttribution:faq.status==='PASS'&&/published.*guidance/i.test(faq.text)&&faq.text.includes('SWIFT')&&/unavailable|not available/.test(faq.text),faqSourceBound:faq.source_refs.some(s=>s.path.startsWith('https://docs.vast.ai/host/payment')&&s.locator==='/text')&&faq.evidence_refs.some(e=>e.artifact_ref===dir+'/published-payout-faq-01.json'),faqPriorSetupPreserved:faq.history.predecessor.text===bc.get(faqId).text,faqSourceHash:hash(faqSource.text)===faqSource.text_sha256,priorEvidenceUnchanged:priorEvidence.every(f=>fs.existsSync(f.path)&&hash(read(f.path))===f.sha256),sourceOwnerGapRemoved:!read('verification/current-source-owner-blockers.md').toString().includes(id),headUnchanged:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()===baseline.head,indexUnchanged:hash(execFileSync('git',['diff','--cached','--binary']))===baseline.index_diff_sha256};
const result={recorded_at:new Date().toISOString(),result:Object.values(checks).every(Boolean)?'PASS':'FAIL',checks,claim_changes:changes,unchanged_claim_records:ac.size-changes.length,prior_evidence_files:priorEvidence.length,changed_existing_files:changedFiles,counts:model.counts,artifacts:Object.fromEntries(['host/payment.mdx','review-server.mjs','verification/current-host-payout-terms-correction.json','verification/current-host-docs-review.json','verification/host-docs-review.html','verification/host-docs-review-export.json'].map(f=>[f,hash(read(f))])),limits:'Integrity and source binding only; browser and test results are retained separately. No payment outcome, individual liability ruling, publication or acceptance.'};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({result:result.result,checks,unchanged_claim_records:result.unchanged_claim_records,prior_evidence_files:priorEvidence.length}));process.exitCode=result.result==='PASS'?0:1;
